package httpapi

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"net/http"
	"time"

	"github.com/google/uuid"
)

// draftCookieName holds the anonymous-draft identity (§5): a random value
// whose SHA-256 is stored as anon_drafts.cookie_hash.
const draftCookieName = "syt_draft"

// draftCookieTTL is the cookie's own lifetime; anon_drafts.expires_at (also
// 30 days, refreshed at creation time only) is the value that actually gates
// access, so an expired cookie and an expired row age out together.
const draftCookieTTL = 30 * 24 * time.Hour

// Per-event gate cookie prefixes and lifetimes (§5). Each cookie is named
// prefix+hex(event id) via eventCookieName/setEventCookie, so one browser
// can hold independent state for many events.
const (
	pwCookiePrefix     = "syt_pw_"
	inviteCookiePrefix = "syt_inv_"
	rsvpCookiePrefix   = "syt_rsvp_"

	accessCookieTTL = 30 * 24 * time.Hour
	inviteCookieTTL = 90 * 24 * time.Hour
	rsvpCookieTTL   = 180 * 24 * time.Hour
)

// randomToken returns a random 32-byte value, base64url-encoded, suitable
// for a cookie whose SHA-256 is what's stored server-side (session tokens
// use the same shape; see internal/auth.Sessions.Create).
func randomToken() (string, error) {
	raw := make([]byte, 32)
	if _, err := rand.Read(raw); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(raw), nil
}

// setDraftCookie sets syt_draft to value, generated by randomToken when no
// cookie already exists for this browser (POST /v1/events reuses an existing
// one rather than minting a fresh identity on every draft).
func (s *Server) setDraftCookie(w http.ResponseWriter, value string) {
	http.SetCookie(w, &http.Cookie{
		Name:     draftCookieName,
		Value:    value,
		Path:     "/",
		Domain:   s.cfg.CookieDomain,
		MaxAge:   int(draftCookieTTL.Seconds()),
		HttpOnly: true,
		Secure:   s.cfg.CookieSecure,
		SameSite: http.SameSiteLaxMode,
	})
}

// clearDraftCookie removes syt_draft after its drafts have been claimed at login.
func (s *Server) clearDraftCookie(w http.ResponseWriter) {
	http.SetCookie(w, &http.Cookie{
		Name:     draftCookieName,
		Path:     "/",
		Domain:   s.cfg.CookieDomain,
		MaxAge:   -1,
		HttpOnly: true,
		Secure:   s.cfg.CookieSecure,
		SameSite: http.SameSiteLaxMode,
	})
}

// setEventCookie sets one of the per-event gate cookies (syt_pw_/syt_inv_/syt_rsvp_,
// per prefix), named with the event id in unpadded hex (no dashes), per §5.
func (s *Server) setEventCookie(w http.ResponseWriter, prefix string, eventID uuid.UUID, value string, ttl time.Duration) {
	http.SetCookie(w, &http.Cookie{
		Name:     prefix + hex.EncodeToString(eventID[:]),
		Value:    value,
		Path:     "/",
		Domain:   s.cfg.CookieDomain,
		Expires:  time.Now().Add(ttl),
		MaxAge:   int(ttl.Seconds()),
		HttpOnly: true,
		Secure:   s.cfg.CookieSecure,
		SameSite: http.SameSiteLaxMode,
	})
}

// eventCookieName returns the name of one of the per-event gate cookies for
// eventID: prefix followed by the event id's unpadded hex (§5).
func eventCookieName(prefix string, eventID uuid.UUID) string {
	return prefix + hex.EncodeToString(eventID[:])
}

// eventCookie reads one of the per-event gate cookies for eventID, or
// ok=false if it's absent or empty. It does not validate the value: callers
// pass it to token.Split / Keys.CheckAccessCookie.
func eventCookie(r *http.Request, prefix string, eventID uuid.UUID) (string, bool) {
	c, err := r.Cookie(eventCookieName(prefix, eventID))
	if err != nil || c.Value == "" {
		return "", false
	}
	return c.Value, true
}

// isValidDraftToken reports whether v has randomToken's exact shape: 32
// random bytes, base64url-encoded without padding, which is always 43
// characters. draftCookieHash rejects anything else so a client can't
// fix a victim's syt_draft to an attacker-chosen or malformed value.
func isValidDraftToken(v string) bool {
	if len(v) != 43 {
		return false
	}
	for _, c := range v {
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9', c == '-', c == '_':
		default:
			return false
		}
	}
	return true
}

// draftCookieHash reads the syt_draft cookie and returns the SHA-256 hash
// stored against it in anon_drafts.cookie_hash, or ok=false if the cookie
// is missing or isn't shaped like a value randomToken could have produced.
func draftCookieHash(r *http.Request) ([]byte, bool) {
	c, err := r.Cookie(draftCookieName)
	if err != nil || !isValidDraftToken(c.Value) {
		return nil, false
	}
	sum := sha256.Sum256([]byte(c.Value))
	return sum[:], true
}
