package content

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// v2SeedSlugs are the 12 launch themes of theme engine v2, in picker order.
// Their manifests live in testdata/themes_v2/<slug>.json (generated by
// design/src/v2/build.mjs) and seed migration 00007 copies them verbatim.
var v2SeedSlugs = []string{
	"olive-grove", "letterpress", "velvet-foil", "sunlit", "sprinkles", "risograph",
	"cloud-nine", "gingham", "open-door", "terrazzo", "gilt-noir", "mirror-ball",
}

// resolvedHexRe is the only colour form a resolved theme may carry: the
// validator upper-cases every hex, so lower case would mean a token or a
// literal slipped through unresolved.
var resolvedHexRe = regexp.MustCompile(`^#[0-9A-F]{6}$`)

func loadV2Seeds(t *testing.T) map[string][]byte {
	t.Helper()
	paths, err := filepath.Glob(filepath.Join("testdata", "themes_v2", "*.json"))
	if err != nil {
		t.Fatalf("glob: %v", err)
	}
	seeds := make(map[string][]byte, len(paths))
	for _, p := range paths {
		raw, err := os.ReadFile(p)
		if err != nil {
			t.Fatalf("read %s: %v", p, err)
		}
		seeds[strings.TrimSuffix(filepath.Base(p), ".json")] = raw
	}
	return seeds
}

func TestV2SeedThemes(t *testing.T) {
	seeds := loadV2Seeds(t)

	got := make([]string, 0, len(seeds))
	for slug := range seeds {
		got = append(got, slug)
	}
	sort.Strings(got)
	want := append([]string(nil), v2SeedSlugs...)
	sort.Strings(want)
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Fatalf("seed themes = %v, want exactly %v", got, want)
	}

	for _, slug := range v2SeedSlugs {
		raw := seeds[slug]
		t.Run(slug, func(t *testing.T) {
			if len(raw) > maxManifestBytes {
				t.Fatalf("manifest is %d bytes, cap is %d", len(raw), maxManifestBytes)
			}
			m, err := ValidateManifest(raw)
			if err != nil {
				t.Fatalf("ValidateManifest: %v", err)
			}
			if m.Schema != 2 {
				t.Fatalf("schema = %d, want 2", m.Schema)
			}
			if n := len(m.Palettes); n < 2 || n > 4 {
				t.Errorf("%d palettes, want 2-4", n)
			}
			if m.Defaults.Palette != m.Palettes[0].ID {
				t.Errorf("default palette %q is not the first palette %q", m.Defaults.Palette, m.Palettes[0].ID)
			}
			if len(m.Layers) < 3 {
				t.Errorf("%d layers, want a stack of at least 3", len(m.Layers))
			}

			// Canonical form is idempotent.
			canon, err := json.Marshal(m)
			if err != nil {
				t.Fatalf("marshal: %v", err)
			}
			m2, err := ValidateManifest(canon)
			if err != nil {
				t.Fatalf("canonical form rejected: %v", err)
			}
			canon2, err := json.Marshal(m2)
			if err != nil {
				t.Fatalf("marshal: %v", err)
			}
			if !bytes.Equal(canon, canon2) {
				t.Errorf("canonical form not idempotent:\n%s\n%s", canon, canon2)
			}

			// Every palette x font pair resolves to hex colours only.
			for _, p := range m.Palettes {
				for _, f := range m.Fonts {
					ov, err := json.Marshal(Overrides{Palette: p.ID, Font: f.ID})
					if err != nil {
						t.Fatalf("marshal overrides: %v", err)
					}
					if _, err := ValidateOverrides(ov, m); err != nil {
						t.Fatalf("overrides %s/%s: %v", p.ID, f.ID, err)
					}
					th := ResolveTheme(m, ov, "")
					where := p.ID + "/" + f.ID
					if th.Engine != 2 {
						t.Errorf("%s: engine = %d, want 2", where, th.Engine)
					}
					if th.Palette != p.Colors {
						t.Errorf("%s: resolved palette %+v, want %+v", where, th.Palette, p.Colors)
					}
					if th.Fonts.Heading != f.Heading || th.Fonts.Body != f.Body || th.Fonts.Accent == "" {
						t.Errorf("%s: fonts %+v", where, th.Fonts)
					}
					for _, c := range resolvedColours(th) {
						if !resolvedHexRe.MatchString(c.hex) {
							t.Errorf("%s: %s = %q is not a resolved hex colour", where, c.at, c.hex)
						}
					}
					if len(th.Layers) != len(m.Layers) {
						t.Errorf("%s: %d resolved layers, want %d (no image layers in seeds)", where, len(th.Layers), len(m.Layers))
					}
				}
			}

			logContrastTable(t, slug, m)
		})
	}
}

type colourAt struct{ at, hex string }

// resolvedColours lists every colour a resolved theme carries.
func resolvedColours(th Theme) []colourAt {
	c := th.Palette
	out := []colourAt{
		{"palette.background", c.Background}, {"palette.surface", c.Surface}, {"palette.text", c.Text},
		{"palette.muted", c.Muted}, {"palette.accent", c.Accent}, {"palette.accent_text", c.AccentText},
		{"accent_ink", th.AccentInk},
	}
	for i, a := range th.Art {
		out = append(out, colourAt{fmt.Sprintf("art[%d]", i), a})
	}
	for i, f := range th.Foil {
		out = append(out, colourAt{fmt.Sprintf("foil[%d]", i), f})
	}
	if th.Ornament != nil {
		out = append(out, colourAt{"ornament.hero_ink", th.Ornament.HeroInk})
	}
	for i, l := range th.Layers {
		for name, v := range map[string]string{"tone": l.Tone, "glow": l.Glow, "vignette": l.Vignette, "color": l.Color} {
			if v != "" {
				out = append(out, colourAt{fmt.Sprintf("layers[%d].%s", i, name), v})
			}
		}
		for j, v := range l.Colors {
			out = append(out, colourAt{fmt.Sprintf("layers[%d].colors[%d]", i, j), v})
		}
	}
	return out
}

// logContrastTable prints every contrast pair the v2 validator checks, per
// palette, so the seed's margins are visible in `go test -v` output.
func logContrastTable(t *testing.T, slug string, m Manifest) {
	t.Helper()
	glass := m.Card.Style == "glass"
	var b strings.Builder
	fmt.Fprintf(&b, "contrast %s (card %s, hero %s)\n", slug, m.Card.Style, m.HeroStyle)
	for _, p := range m.Palettes {
		c := p.Colors
		ink := paletteInk(p, glass)
		backdrop, backdropName := c.Background, "background"
		if m.HeroStyle == "color_block" {
			backdrop, backdropName = c.Accent, "accent block"
		}
		rows := []struct {
			name    string
			fg, bg  string
			minimum float64
		}{
			{"text/background", c.Text, c.Background, minTextContrastV2},
			{"text/surface", c.Text, c.Surface, minTextContrastV2},
			{"muted/background", c.Muted, c.Background, minTextContrastV2},
			{"muted/surface", c.Muted, c.Surface, minTextContrastV2},
			{"accent_text/accent", c.AccentText, c.Accent, minTextContrastV2},
			{"accent_ink/background", ink, c.Background, minTextContrastV2},
			{"accent_ink/surface", ink, c.Surface, minTextContrastV2},
			{"hero_ink/" + backdropName, resolveHeroInk(p, &m, glass), backdrop, minLargeContrast},
		}
		if glass {
			for _, a := range [...]float64{glassAlphaWide, glassAlphaNarrow} {
				bl := blendHex(c.Surface, c.Background, a)
				rows = append(rows,
					struct {
						name    string
						fg, bg  string
						minimum float64
					}{fmt.Sprintf("text/glass %.2f", a), c.Text, bl, minTextContrastV2},
					struct {
						name    string
						fg, bg  string
						minimum float64
					}{fmt.Sprintf("muted/glass %.2f", a), c.Muted, bl, minTextContrastV2},
					struct {
						name    string
						fg, bg  string
						minimum float64
					}{fmt.Sprintf("accent_ink/glass %.2f", a), ink, bl, minTextContrastV2},
				)
			}
		}
		for i, stop := range p.Foil {
			if m.Ornament.Hero == "foil_numeral" {
				rows = append(rows, struct {
					name    string
					fg, bg  string
					minimum float64
				}{fmt.Sprintf("foil[%d]/%s (numeral)", i, backdropName), stop, backdrop, minLargeContrast})
			}
			if m.Card.Buttons == "foil" {
				rows = append(rows, struct {
					name    string
					fg, bg  string
					minimum float64
				}{fmt.Sprintf("accent_text/foil[%d] (button)", i), c.AccentText, stop, minTextContrastV2})
			}
		}
		fmt.Fprintf(&b, "  %s (%s)\n", p.Name, p.ID)
		for _, r := range rows {
			ratio := contrastRatio(r.fg, r.bg)
			mark := "ok"
			if ratio < r.minimum {
				mark = "FAIL"
				t.Errorf("%s/%s: %s %.2f below %.1f", slug, p.ID, r.name, ratio, r.minimum)
			}
			fmt.Fprintf(&b, "    %-34s %s on %s  %5.2f:1  (min %.1f) %s\n", r.name, r.fg, r.bg, ratio, r.minimum, mark)
		}
	}
	t.Log(b.String())
}
