-- +goose Up

-- Starter catalog: occasions, templates and their first published version.
-- The JSON follows the formats validated by internal/content (ParseOccasion, ValidateManifest);
-- a Go test runs these rows through the validators so they can't drift.

INSERT INTO occasions (slug, name, sort_order, default_blocks, optional_blocks, rsvp_fields, copy, setup_questions) VALUES
    ('wedding', 'Wedding', 10,
     '[{"id":"hero","type":"hero","title":"Alex & Sam","subtitle":"are getting married","image":null},{"id":"when","type":"datetime","heading":"When","start_local":"2027-06-12T18:00","end_local":"","timezone":"UTC","all_day":false},{"id":"where","type":"location","heading":"Where","name":"The venue","address":"","map_url":"","notes":""},{"id":"welcome","type":"text","heading":"","body":"We can''t wait to celebrate our wedding with you."},{"id":"rsvp","type":"rsvp","heading":"RSVP","body":"Please let us know if you can make it.","deadline_local":"","capacity":null,"max_party_size":4,"fields":[{"key":"dietary","required":false},{"key":"song_request","required":false},{"key":"message","required":false}],"questions":[]}]',
     '["text","image","gallery","schedule","location","dress_code","links","faq","countdown","guest_photos","rsvp"]',
     '[{"key":"dietary","label":"Dietary requirements","type":"text","required":false,"max_length":200,"options":[],"min":null,"max":null,"help":""},{"key":"song_request","label":"Song request","type":"text","required":false,"max_length":120,"options":[],"min":null,"max":null,"help":""},{"key":"message","label":"Message for the hosts","type":"textarea","required":false,"max_length":500,"options":[],"min":null,"max":null,"help":""}]',
     '{"title_template":"{name_1} & {name_2}","tagline":"are getting married","rsvp_heading":"RSVP","rsvp_body":"Please let us know if you can make it.","share_message":"You''re invited to our wedding! Details and RSVP:"}',
     '[{"key":"name_1","label":"Your name","type":"text","required":true,"max_length":50,"target":"title_var"},{"key":"name_2","label":"Your partner''s name","type":"text","required":true,"max_length":50,"target":"title_var"},{"key":"date","label":"Date and time","type":"date_time","required":false,"max_length":16,"target":"datetime.start_local"},{"key":"timezone","label":"Time zone","type":"timezone","required":false,"max_length":64,"target":"datetime.timezone"},{"key":"venue","label":"Venue","type":"place","required":false,"max_length":120,"target":"location.name"}]'),
    ('engagement', 'Engagement', 20,
     '[{"id":"hero","type":"hero","title":"Alex & Sam","subtitle":"are engaged","image":null},{"id":"when","type":"datetime","heading":"When","start_local":"2027-06-12T18:00","end_local":"","timezone":"UTC","all_day":false},{"id":"where","type":"location","heading":"Where","name":"The venue","address":"","map_url":"","notes":""},{"id":"welcome","type":"text","heading":"","body":"Join us to celebrate our engagement."},{"id":"rsvp","type":"rsvp","heading":"RSVP","body":"Please let us know if you can make it.","deadline_local":"","capacity":null,"max_party_size":4,"fields":[{"key":"dietary","required":false},{"key":"song_request","required":false},{"key":"message","required":false}],"questions":[]}]',
     '["text","image","gallery","schedule","location","dress_code","links","faq","countdown","guest_photos","rsvp"]',
     '[{"key":"dietary","label":"Dietary requirements","type":"text","required":false,"max_length":200,"options":[],"min":null,"max":null,"help":""},{"key":"song_request","label":"Song request","type":"text","required":false,"max_length":120,"options":[],"min":null,"max":null,"help":""},{"key":"message","label":"Message for the hosts","type":"textarea","required":false,"max_length":500,"options":[],"min":null,"max":null,"help":""}]',
     '{"title_template":"{name_1} & {name_2}","tagline":"are engaged","rsvp_heading":"RSVP","rsvp_body":"Please let us know if you can make it.","share_message":"You''re invited to our engagement party! Details and RSVP:"}',
     '[{"key":"name_1","label":"Your name","type":"text","required":true,"max_length":50,"target":"title_var"},{"key":"name_2","label":"Your partner''s name","type":"text","required":true,"max_length":50,"target":"title_var"},{"key":"date","label":"Date and time","type":"date_time","required":false,"max_length":16,"target":"datetime.start_local"},{"key":"timezone","label":"Time zone","type":"timezone","required":false,"max_length":64,"target":"datetime.timezone"},{"key":"venue","label":"Venue","type":"place","required":false,"max_length":120,"target":"location.name"}]'),
    ('birthday', 'Birthday', 30,
     '[{"id":"hero","type":"hero","title":"Sam''s birthday","subtitle":"Join us to celebrate","image":null},{"id":"when","type":"datetime","heading":"When","start_local":"2027-06-12T18:00","end_local":"","timezone":"UTC","all_day":false},{"id":"where","type":"location","heading":"Where","name":"The venue","address":"","map_url":"","notes":""},{"id":"welcome","type":"text","heading":"","body":"Come and celebrate with cake, friends and good times."},{"id":"rsvp","type":"rsvp","heading":"RSVP","body":"Let us know if you''re coming.","deadline_local":"","capacity":null,"max_party_size":4,"fields":[{"key":"dietary","required":false},{"key":"bringing","required":false},{"key":"message","required":false}],"questions":[]}]',
     '["text","image","gallery","schedule","location","dress_code","links","faq","countdown","guest_photos","rsvp"]',
     '[{"key":"dietary","label":"Dietary requirements","type":"text","required":false,"max_length":200,"options":[],"min":null,"max":null,"help":""},{"key":"bringing","label":"What are you bringing?","type":"text","required":false,"max_length":120,"options":[],"min":null,"max":null,"help":""},{"key":"message","label":"Message for the hosts","type":"textarea","required":false,"max_length":500,"options":[],"min":null,"max":null,"help":""}]',
     '{"title_template":"{name}''s birthday","tagline":"Join us to celebrate","rsvp_heading":"RSVP","rsvp_body":"Let us know if you''re coming.","share_message":"You''re invited to a birthday party! Details and RSVP:"}',
     '[{"key":"name","label":"Whose birthday is it?","type":"text","required":true,"max_length":50,"target":"title_var"},{"key":"date","label":"Date and time","type":"date_time","required":false,"max_length":16,"target":"datetime.start_local"},{"key":"timezone","label":"Time zone","type":"timezone","required":false,"max_length":64,"target":"datetime.timezone"},{"key":"venue","label":"Venue","type":"place","required":false,"max_length":120,"target":"location.name"}]'),
    ('baby-shower', 'Baby shower', 40,
     '[{"id":"hero","type":"hero","title":"Baby shower for Sam","subtitle":"Celebrating the little one on the way","image":null},{"id":"when","type":"datetime","heading":"When","start_local":"2027-06-12T18:00","end_local":"","timezone":"UTC","all_day":false},{"id":"where","type":"location","heading":"Where","name":"The venue","address":"","map_url":"","notes":""},{"id":"welcome","type":"text","heading":"","body":"Join us to shower the parents-to-be with love."},{"id":"rsvp","type":"rsvp","heading":"RSVP","body":"Let us know if you''re coming.","deadline_local":"","capacity":null,"max_party_size":4,"fields":[{"key":"dietary","required":false},{"key":"guess","required":false},{"key":"message","required":false}],"questions":[]}]',
     '["text","image","gallery","schedule","location","dress_code","links","faq","countdown","guest_photos","rsvp"]',
     '[{"key":"dietary","label":"Dietary requirements","type":"text","required":false,"max_length":200,"options":[],"min":null,"max":null,"help":""},{"key":"guess","label":"Your guess","type":"select","required":false,"max_length":null,"options":["Boy","Girl","Surprise"],"min":null,"max":null,"help":""},{"key":"message","label":"Message for the hosts","type":"textarea","required":false,"max_length":500,"options":[],"min":null,"max":null,"help":""}]',
     '{"title_template":"Baby shower for {name}","tagline":"Celebrating the little one on the way","rsvp_heading":"RSVP","rsvp_body":"Let us know if you''re coming.","share_message":"You''re invited to a baby shower! Details and RSVP:"}',
     '[{"key":"name","label":"Who is the shower for?","type":"text","required":true,"max_length":50,"target":"title_var"},{"key":"date","label":"Date and time","type":"date_time","required":false,"max_length":16,"target":"datetime.start_local"},{"key":"timezone","label":"Time zone","type":"timezone","required":false,"max_length":64,"target":"datetime.timezone"},{"key":"venue","label":"Venue","type":"place","required":false,"max_length":120,"target":"location.name"}]'),
    ('housewarming', 'Housewarming', 50,
     '[{"id":"hero","type":"hero","title":"Sam''s housewarming","subtitle":"Come see our new place","image":null},{"id":"when","type":"datetime","heading":"When","start_local":"2027-06-12T18:00","end_local":"","timezone":"UTC","all_day":false},{"id":"where","type":"location","heading":"Where","name":"Our new place","address":"","map_url":"","notes":""},{"id":"welcome","type":"text","heading":"","body":"We''ve moved! Come round and help us warm up the new home."},{"id":"rsvp","type":"rsvp","heading":"RSVP","body":"Let us know if you''re coming.","deadline_local":"","capacity":null,"max_party_size":4,"fields":[{"key":"dietary","required":false},{"key":"bringing","required":false},{"key":"message","required":false}],"questions":[]}]',
     '["text","image","gallery","schedule","location","dress_code","links","faq","countdown","guest_photos","rsvp"]',
     '[{"key":"dietary","label":"Dietary requirements","type":"text","required":false,"max_length":200,"options":[],"min":null,"max":null,"help":""},{"key":"bringing","label":"What are you bringing?","type":"text","required":false,"max_length":120,"options":[],"min":null,"max":null,"help":""},{"key":"message","label":"Message for the hosts","type":"textarea","required":false,"max_length":500,"options":[],"min":null,"max":null,"help":""}]',
     '{"title_template":"{host}''s housewarming","tagline":"Come see our new place","rsvp_heading":"RSVP","rsvp_body":"Let us know if you''re coming.","share_message":"You''re invited to our housewarming! Details and RSVP:"}',
     '[{"key":"host","label":"Host name(s)","type":"text","required":true,"max_length":50,"target":"title_var"},{"key":"date","label":"Date and time","type":"date_time","required":false,"max_length":16,"target":"datetime.start_local"},{"key":"timezone","label":"Time zone","type":"timezone","required":false,"max_length":64,"target":"datetime.timezone"},{"key":"address","label":"Address","type":"place","required":false,"max_length":300,"target":"location.address"}]'),
    ('party', 'Party', 60,
     '[{"id":"hero","type":"hero","title":"Summer party","subtitle":"You''re invited","image":null},{"id":"when","type":"datetime","heading":"When","start_local":"2027-06-12T18:00","end_local":"","timezone":"UTC","all_day":false},{"id":"where","type":"location","heading":"Where","name":"The venue","address":"","map_url":"","notes":""},{"id":"welcome","type":"text","heading":"","body":"Join us for an evening of good food and good company."},{"id":"rsvp","type":"rsvp","heading":"RSVP","body":"Let us know if you''re coming.","deadline_local":"","capacity":null,"max_party_size":4,"fields":[{"key":"dietary","required":false},{"key":"bringing","required":false},{"key":"message","required":false}],"questions":[]}]',
     '["text","image","gallery","schedule","location","dress_code","links","faq","countdown","guest_photos","rsvp"]',
     '[{"key":"dietary","label":"Dietary requirements","type":"text","required":false,"max_length":200,"options":[],"min":null,"max":null,"help":""},{"key":"bringing","label":"What are you bringing?","type":"text","required":false,"max_length":120,"options":[],"min":null,"max":null,"help":""},{"key":"message","label":"Message for the hosts","type":"textarea","required":false,"max_length":500,"options":[],"min":null,"max":null,"help":""}]',
     '{"title_template":"{title}","tagline":"You''re invited","rsvp_heading":"RSVP","rsvp_body":"Let us know if you''re coming.","share_message":"You''re invited! Details and RSVP:"}',
     '[{"key":"title","label":"What''s the occasion?","type":"text","required":true,"max_length":60,"target":"title_var"},{"key":"tagline","label":"Tagline","type":"text","required":false,"max_length":120,"target":"hero.subtitle"},{"key":"date","label":"Date and time","type":"date_time","required":false,"max_length":16,"target":"datetime.start_local"},{"key":"timezone","label":"Time zone","type":"timezone","required":false,"max_length":64,"target":"datetime.timezone"},{"key":"venue","label":"Venue","type":"place","required":false,"max_length":120,"target":"location.name"}]');

INSERT INTO templates (id, slug, name, tags, status) VALUES
    ('01926a00-0000-7000-8000-000000000001', 'classic', 'Classic', '{"occasions":["wedding","engagement","birthday","baby-shower","housewarming","party"]}', 'published'),
    ('01926a00-0000-7000-8000-000000000002', 'garden', 'Garden', '{"occasions":["wedding","engagement","baby-shower"]}', 'published'),
    ('01926a00-0000-7000-8000-000000000003', 'modern', 'Modern', '{"occasions":["wedding","engagement","birthday","baby-shower","housewarming","party"]}', 'published'),
    ('01926a00-0000-7000-8000-000000000004', 'confetti', 'Confetti', '{"occasions":["birthday","party","baby-shower","housewarming"]}', 'published'),
    ('01926a00-0000-7000-8000-000000000005', 'minimal', 'Minimal', '{"occasions":["wedding","engagement","birthday","baby-shower","housewarming","party"]}', 'published');

INSERT INTO template_versions (template_id, version, manifest, assets_path, created_by, published_at) VALUES
    ('01926a00-0000-7000-8000-000000000001', 1,
     '{"schema":1,"layout":"centered","hero_style":"framed","decoration":"line","palettes":[{"id":"ivory","name":"Ivory","colors":{"background":"#FBF8F3","surface":"#FFFFFF","text":"#1F1B16","muted":"#6B645C","accent":"#8C6A3F","accent_text":"#FFFFFF"}},{"id":"navy","name":"Navy","colors":{"background":"#F4F6FA","surface":"#FFFFFF","text":"#14213D","muted":"#56607A","accent":"#1F3A68","accent_text":"#FFFFFF"}},{"id":"sage","name":"Sage","colors":{"background":"#F3F6F1","surface":"#FFFFFF","text":"#1E2A1F","muted":"#5C6B5D","accent":"#4A6B4E","accent_text":"#FFFFFF"}}],"fonts":[{"id":"playfair","name":"Playfair and Lora","heading":"playfair_display","body":"lora"},{"id":"cormorant","name":"Cormorant and Figtree","heading":"cormorant_garamond","body":"figtree"}],"defaults":{"palette":"ivory","font":"playfair"},"background":null}',
     '', NULL, now()),
    ('01926a00-0000-7000-8000-000000000002', 1,
     '{"schema":1,"layout":"centered","hero_style":"full_bleed","decoration":"floral","palettes":[{"id":"blush","name":"Blush","colors":{"background":"#FDF4F2","surface":"#FFFFFF","text":"#3A2027","muted":"#7A5A60","accent":"#A64D63","accent_text":"#FFFFFF"}},{"id":"meadow","name":"Meadow","colors":{"background":"#F4F8EE","surface":"#FFFFFF","text":"#1F2B17","muted":"#5A6B4C","accent":"#4F7A2E","accent_text":"#FFFFFF"}},{"id":"lavender","name":"Lavender","colors":{"background":"#F6F3FB","surface":"#FFFFFF","text":"#2A2140","muted":"#675D80","accent":"#6B4FA0","accent_text":"#FFFFFF"}}],"fonts":[{"id":"cormorant","name":"Cormorant and Lora","heading":"cormorant_garamond","body":"lora"},{"id":"script","name":"Great Vibes and Lora","heading":"great_vibes","body":"lora"}],"defaults":{"palette":"blush","font":"cormorant"},"background":null}',
     '', NULL, now()),
    ('01926a00-0000-7000-8000-000000000003', 1,
     '{"schema":1,"layout":"split","hero_style":"full_bleed","decoration":"none","palettes":[{"id":"mono","name":"Mono","colors":{"background":"#FFFFFF","surface":"#F4F4F4","text":"#111111","muted":"#666666","accent":"#111111","accent_text":"#FFFFFF"}},{"id":"ocean","name":"Ocean","colors":{"background":"#F1F7FA","surface":"#FFFFFF","text":"#0E2A38","muted":"#4F6B78","accent":"#0F6E8C","accent_text":"#FFFFFF"}},{"id":"terracotta","name":"Terracotta","colors":{"background":"#FAF3EE","surface":"#FFFFFF","text":"#2E1D14","muted":"#7A5F50","accent":"#A8502C","accent_text":"#FFFFFF"}}],"fonts":[{"id":"grotesque","name":"Bricolage and Figtree","heading":"bricolage_grotesque","body":"figtree"},{"id":"serif","name":"DM Serif and Figtree","heading":"dm_serif_display","body":"figtree"}],"defaults":{"palette":"mono","font":"grotesque"},"background":null}',
     '', NULL, now()),
    ('01926a00-0000-7000-8000-000000000004', 1,
     '{"schema":1,"layout":"centered","hero_style":"text_only","decoration":"dots","palettes":[{"id":"sunshine","name":"Sunshine","colors":{"background":"#FFF9E6","surface":"#FFFFFF","text":"#2B2100","muted":"#6E6340","accent":"#F2C12E","accent_text":"#2B2100"}},{"id":"bubblegum","name":"Bubblegum","colors":{"background":"#FFF1F7","surface":"#FFFFFF","text":"#3A0F24","muted":"#7D5468","accent":"#C2185B","accent_text":"#FFFFFF"}},{"id":"mint","name":"Mint","colors":{"background":"#EFFAF5","surface":"#FFFFFF","text":"#0F2E22","muted":"#4E6E61","accent":"#0E7A55","accent_text":"#FFFFFF"}}],"fonts":[{"id":"fraunces","name":"Fraunces and Figtree","heading":"fraunces","body":"figtree"},{"id":"grotesque","name":"Bricolage and Figtree","heading":"bricolage_grotesque","body":"figtree"}],"defaults":{"palette":"sunshine","font":"fraunces"},"background":null}',
     '', NULL, now()),
    ('01926a00-0000-7000-8000-000000000005', 1,
     '{"schema":1,"layout":"stacked","hero_style":"text_only","decoration":"none","palettes":[{"id":"paper","name":"Paper","colors":{"background":"#FFFFFF","surface":"#FAFAFA","text":"#1A1A1A","muted":"#6B6B6B","accent":"#1A1A1A","accent_text":"#FFFFFF"}},{"id":"charcoal","name":"Charcoal","colors":{"background":"#1C1C1E","surface":"#2A2A2D","text":"#F2F2F2","muted":"#A0A0A6","accent":"#F2F2F2","accent_text":"#1C1C1E"}}],"fonts":[{"id":"sans","name":"Figtree","heading":"figtree","body":"figtree"},{"id":"serif","name":"Lora","heading":"lora","body":"lora"}],"defaults":{"palette":"paper","font":"sans"},"background":null}',
     '', NULL, now());

-- +goose Down

-- Dev only. Fails if events reference the seeded rows (FK RESTRICT / NO ACTION), which is intended.
ALTER TABLE template_versions DISABLE TRIGGER template_versions_immutable;
DELETE FROM template_versions WHERE template_id IN ('01926a00-0000-7000-8000-000000000001', '01926a00-0000-7000-8000-000000000002', '01926a00-0000-7000-8000-000000000003', '01926a00-0000-7000-8000-000000000004', '01926a00-0000-7000-8000-000000000005');
ALTER TABLE template_versions ENABLE TRIGGER template_versions_immutable;
DELETE FROM templates WHERE id IN ('01926a00-0000-7000-8000-000000000001', '01926a00-0000-7000-8000-000000000002', '01926a00-0000-7000-8000-000000000003', '01926a00-0000-7000-8000-000000000004', '01926a00-0000-7000-8000-000000000005');
DELETE FROM occasions WHERE slug IN ('wedding', 'engagement', 'birthday', 'baby-shower', 'housewarming', 'party');
