-- +goose Up

-- All primary keys are UUIDv7, generated by the API so they sort by creation time.

-- Hosts and admins. Guests never get a row here.
CREATE TABLE users (
    id          uuid PRIMARY KEY,
    email       text NOT NULL CHECK (email = lower(email)),
    name        text NOT NULL DEFAULT '',
    status      text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'banned')),
    totp_secret text, -- encrypted authenticator secret, required for admins
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    deleted_at  timestamptz
);
CREATE UNIQUE INDEX users_email_key ON users (email) WHERE deleted_at IS NULL;
CREATE INDEX users_search_idx ON users USING gin (to_tsvector('simple', email || ' ' || name));

CREATE TABLE user_roles (
    user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role       text NOT NULL CHECK (role IN ('super_admin', 'moderator', 'support')),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role)
);

-- The cookie holds a random token; only its SHA-256 hash is stored.
-- Mirrored in Valkey for fast lookups.
CREATE TABLE sessions (
    id           uuid PRIMARY KEY,
    user_id      uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash   bytea NOT NULL UNIQUE,
    expires_at   timestamptz NOT NULL,
    ip           inet,
    user_agent   text NOT NULL DEFAULT '',
    created_at   timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX sessions_user_id_idx ON sessions (user_id);
CREATE INDEX sessions_expires_at_idx ON sessions (expires_at);

-- Occasions are presets: default blocks, RSVP questions and suggested wording.
CREATE TABLE occasions (
    slug            text PRIMARY KEY,
    name            text NOT NULL,
    default_blocks  jsonb NOT NULL DEFAULT '[]',
    optional_blocks jsonb NOT NULL DEFAULT '[]',
    rsvp_fields     jsonb NOT NULL DEFAULT '[]',
    copy            jsonb NOT NULL DEFAULT '{}',
    setup_questions jsonb NOT NULL DEFAULT '[]',
    sort_order      int NOT NULL DEFAULT 0,
    is_active       boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE templates (
    id         uuid PRIMARY KEY,
    slug       text NOT NULL UNIQUE,
    name       text NOT NULL,
    tags       jsonb NOT NULL DEFAULT '{}',
    status     text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'retired')),
    is_premium boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Immutable once published_at is set; events pin a version.
CREATE TABLE template_versions (
    template_id  uuid NOT NULL REFERENCES templates (id) ON DELETE RESTRICT,
    version      int NOT NULL CHECK (version > 0),
    manifest     jsonb NOT NULL,
    assets_path  text NOT NULL DEFAULT '',
    created_by   uuid REFERENCES users (id) ON DELETE SET NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    published_at timestamptz,
    PRIMARY KEY (template_id, version)
);

CREATE TABLE events (
    id               uuid PRIMARY KEY,
    owner_id         uuid REFERENCES users (id) ON DELETE RESTRICT, -- null while an anonymous draft
    occasion_slug    text NOT NULL REFERENCES occasions (slug) ON UPDATE CASCADE,
    slug             text UNIQUE CHECK (slug ~ '^[a-z0-9](?:[a-z0-9-]{1,48}[a-z0-9])$'),
    title            text NOT NULL DEFAULT '',
    content          jsonb NOT NULL DEFAULT '[]', -- ordered list of typed blocks
    template_id      uuid NOT NULL,
    template_version int NOT NULL,
    overrides        jsonb NOT NULL DEFAULT '{}', -- palette and font pairing choice
    visibility       text NOT NULL DEFAULT 'unlisted' CHECK (visibility IN ('unlisted', 'password', 'invite_only', 'public')),
    password_hash    text, -- Argon2id, only when visibility = 'password'
    rsvp_mode        text NOT NULL DEFAULT 'open' CHECK (rsvp_mode IN ('open', 'invite_only')),
    status           text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'hidden', 'taken_down')),
    remove_branding  boolean NOT NULL DEFAULT false,
    starts_at        timestamptz,
    published_at     timestamptz,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    deleted_at       timestamptz,
    FOREIGN KEY (template_id, template_version) REFERENCES template_versions (template_id, version),
    CHECK (visibility <> 'password' OR password_hash IS NOT NULL),
    CHECK (status = 'draft' OR (owner_id IS NOT NULL AND slug IS NOT NULL))
);
CREATE INDEX events_owner_id_idx ON events (owner_id) WHERE deleted_at IS NULL;
CREATE INDEX events_search_idx ON events USING gin (to_tsvector('simple', coalesce(slug, '') || ' ' || title));

-- Ties a draft to a browser before sign-up. Claimed (deleted) at publish, or expires after 30 days.
CREATE TABLE anon_drafts (
    id          uuid PRIMARY KEY,
    cookie_hash bytea NOT NULL,
    event_id    uuid NOT NULL UNIQUE REFERENCES events (id) ON DELETE CASCADE,
    expires_at  timestamptz NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX anon_drafts_cookie_hash_idx ON anon_drafts (cookie_hash);
CREATE INDEX anon_drafts_expires_at_idx ON anon_drafts (expires_at);

-- Co-hosts.
CREATE TABLE event_members (
    event_id   uuid NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role       text NOT NULL CHECK (role IN ('editor', 'viewer')),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (event_id, user_id)
);
CREATE INDEX event_members_user_id_idx ON event_members (user_id);

-- Invited guests for invite-only events. No account needed.
CREATE TABLE guests (
    id             uuid PRIMARY KEY,
    event_id       uuid NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    name           text NOT NULL,
    email          text,
    phone          text,
    household_size int NOT NULL DEFAULT 1 CHECK (household_size BETWEEN 1 AND 50),
    invite_token   text NOT NULL UNIQUE,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX guests_event_id_idx ON guests (event_id);

-- Open RSVPs have no guest_id.
CREATE TABLE rsvps (
    id              uuid PRIMARY KEY,
    event_id        uuid NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    guest_id        uuid REFERENCES guests (id) ON DELETE CASCADE,
    name            text NOT NULL,
    email           text,
    attending       text NOT NULL CHECK (attending IN ('yes', 'no', 'maybe')),
    count           int NOT NULL DEFAULT 1 CHECK (count BETWEEN 0 AND 50),
    answers         jsonb NOT NULL DEFAULT '{}',
    edit_token_hash bytea NOT NULL UNIQUE, -- for the "edit your RSVP" emailed link
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX rsvps_event_id_idx ON rsvps (event_id);
CREATE UNIQUE INDEX rsvps_event_guest_key ON rsvps (event_id, guest_id) WHERE guest_id IS NOT NULL;

-- Originals only; imgproxy serves resized variants.
CREATE TABLE media (
    id                uuid PRIMARY KEY,
    owner_id          uuid REFERENCES users (id) ON DELETE SET NULL,
    event_id          uuid REFERENCES events (id) ON DELETE CASCADE,
    storage_key       text NOT NULL UNIQUE,
    content_type      text NOT NULL,
    size_bytes        bigint NOT NULL CHECK (size_bytes > 0),
    width             int,
    height            int,
    uploaded_by       text NOT NULL CHECK (uploaded_by IN ('host', 'guest')),
    guest_id          uuid REFERENCES guests (id) ON DELETE SET NULL,
    moderation_status text NOT NULL DEFAULT 'approved' CHECK (moderation_status IN ('pending', 'approved', 'rejected')),
    created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX media_event_id_idx ON media (event_id);
CREATE INDEX media_pending_idx ON media (created_at) WHERE moderation_status = 'pending';

-- From "Report this page".
CREATE TABLE reports (
    id               uuid PRIMARY KEY,
    event_id         uuid NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    reporter_ip_hash bytea NOT NULL,
    reason           text NOT NULL CHECK (reason IN ('phishing', 'spam', 'harassment', 'illegal', 'other')),
    details          text NOT NULL DEFAULT '',
    status           text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'reviewing', 'dismissed', 'taken_down', 'restored')),
    handled_by       uuid REFERENCES users (id) ON DELETE SET NULL,
    handled_at       timestamptz,
    created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX reports_event_id_created_at_idx ON reports (event_id, created_at);
CREATE INDEX reports_open_idx ON reports (created_at) WHERE status IN ('open', 'reviewing');

CREATE TABLE slug_blocklist (
    term       text PRIMARY KEY CHECK (term = lower(term)),
    reason     text NOT NULL CHECK (reason IN ('reserved', 'abuse', 'brand')),
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Append-only record of admin actions.
CREATE TABLE audit_log (
    id          uuid PRIMARY KEY,
    actor_id    uuid REFERENCES users (id) ON DELETE SET NULL,
    action      text NOT NULL,
    target_type text NOT NULL,
    target_id   text NOT NULL,
    before      jsonb,
    after       jsonb,
    ip          inet,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_target_idx ON audit_log (target_type, target_id, created_at);
CREATE INDEX audit_log_actor_idx ON audit_log (actor_id, created_at);

-- +goose StatementBegin
CREATE FUNCTION audit_log_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_log is append-only';
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER audit_log_no_update_delete
    BEFORE UPDATE OR DELETE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION audit_log_append_only();

INSERT INTO slug_blocklist (term, reason) VALUES
    ('app', 'reserved'), ('admin', 'reserved'), ('api', 'reserved'), ('login', 'reserved'),
    ('logout', 'reserved'), ('signup', 'reserved'), ('templates', 'reserved'), ('help', 'reserved'),
    ('about', 'reserved'), ('privacy', 'reserved'), ('terms', 'reserved'), ('pricing', 'reserved'),
    ('blog', 'reserved'), ('static', 'reserved'), ('assets', 'reserved'), ('img', 'reserved'),
    ('_next', 'reserved'), ('status', 'reserved'), ('settings', 'reserved'), ('account', 'reserved'),
    ('verify', 'abuse'), ('support', 'abuse'), ('secure', 'abuse'), ('security', 'abuse'),
    ('password', 'abuse'), ('reset', 'abuse'), ('wallet', 'abuse'), ('billing', 'abuse'),
    ('payment', 'abuse'), ('invoice', 'abuse'), ('refund', 'abuse'), ('bank', 'abuse'),
    ('paypal', 'brand'), ('google', 'brand'), ('apple', 'brand'), ('microsoft', 'brand'),
    ('whatsapp', 'brand'), ('facebook', 'brand'), ('instagram', 'brand'), ('amazon', 'brand'),
    ('netflix', 'brand'), ('emiratesnbd', 'brand'), ('adcb', 'brand'), ('hdfc', 'brand'),
    ('icici', 'brand'), ('sbi', 'brand'), ('paytm', 'brand'), ('etisalat', 'brand');

-- +goose Down
DROP TABLE audit_log, slug_blocklist, reports, media, rsvps, guests, event_members,
    anon_drafts, events, template_versions, templates, occasions, sessions, user_roles, users;
DROP FUNCTION audit_log_append_only();
