// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (id, actor_id, action, target_type, target_id, before, after, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditLogParams struct {
	ID         uuid.UUID   `json:"id"`
	ActorID    *uuid.UUID  `json:"actor_id"`
	Action     string      `json:"action"`
	TargetType string      `json:"target_type"`
	TargetID   string      `json:"target_id"`
	Before     []byte      `json:"before"`
	After      []byte      `json:"after"`
	Ip         *netip.Addr `json:"ip"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Before,
		arg.After,
		arg.Ip,
	)
	return err
}

const listAuditByActor = `-- name: ListAuditByActor :many
SELECT id, actor_id, action, target_type, target_id, before, after, ip, created_at
FROM audit_log
WHERE actor_id = $1::uuid
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type ListAuditByActorParams struct {
	ActorID         uuid.UUID `json:"actor_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	Lim             int32     `json:"lim"`
}

// Entries by one admin, newest first (audit_log_actor_idx).
func (q *Queries) ListAuditByActor(ctx context.Context, arg ListAuditByActorParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByActor,
		arg.ActorID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Before,
			&i.After,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditForTarget = `-- name: ListAuditForTarget :many
SELECT id, actor_id, action, target_type, target_id, before, after, ip, created_at
FROM audit_log
WHERE target_type = $1
  AND target_id = $2
  AND (created_at, id) < ($3::timestamptz, $4::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $5::int
`

type ListAuditForTargetParams struct {
	TargetType      string    `json:"target_type"`
	TargetID        string    `json:"target_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	Lim             int32     `json:"lim"`
}

// Entries about one object, newest first (audit_log_target_idx). The user detail page passes lim 20.
func (q *Queries) ListAuditForTarget(ctx context.Context, arg ListAuditForTargetParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditForTarget,
		arg.TargetType,
		arg.TargetID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Before,
			&i.After,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, actor_id, action, target_type, target_id, before, after, ip, created_at
FROM audit_log
WHERE (created_at, id) < ($1::timestamptz, $2::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $3::int
`

type ListAuditLogParams struct {
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	Lim             int32     `json:"lim"`
}

// Global view, newest first (audit_log_created_idx).
func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog, arg.CursorCreatedAt, arg.CursorID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Before,
			&i.After,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
