// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getOccasion = `-- name: GetOccasion :one
SELECT slug, name, default_blocks, optional_blocks, rsvp_fields, copy, setup_questions, sort_order, is_active, created_at, updated_at FROM occasions
WHERE slug = $1 AND is_active
`

// For picking an occasion when creating a new event; deactivated occasions aren't offered.
func (q *Queries) GetOccasion(ctx context.Context, slug string) (Occasion, error) {
	row := q.db.QueryRow(ctx, getOccasion, slug)
	var i Occasion
	err := row.Scan(
		&i.Slug,
		&i.Name,
		&i.DefaultBlocks,
		&i.OptionalBlocks,
		&i.RsvpFields,
		&i.Copy,
		&i.SetupQuestions,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOccasionForEvent = `-- name: GetOccasionForEvent :one
SELECT slug, name, default_blocks, optional_blocks, rsvp_fields, copy, setup_questions, sort_order, is_active, created_at, updated_at FROM occasions
WHERE slug = $1
`

// For loading an existing event's occasion (e.g. rendering/editing it). No is_active filter:
// an occasion can be deactivated for new events after events already reference it, and those
// existing events must keep loading it instead of 500ing.
func (q *Queries) GetOccasionForEvent(ctx context.Context, slug string) (Occasion, error) {
	row := q.db.QueryRow(ctx, getOccasionForEvent, slug)
	var i Occasion
	err := row.Scan(
		&i.Slug,
		&i.Name,
		&i.DefaultBlocks,
		&i.OptionalBlocks,
		&i.RsvpFields,
		&i.Copy,
		&i.SetupQuestions,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedTemplateBySlug = `-- name: GetPublishedTemplateBySlug :one
SELECT t.id, t.slug, t.name, t.is_premium, v.version, v.manifest, v.assets_path
FROM templates t
JOIN LATERAL (
    SELECT tv.version, tv.manifest, tv.assets_path
    FROM template_versions tv
    WHERE tv.template_id = t.id AND tv.published_at IS NOT NULL
    ORDER BY tv.version DESC
    LIMIT 1
) v ON true
WHERE t.slug = $1
  AND t.status = 'published'
  AND ($2::bool OR NOT t.is_premium)
`

type GetPublishedTemplateBySlugParams struct {
	Slug         string `json:"slug"`
	AllowPremium bool   `json:"allow_premium"`
}

type GetPublishedTemplateBySlugRow struct {
	ID         uuid.UUID `json:"id"`
	Slug       string    `json:"slug"`
	Name       string    `json:"name"`
	IsPremium  bool      `json:"is_premium"`
	Version    int32     `json:"version"`
	Manifest   []byte    `json:"manifest"`
	AssetsPath string    `json:"assets_path"`
}

// allow_premium is true only on the admin flags endpoint.
func (q *Queries) GetPublishedTemplateBySlug(ctx context.Context, arg GetPublishedTemplateBySlugParams) (GetPublishedTemplateBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublishedTemplateBySlug, arg.Slug, arg.AllowPremium)
	var i GetPublishedTemplateBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.IsPremium,
		&i.Version,
		&i.Manifest,
		&i.AssetsPath,
	)
	return i, err
}

const getTemplateVersion = `-- name: GetTemplateVersion :one
SELECT template_id, version, manifest, assets_path, created_by, created_at, published_at FROM template_versions
WHERE template_id = $1 AND version = $2
`

type GetTemplateVersionParams struct {
	TemplateID uuid.UUID `json:"template_id"`
	Version    int32     `json:"version"`
}

func (q *Queries) GetTemplateVersion(ctx context.Context, arg GetTemplateVersionParams) (TemplateVersion, error) {
	row := q.db.QueryRow(ctx, getTemplateVersion, arg.TemplateID, arg.Version)
	var i TemplateVersion
	err := row.Scan(
		&i.TemplateID,
		&i.Version,
		&i.Manifest,
		&i.AssetsPath,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listActiveOccasions = `-- name: ListActiveOccasions :many
SELECT slug, name, default_blocks, optional_blocks, rsvp_fields, copy, setup_questions, sort_order, is_active, created_at, updated_at FROM occasions
WHERE is_active
ORDER BY sort_order, slug
LIMIT 100
`

// Tiny table; the full row feeds content.ParseOccasion.
func (q *Queries) ListActiveOccasions(ctx context.Context) ([]Occasion, error) {
	rows, err := q.db.Query(ctx, listActiveOccasions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Occasion{}
	for rows.Next() {
		var i Occasion
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.DefaultBlocks,
			&i.OptionalBlocks,
			&i.RsvpFields,
			&i.Copy,
			&i.SetupQuestions,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedTemplates = `-- name: ListPublishedTemplates :many
SELECT t.id, t.slug, t.name, t.tags, v.version, v.manifest, v.assets_path
FROM templates t
JOIN LATERAL (
    SELECT tv.version, tv.manifest, tv.assets_path
    FROM template_versions tv
    WHERE tv.template_id = t.id AND tv.published_at IS NOT NULL
    ORDER BY tv.version DESC
    LIMIT 1
) v ON true
WHERE t.status = 'published'
  AND NOT t.is_premium
  AND ($1::text IS NULL
       OR t.tags @> jsonb_build_object('occasions', jsonb_build_array($1::text)))
ORDER BY t.name, t.id
LIMIT 100
`

type ListPublishedTemplatesRow struct {
	ID         uuid.UUID `json:"id"`
	Slug       string    `json:"slug"`
	Name       string    `json:"name"`
	Tags       []byte    `json:"tags"`
	Version    int32     `json:"version"`
	Manifest   []byte    `json:"manifest"`
	AssetsPath string    `json:"assets_path"`
}

// Host picker: published, non-premium templates with their latest published version.
// occasion NULL lists every template.
func (q *Queries) ListPublishedTemplates(ctx context.Context, occasion *string) ([]ListPublishedTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedTemplates, occasion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedTemplatesRow{}
	for rows.Next() {
		var i ListPublishedTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Tags,
			&i.Version,
			&i.Manifest,
			&i.AssetsPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
