// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimAnonDraftMedia = `-- name: ClaimAnonDraftMedia :exec
UPDATE media
SET owner_id = $1::uuid
WHERE event_id = ANY($2::uuid[]) AND owner_id IS NULL
`

type ClaimAnonDraftMediaParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	EventIds []uuid.UUID `json:"event_ids"`
}

func (q *Queries) ClaimAnonDraftMedia(ctx context.Context, arg ClaimAnonDraftMediaParams) error {
	_, err := q.db.Exec(ctx, claimAnonDraftMedia, arg.UserID, arg.EventIds)
	return err
}

const claimAnonDrafts = `-- name: ClaimAnonDrafts :many
WITH claimed AS (
    DELETE FROM anon_drafts a
    WHERE a.cookie_hash = $2 AND a.expires_at > now()
    RETURNING a.event_id
)
UPDATE events e
SET owner_id = $1::uuid, updated_at = now()
FROM claimed c
WHERE e.id = c.event_id AND e.owner_id IS NULL
RETURNING e.id
`

type ClaimAnonDraftsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	CookieHash []byte    `json:"cookie_hash"`
}

// At login: hands every unexpired draft of this browser to the user. Soft-deleted drafts are
// claimed too, so the 30-day purge removes them instead of leaving ownerless rows behind.
func (q *Queries) ClaimAnonDrafts(ctx context.Context, arg ClaimAnonDraftsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, claimAnonDrafts, arg.UserID, arg.CookieHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimRSVPWatermark = `-- name: ClaimRSVPWatermark :one
WITH prev AS (
    SELECT x.id, x.rsvp_notified_at FROM events x
    WHERE x.id = $1 AND x.deleted_at IS NULL
    FOR NO KEY UPDATE
)
UPDATE events e
SET rsvp_notified_at = now()
FROM prev
WHERE e.id = prev.id
RETURNING prev.rsvp_notified_at AS previous_notified_at, e.rsvp_notified_at::timestamptz AS notified_at
`

type ClaimRSVPWatermarkRow struct {
	PreviousNotifiedAt *time.Time `json:"previous_notified_at"`
	NotifiedAt         time.Time  `json:"notified_at"`
}

// Digest job: returns the previous watermark (NULL = never) and moves it to now().
func (q *Queries) ClaimRSVPWatermark(ctx context.Context, eventID uuid.UUID) (ClaimRSVPWatermarkRow, error) {
	row := q.db.QueryRow(ctx, claimRSVPWatermark, eventID)
	var i ClaimRSVPWatermarkRow
	err := row.Scan(&i.PreviousNotifiedAt, &i.NotifiedAt)
	return i, err
}

const countAnonDraftsByCookie = `-- name: CountAnonDraftsByCookie :one
SELECT count(*) FROM anon_drafts
WHERE cookie_hash = $1 AND expires_at > now()
`

func (q *Queries) CountAnonDraftsByCookie(ctx context.Context, cookieHash []byte) (int64, error) {
	row := q.db.QueryRow(ctx, countAnonDraftsByCookie, cookieHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveEventsByOwner = `-- name: CountLiveEventsByOwner :one
SELECT count(*) FROM events
WHERE owner_id = $1::uuid AND deleted_at IS NULL
`

func (q *Queries) CountLiveEventsByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveEventsByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnonDraft = `-- name: CreateAnonDraft :exec
INSERT INTO anon_drafts (id, cookie_hash, event_id, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateAnonDraftParams struct {
	ID         uuid.UUID `json:"id"`
	CookieHash []byte    `json:"cookie_hash"`
	EventID    uuid.UUID `json:"event_id"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) CreateAnonDraft(ctx context.Context, arg CreateAnonDraftParams) error {
	_, err := q.db.Exec(ctx, createAnonDraft,
		arg.ID,
		arg.CookieHash,
		arg.EventID,
		arg.ExpiresAt,
	)
	return err
}

const createEvent = `-- name: CreateEvent :one


INSERT INTO events (id, owner_id, occasion_slug, title, content, template_id, template_version, overrides, starts_at)
SELECT $1::uuid, $2::uuid, $3::text, $4::text, $5::jsonb,
       t.id, tv.version, $6::jsonb, $7::timestamptz
FROM templates t
JOIN template_versions tv ON tv.template_id = t.id
WHERE t.id = $8::uuid
  AND tv.version = $9::int
  AND tv.published_at IS NOT NULL
  AND t.status = 'published'
  AND NOT t.is_premium
RETURNING id, owner_id, occasion_slug, slug, title, content, template_id, template_version, overrides, visibility, password_hash, rsvp_mode, status, remove_branding, starts_at, published_at, created_at, updated_at, deleted_at, version, notify_rsvps, rsvp_notified_at
`

type CreateEventParams struct {
	ID              uuid.UUID  `json:"id"`
	OwnerID         *uuid.UUID `json:"owner_id"`
	OccasionSlug    string     `json:"occasion_slug"`
	Title           string     `json:"title"`
	Content         []byte     `json:"content"`
	Overrides       []byte     `json:"overrides"`
	StartsAt        *time.Time `json:"starts_at"`
	TemplateID      uuid.UUID  `json:"template_id"`
	TemplateVersion int32      `json:"template_version"`
}

// Event-scoped authorisation lives in the WHERE clause of each query (event_role, owner_id, or the
// anonymous-draft cookie hash). No row means "not found or no access"; callers map it to 404.
// Keyset cursors: first page of a DESC list passes (far future, max uuid); of an ASC list (zero time, nil uuid).
// Template pins set by hosts must name a published version of a published, non-premium template.
// Admin changes go through SetEventFlags instead.
// No row when the template pin is not selectable; the caller maps pgx.ErrNoRows to a validation error.
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ID,
		arg.OwnerID,
		arg.OccasionSlug,
		arg.Title,
		arg.Content,
		arg.Overrides,
		arg.StartsAt,
		arg.TemplateID,
		arg.TemplateVersion,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.OccasionSlug,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.TemplateID,
		&i.TemplateVersion,
		&i.Overrides,
		&i.Visibility,
		&i.PasswordHash,
		&i.RsvpMode,
		&i.Status,
		&i.RemoveBranding,
		&i.StartsAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.NotifyRsvps,
		&i.RsvpNotifiedAt,
	)
	return i, err
}

const deleteExpiredAnonDraftEvents = `-- name: DeleteExpiredAnonDraftEvents :execrows
DELETE FROM events
WHERE id IN (SELECT a.event_id FROM anon_drafts a WHERE a.expires_at <= now() LIMIT 500)
  AND owner_id IS NULL
`

// Hard-deletes expired, unclaimed drafts in batches (anon_drafts and media rows cascade; files go via reconcile).
func (q *Queries) DeleteExpiredAnonDraftEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAnonDraftEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const existingEventIDs = `-- name: ExistingEventIDs :many
SELECT id FROM events WHERE id = ANY($1::uuid[])
`

// Media reconcile: which of these directory names still have an event row (deleted or not).
func (q *Queries) ExistingEventIDs(ctx context.Context, eventIds []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, existingEventIDs, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnonDraftEvent = `-- name: GetAnonDraftEvent :one
SELECT e.id, e.owner_id, e.occasion_slug, e.slug, e.title, e.content, e.template_id, e.template_version, e.overrides, e.visibility, e.password_hash, e.rsvp_mode, e.status, e.remove_branding, e.starts_at, e.published_at, e.created_at, e.updated_at, e.deleted_at, e.version, e.notify_rsvps, e.rsvp_notified_at, 'anon'::text AS role,
       t.slug AS template_slug, t.name AS template_name,
       tv.manifest, tv.assets_path,
       coalesce((SELECT max(v.version) FROM template_versions v
                 WHERE v.template_id = e.template_id AND v.published_at IS NOT NULL),
                e.template_version)::int AS latest_version
FROM events e
JOIN templates t ON t.id = e.template_id
JOIN template_versions tv ON tv.template_id = e.template_id AND tv.version = e.template_version
WHERE e.id = $1
  AND e.deleted_at IS NULL
  AND e.owner_id IS NULL
  AND EXISTS (SELECT 1 FROM anon_drafts a
              WHERE a.event_id = e.id AND a.cookie_hash = $2 AND a.expires_at > now())
`

type GetAnonDraftEventParams struct {
	EventID    uuid.UUID `json:"event_id"`
	CookieHash []byte    `json:"cookie_hash"`
}

type GetAnonDraftEventRow struct {
	Event         Event  `json:"event"`
	Role          string `json:"role"`
	TemplateSlug  string `json:"template_slug"`
	TemplateName  string `json:"template_name"`
	Manifest      []byte `json:"manifest"`
	AssetsPath    string `json:"assets_path"`
	LatestVersion int32  `json:"latest_version"`
}

// Same shape as GetEventForUser for an unclaimed draft owned by the draft cookie.
func (q *Queries) GetAnonDraftEvent(ctx context.Context, arg GetAnonDraftEventParams) (GetAnonDraftEventRow, error) {
	row := q.db.QueryRow(ctx, getAnonDraftEvent, arg.EventID, arg.CookieHash)
	var i GetAnonDraftEventRow
	err := row.Scan(
		&i.Event.ID,
		&i.Event.OwnerID,
		&i.Event.OccasionSlug,
		&i.Event.Slug,
		&i.Event.Title,
		&i.Event.Content,
		&i.Event.TemplateID,
		&i.Event.TemplateVersion,
		&i.Event.Overrides,
		&i.Event.Visibility,
		&i.Event.PasswordHash,
		&i.Event.RsvpMode,
		&i.Event.Status,
		&i.Event.RemoveBranding,
		&i.Event.StartsAt,
		&i.Event.PublishedAt,
		&i.Event.CreatedAt,
		&i.Event.UpdatedAt,
		&i.Event.DeletedAt,
		&i.Event.Version,
		&i.Event.NotifyRsvps,
		&i.Event.RsvpNotifiedAt,
		&i.Role,
		&i.TemplateSlug,
		&i.TemplateName,
		&i.Manifest,
		&i.AssetsPath,
		&i.LatestVersion,
	)
	return i, err
}

const getAnonDraftWriteState = `-- name: GetAnonDraftWriteState :one
SELECT e.version, e.status
FROM events e
WHERE e.id = $1
  AND e.deleted_at IS NULL
  AND e.owner_id IS NULL
  AND EXISTS (SELECT 1 FROM anon_drafts a
              WHERE a.event_id = e.id AND a.cookie_hash = $2 AND a.expires_at > now())
`

type GetAnonDraftWriteStateParams struct {
	EventID    uuid.UUID `json:"event_id"`
	CookieHash []byte    `json:"cookie_hash"`
}

type GetAnonDraftWriteStateRow struct {
	Version int32  `json:"version"`
	Status  string `json:"status"`
}

func (q *Queries) GetAnonDraftWriteState(ctx context.Context, arg GetAnonDraftWriteStateParams) (GetAnonDraftWriteStateRow, error) {
	row := q.db.QueryRow(ctx, getAnonDraftWriteState, arg.EventID, arg.CookieHash)
	var i GetAnonDraftWriteStateRow
	err := row.Scan(&i.Version, &i.Status)
	return i, err
}

const getEventAdmin = `-- name: GetEventAdmin :one
SELECT e.id, e.owner_id, e.occasion_slug, e.slug, e.title, e.content, e.template_id, e.template_version, e.overrides, e.visibility, e.password_hash, e.rsvp_mode, e.status, e.remove_branding, e.starts_at, e.published_at, e.created_at, e.updated_at, e.deleted_at, e.version, e.notify_rsvps, e.rsvp_notified_at,
       u.email AS owner_email,
       t.slug AS template_slug, t.name AS template_name, tv.manifest, tv.assets_path,
       (SELECT count(*) FROM rsvps r WHERE r.event_id = e.id) AS rsvp_count,
       (SELECT count(*) FROM guests g WHERE g.event_id = e.id) AS guest_count,
       (SELECT count(*) FROM media m WHERE m.event_id = e.id) AS media_count,
       (SELECT count(*) FROM reports p WHERE p.event_id = e.id AND p.status IN ('open', 'reviewing')) AS open_reports
FROM events e
LEFT JOIN users u ON u.id = e.owner_id
JOIN templates t ON t.id = e.template_id
JOIN template_versions tv ON tv.template_id = e.template_id AND tv.version = e.template_version
WHERE e.id = $1
`

type GetEventAdminRow struct {
	Event        Event   `json:"event"`
	OwnerEmail   *string `json:"owner_email"`
	TemplateSlug string  `json:"template_slug"`
	TemplateName string  `json:"template_name"`
	Manifest     []byte  `json:"manifest"`
	AssetsPath   string  `json:"assets_path"`
	RsvpCount    int64   `json:"rsvp_count"`
	GuestCount   int64   `json:"guest_count"`
	MediaCount   int64   `json:"media_count"`
	OpenReports  int64   `json:"open_reports"`
}

func (q *Queries) GetEventAdmin(ctx context.Context, eventID uuid.UUID) (GetEventAdminRow, error) {
	row := q.db.QueryRow(ctx, getEventAdmin, eventID)
	var i GetEventAdminRow
	err := row.Scan(
		&i.Event.ID,
		&i.Event.OwnerID,
		&i.Event.OccasionSlug,
		&i.Event.Slug,
		&i.Event.Title,
		&i.Event.Content,
		&i.Event.TemplateID,
		&i.Event.TemplateVersion,
		&i.Event.Overrides,
		&i.Event.Visibility,
		&i.Event.PasswordHash,
		&i.Event.RsvpMode,
		&i.Event.Status,
		&i.Event.RemoveBranding,
		&i.Event.StartsAt,
		&i.Event.PublishedAt,
		&i.Event.CreatedAt,
		&i.Event.UpdatedAt,
		&i.Event.DeletedAt,
		&i.Event.Version,
		&i.Event.NotifyRsvps,
		&i.Event.RsvpNotifiedAt,
		&i.OwnerEmail,
		&i.TemplateSlug,
		&i.TemplateName,
		&i.Manifest,
		&i.AssetsPath,
		&i.RsvpCount,
		&i.GuestCount,
		&i.MediaCount,
		&i.OpenReports,
	)
	return i, err
}

const getEventForNotify = `-- name: GetEventForNotify :one
SELECT e.id, e.slug, e.title, e.status, e.notify_rsvps, u.email AS owner_email, u.name AS owner_name
FROM events e
JOIN users u ON u.id = e.owner_id
WHERE e.id = $1 AND e.deleted_at IS NULL AND u.deleted_at IS NULL
`

type GetEventForNotifyRow struct {
	ID          uuid.UUID `json:"id"`
	Slug        *string   `json:"slug"`
	Title       string    `json:"title"`
	Status      string    `json:"status"`
	NotifyRsvps bool      `json:"notify_rsvps"`
	OwnerEmail  string    `json:"owner_email"`
	OwnerName   string    `json:"owner_name"`
}

func (q *Queries) GetEventForNotify(ctx context.Context, eventID uuid.UUID) (GetEventForNotifyRow, error) {
	row := q.db.QueryRow(ctx, getEventForNotify, eventID)
	var i GetEventForNotifyRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.NotifyRsvps,
		&i.OwnerEmail,
		&i.OwnerName,
	)
	return i, err
}

const getEventForUser = `-- name: GetEventForUser :one
SELECT e.id, e.owner_id, e.occasion_slug, e.slug, e.title, e.content, e.template_id, e.template_version, e.overrides, e.visibility, e.password_hash, e.rsvp_mode, e.status, e.remove_branding, e.starts_at, e.published_at, e.created_at, e.updated_at, e.deleted_at, e.version, e.notify_rsvps, e.rsvp_notified_at, r.role::text AS role,
       t.slug AS template_slug, t.name AS template_name,
       tv.manifest, tv.assets_path,
       coalesce((SELECT max(v.version) FROM template_versions v
                 WHERE v.template_id = e.template_id AND v.published_at IS NOT NULL),
                e.template_version)::int AS latest_version
FROM events e
CROSS JOIN LATERAL (SELECT event_role(e.id, $1::uuid) AS role) r
JOIN templates t ON t.id = e.template_id
JOIN template_versions tv ON tv.template_id = e.template_id AND tv.version = e.template_version
WHERE e.id = $2 AND e.deleted_at IS NULL AND r.role IS NOT NULL
`

type GetEventForUserParams struct {
	UserID  uuid.UUID `json:"user_id"`
	EventID uuid.UUID `json:"event_id"`
}

type GetEventForUserRow struct {
	Event         Event  `json:"event"`
	Role          string `json:"role"`
	TemplateSlug  string `json:"template_slug"`
	TemplateName  string `json:"template_name"`
	Manifest      []byte `json:"manifest"`
	AssetsPath    string `json:"assets_path"`
	LatestVersion int32  `json:"latest_version"`
}

// Host view for any member. role is 'owner', 'editor' or 'viewer'. Includes the pinned manifest
// and the template's latest published version (for the "upgrade available" hint).
func (q *Queries) GetEventForUser(ctx context.Context, arg GetEventForUserParams) (GetEventForUserRow, error) {
	row := q.db.QueryRow(ctx, getEventForUser, arg.UserID, arg.EventID)
	var i GetEventForUserRow
	err := row.Scan(
		&i.Event.ID,
		&i.Event.OwnerID,
		&i.Event.OccasionSlug,
		&i.Event.Slug,
		&i.Event.Title,
		&i.Event.Content,
		&i.Event.TemplateID,
		&i.Event.TemplateVersion,
		&i.Event.Overrides,
		&i.Event.Visibility,
		&i.Event.PasswordHash,
		&i.Event.RsvpMode,
		&i.Event.Status,
		&i.Event.RemoveBranding,
		&i.Event.StartsAt,
		&i.Event.PublishedAt,
		&i.Event.CreatedAt,
		&i.Event.UpdatedAt,
		&i.Event.DeletedAt,
		&i.Event.Version,
		&i.Event.NotifyRsvps,
		&i.Event.RsvpNotifiedAt,
		&i.Role,
		&i.TemplateSlug,
		&i.TemplateName,
		&i.Manifest,
		&i.AssetsPath,
		&i.LatestVersion,
	)
	return i, err
}

const getEventMediaState = `-- name: GetEventMediaState :one
SELECT id, status, deleted_at FROM events WHERE id = $1
`

type GetEventMediaStateRow struct {
	ID        uuid.UUID  `json:"id"`
	Status    string     `json:"status"`
	DeletedAt *time.Time `json:"deleted_at"`
}

// media_visibility job: decides where the event's files belong.
func (q *Queries) GetEventMediaState(ctx context.Context, eventID uuid.UUID) (GetEventMediaStateRow, error) {
	row := q.db.QueryRow(ctx, getEventMediaState, eventID)
	var i GetEventMediaStateRow
	err := row.Scan(&i.ID, &i.Status, &i.DeletedAt)
	return i, err
}

const getEventWriteState = `-- name: GetEventWriteState :one
SELECT r.role::text AS role, e.version, e.status
FROM events e
CROSS JOIN LATERAL (SELECT event_role(e.id, $1::uuid) AS role) r
WHERE e.id = $2 AND e.deleted_at IS NULL AND r.role IS NOT NULL
`

type GetEventWriteStateParams struct {
	UserID  uuid.UUID `json:"user_id"`
	EventID uuid.UUID `json:"event_id"`
}

type GetEventWriteStateRow struct {
	Role    string `json:"role"`
	Version int32  `json:"version"`
	Status  string `json:"status"`
}

// Only to map a zero-row update: no row → 404, viewer → 403, taken_down → 409, else version conflict.
func (q *Queries) GetEventWriteState(ctx context.Context, arg GetEventWriteStateParams) (GetEventWriteStateRow, error) {
	row := q.db.QueryRow(ctx, getEventWriteState, arg.UserID, arg.EventID)
	var i GetEventWriteStateRow
	err := row.Scan(&i.Role, &i.Version, &i.Status)
	return i, err
}

const getPublicEventBySlug = `-- name: GetPublicEventBySlug :one
SELECT e.id, e.slug, e.title, e.occasion_slug, e.content, e.overrides, e.visibility, e.password_hash,
       e.rsvp_mode, e.remove_branding, e.starts_at, e.template_id, e.template_version,
       tv.manifest, tv.assets_path,
       o.slug, o.name, o.default_blocks, o.optional_blocks, o.rsvp_fields, o.copy, o.setup_questions, o.sort_order, o.is_active, o.created_at, o.updated_at
FROM events e
JOIN template_versions tv ON tv.template_id = e.template_id AND tv.version = e.template_version
JOIN occasions o ON o.slug = e.occasion_slug
WHERE e.slug = $1 AND e.status = 'published' AND e.deleted_at IS NULL
`

type GetPublicEventBySlugRow struct {
	ID              uuid.UUID  `json:"id"`
	Slug            *string    `json:"slug"`
	Title           string     `json:"title"`
	OccasionSlug    string     `json:"occasion_slug"`
	Content         []byte     `json:"content"`
	Overrides       []byte     `json:"overrides"`
	Visibility      string     `json:"visibility"`
	PasswordHash    *string    `json:"password_hash"`
	RsvpMode        string     `json:"rsvp_mode"`
	RemoveBranding  bool       `json:"remove_branding"`
	StartsAt        *time.Time `json:"starts_at"`
	TemplateID      uuid.UUID  `json:"template_id"`
	TemplateVersion int32      `json:"template_version"`
	Manifest        []byte     `json:"manifest"`
	AssetsPath      string     `json:"assets_path"`
	Occasion        Occasion   `json:"occasion"`
}

// Public page. password_hash is only for the Go-side gate and must never be serialised.
func (q *Queries) GetPublicEventBySlug(ctx context.Context, slug *string) (GetPublicEventBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublicEventBySlug, slug)
	var i GetPublicEventBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.OccasionSlug,
		&i.Content,
		&i.Overrides,
		&i.Visibility,
		&i.PasswordHash,
		&i.RsvpMode,
		&i.RemoveBranding,
		&i.StartsAt,
		&i.TemplateID,
		&i.TemplateVersion,
		&i.Manifest,
		&i.AssetsPath,
		&i.Occasion.Slug,
		&i.Occasion.Name,
		&i.Occasion.DefaultBlocks,
		&i.Occasion.OptionalBlocks,
		&i.Occasion.RsvpFields,
		&i.Occasion.Copy,
		&i.Occasion.SetupQuestions,
		&i.Occasion.SortOrder,
		&i.Occasion.IsActive,
		&i.Occasion.CreatedAt,
		&i.Occasion.UpdatedAt,
	)
	return i, err
}

const listEventsForUser = `-- name: ListEventsForUser :many
SELECT x.id, x.slug, x.title, x.occasion_slug, x.status, x.starts_at, x.created_at, x.role
FROM (
    (SELECT e.id, e.slug, e.title, e.occasion_slug, e.status, e.starts_at, e.created_at, 'owner'::text AS role
     FROM events e
     WHERE e.owner_id = $1::uuid
       AND e.deleted_at IS NULL
       AND (e.created_at, e.id) < ($2::timestamptz, $3::uuid)
     ORDER BY e.created_at DESC, e.id DESC
     LIMIT $4::int)
    UNION ALL
    (SELECT e.id, e.slug, e.title, e.occasion_slug, e.status, e.starts_at, e.created_at, m.role
     FROM event_members m
     JOIN events e ON e.id = m.event_id
     WHERE m.user_id = $1::uuid
       AND e.deleted_at IS NULL
       AND (e.created_at, e.id) < ($2::timestamptz, $3::uuid)
     ORDER BY e.created_at DESC, e.id DESC
     LIMIT $4::int)
) x
ORDER BY x.created_at DESC, x.id DESC
LIMIT $4::int
`

type ListEventsForUserParams struct {
	UserID          uuid.UUID `json:"user_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	Lim             int32     `json:"lim"`
}

type ListEventsForUserRow struct {
	ID           uuid.UUID  `json:"id"`
	Slug         *string    `json:"slug"`
	Title        string     `json:"title"`
	OccasionSlug string     `json:"occasion_slug"`
	Status       string     `json:"status"`
	StartsAt     *time.Time `json:"starts_at"`
	CreatedAt    time.Time  `json:"created_at"`
	Role         string     `json:"role"`
}

// Owned and co-hosted events, newest first. Each branch is limited on its own index before the merge.
func (q *Queries) ListEventsForUser(ctx context.Context, arg ListEventsForUserParams) ([]ListEventsForUserRow, error) {
	rows, err := q.db.Query(ctx, listEventsForUser,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsForUserRow{}
	for rows.Next() {
		var i ListEventsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.OccasionSlug,
			&i.Status,
			&i.StartsAt,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAnonDraftEvent = `-- name: LockAnonDraftEvent :one
SELECT e.id
FROM events e
WHERE e.id = $1
  AND e.deleted_at IS NULL
  AND e.owner_id IS NULL
  AND EXISTS (SELECT 1 FROM anon_drafts a
              WHERE a.event_id = e.id AND a.cookie_hash = $2 AND a.expires_at > now())
FOR NO KEY UPDATE
`

type LockAnonDraftEventParams struct {
	EventID    uuid.UUID `json:"event_id"`
	CookieHash []byte    `json:"cookie_hash"`
}

// Serialises anonymous draft writes; confirms the cookie still owns a live (unclaimed, unexpired) draft.
func (q *Queries) LockAnonDraftEvent(ctx context.Context, arg LockAnonDraftEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockAnonDraftEvent, arg.EventID, arg.CookieHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const lockEventForEditor = `-- name: LockEventForEditor :one
SELECT e.id, e.slug, e.status, e.owner_id
FROM events e
WHERE e.id = $1
  AND e.deleted_at IS NULL
  AND event_role($1, $2::uuid) IN ('owner', 'editor')
FOR NO KEY UPDATE
`

type LockEventForEditorParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type LockEventForEditorRow struct {
	ID      uuid.UUID  `json:"id"`
	Slug    *string    `json:"slug"`
	Status  string     `json:"status"`
	OwnerID *uuid.UUID `json:"owner_id"`
}

// Serialises owner/editor writes with per-event caps (guests, media, members).
func (q *Queries) LockEventForEditor(ctx context.Context, arg LockEventForEditorParams) (LockEventForEditorRow, error) {
	row := q.db.QueryRow(ctx, lockEventForEditor, arg.EventID, arg.UserID)
	var i LockEventForEditorRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Status,
		&i.OwnerID,
	)
	return i, err
}

const lockEventForRSVP = `-- name: LockEventForRSVP :one
SELECT e.id, e.slug, e.title, e.occasion_slug, e.content, e.rsvp_mode, e.visibility, e.notify_rsvps, e.owner_id
FROM events e
WHERE e.id = $1 AND e.status = 'published' AND e.deleted_at IS NULL
FOR NO KEY UPDATE
`

type LockEventForRSVPRow struct {
	ID           uuid.UUID  `json:"id"`
	Slug         *string    `json:"slug"`
	Title        string     `json:"title"`
	OccasionSlug string     `json:"occasion_slug"`
	Content      []byte     `json:"content"`
	RsvpMode     string     `json:"rsvp_mode"`
	Visibility   string     `json:"visibility"`
	NotifyRsvps  bool       `json:"notify_rsvps"`
	OwnerID      *uuid.UUID `json:"owner_id"`
}

// First statement of an RSVP or guest-photo write: serialises capacity and quota checks per event.
// FOR NO KEY UPDATE does not block the FK checks of concurrent inserts into child tables.
func (q *Queries) LockEventForRSVP(ctx context.Context, eventID uuid.UUID) (LockEventForRSVPRow, error) {
	row := q.db.QueryRow(ctx, lockEventForRSVP, eventID)
	var i LockEventForRSVPRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.OccasionSlug,
		&i.Content,
		&i.RsvpMode,
		&i.Visibility,
		&i.NotifyRsvps,
		&i.OwnerID,
	)
	return i, err
}

const publishEvent = `-- name: PublishEvent :one
UPDATE events e
SET status = 'published',
    published_at = coalesce(e.published_at, now()),
    version = e.version + 1,
    updated_at = now()
WHERE e.id = $1
  AND e.owner_id = $2::uuid
  AND e.deleted_at IS NULL
  AND e.version = $3
  AND e.status IN ('draft', 'hidden')
  AND e.slug IS NOT NULL
RETURNING e.version, e.updated_at, e.published_at
`

type PublishEventParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
	Version int32     `json:"version"`
}

type PublishEventRow struct {
	Version     int32      `json:"version"`
	UpdatedAt   time.Time  `json:"updated_at"`
	PublishedAt *time.Time `json:"published_at"`
}

// published_at keeps the first publish time (it also locks the slug).
func (q *Queries) PublishEvent(ctx context.Context, arg PublishEventParams) (PublishEventRow, error) {
	row := q.db.QueryRow(ctx, publishEvent, arg.EventID, arg.UserID, arg.Version)
	var i PublishEventRow
	err := row.Scan(&i.Version, &i.UpdatedAt, &i.PublishedAt)
	return i, err
}

const purgeDeletedEvents = `-- name: PurgeDeletedEvents :execrows
DELETE FROM events
WHERE id IN (
    SELECT x.id FROM events x
    WHERE x.deleted_at < now() - interval '30 days' AND x.status <> 'taken_down'
    LIMIT 500
)
`

// Taken-down events are kept as moderation evidence.
func (q *Queries) PurgeDeletedEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeDeletedEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rSVPCountsForEvents = `-- name: RSVPCountsForEvents :many
WITH allowed AS (
    SELECT a.id FROM events a
    WHERE a.id = ANY($1::uuid[]) AND event_role(a.id, $2::uuid) IS NOT NULL
)
SELECT r.event_id,
       count(*) FILTER (WHERE r.attending = 'yes') AS yes,
       count(*) FILTER (WHERE r.attending = 'no') AS no,
       count(*) FILTER (WHERE r.attending = 'maybe') AS maybe,
       coalesce(sum(r.count) FILTER (WHERE r.attending = 'yes'), 0)::bigint AS yes_heads
FROM rsvps r
JOIN allowed ON allowed.id = r.event_id
GROUP BY r.event_id
`

type RSVPCountsForEventsParams struct {
	EventIds []uuid.UUID `json:"event_ids"`
	UserID   uuid.UUID   `json:"user_id"`
}

type RSVPCountsForEventsRow struct {
	EventID  uuid.UUID `json:"event_id"`
	Yes      int64     `json:"yes"`
	No       int64     `json:"no"`
	Maybe    int64     `json:"maybe"`
	YesHeads int64     `json:"yes_heads"`
}

// Dashboard counters for one page of events (ids from ListEventsForUser, at most 100).
// Access is checked once per event, not per RSVP row.
func (q *Queries) RSVPCountsForEvents(ctx context.Context, arg RSVPCountsForEventsParams) ([]RSVPCountsForEventsRow, error) {
	rows, err := q.db.Query(ctx, rSVPCountsForEvents, arg.EventIds, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RSVPCountsForEventsRow{}
	for rows.Next() {
		var i RSVPCountsForEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.Yes,
			&i.No,
			&i.Maybe,
			&i.YesHeads,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreEvent = `-- name: RestoreEvent :one
WITH prev AS (
    SELECT x.id, x.status FROM events x
    WHERE x.id = $1 AND x.deleted_at IS NULL AND x.status = 'taken_down'
    FOR NO KEY UPDATE
)
UPDATE events e
SET status = CASE WHEN e.published_at IS NOT NULL THEN 'published' ELSE 'draft' END,
    updated_at = now()
FROM prev
WHERE e.id = prev.id
RETURNING e.id, e.owner_id, prev.status AS old_status, e.status AS new_status
`

type RestoreEventRow struct {
	ID        uuid.UUID  `json:"id"`
	OwnerID   *uuid.UUID `json:"owner_id"`
	OldStatus string     `json:"old_status"`
	NewStatus string     `json:"new_status"`
}

// Back to 'published' if it had ever been published, else 'draft'.
func (q *Queries) RestoreEvent(ctx context.Context, eventID uuid.UUID) (RestoreEventRow, error) {
	row := q.db.QueryRow(ctx, restoreEvent, eventID)
	var i RestoreEventRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.OldStatus,
		&i.NewStatus,
	)
	return i, err
}

const searchEventsAdmin = `-- name: SearchEventsAdmin :many
SELECT e.id, e.slug, e.title, e.occasion_slug, e.status, e.created_at, e.published_at, e.deleted_at,
       e.owner_id, u.email AS owner_email
FROM events e
LEFT JOIN users u ON u.id = e.owner_id
WHERE (e.created_at, e.id) < ($1::timestamptz, $2::uuid)
ORDER BY e.created_at DESC, e.id DESC
LIMIT $3::int
`

type SearchEventsAdminParams struct {
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	Lim             int32     `json:"lim"`
}

type SearchEventsAdminRow struct {
	ID           uuid.UUID  `json:"id"`
	Slug         *string    `json:"slug"`
	Title        string     `json:"title"`
	OccasionSlug string     `json:"occasion_slug"`
	Status       string     `json:"status"`
	CreatedAt    time.Time  `json:"created_at"`
	PublishedAt  *time.Time `json:"published_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
	OwnerID      *uuid.UUID `json:"owner_id"`
	OwnerEmail   *string    `json:"owner_email"`
}

// Admin browse, newest first, deleted events included (events_admin_created_idx).
func (q *Queries) SearchEventsAdmin(ctx context.Context, arg SearchEventsAdminParams) ([]SearchEventsAdminRow, error) {
	rows, err := q.db.Query(ctx, searchEventsAdmin, arg.CursorCreatedAt, arg.CursorID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEventsAdminRow{}
	for rows.Next() {
		var i SearchEventsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.OccasionSlug,
			&i.Status,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.DeletedAt,
			&i.OwnerID,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEventsAdminByStatus = `-- name: SearchEventsAdminByStatus :many
SELECT e.id, e.slug, e.title, e.occasion_slug, e.status, e.created_at, e.published_at, e.deleted_at,
       e.owner_id, u.email AS owner_email
FROM events e
LEFT JOIN users u ON u.id = e.owner_id
WHERE e.status = $1::text
  AND (e.created_at, e.id) < ($2::timestamptz, $3::uuid)
ORDER BY e.created_at DESC, e.id DESC
LIMIT $4::int
`

type SearchEventsAdminByStatusParams struct {
	Status          string    `json:"status"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	Lim             int32     `json:"lim"`
}

type SearchEventsAdminByStatusRow struct {
	ID           uuid.UUID  `json:"id"`
	Slug         *string    `json:"slug"`
	Title        string     `json:"title"`
	OccasionSlug string     `json:"occasion_slug"`
	Status       string     `json:"status"`
	CreatedAt    time.Time  `json:"created_at"`
	PublishedAt  *time.Time `json:"published_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
	OwnerID      *uuid.UUID `json:"owner_id"`
	OwnerEmail   *string    `json:"owner_email"`
}

// As SearchEventsAdmin, one status only (events_admin_status_idx).
func (q *Queries) SearchEventsAdminByStatus(ctx context.Context, arg SearchEventsAdminByStatusParams) ([]SearchEventsAdminByStatusRow, error) {
	rows, err := q.db.Query(ctx, searchEventsAdminByStatus,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEventsAdminByStatusRow{}
	for rows.Next() {
		var i SearchEventsAdminByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.OccasionSlug,
			&i.Status,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.DeletedAt,
			&i.OwnerID,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEventsAdminText = `-- name: SearchEventsAdminText :many
SELECT e.id, e.slug, e.title, e.occasion_slug, e.status, e.created_at, e.published_at, e.deleted_at,
       e.owner_id, u.email AS owner_email
FROM events e
LEFT JOIN users u ON u.id = e.owner_id
WHERE to_tsvector('simple', coalesce(e.slug, '') || ' ' || e.title) @@ to_tsquery('simple', $1)
  AND ($2::text IS NULL OR e.status = $2::text)
  AND (e.created_at, e.id) < ($3::timestamptz, $4::uuid)
ORDER BY e.created_at DESC, e.id DESC
LIMIT $5::int
`

type SearchEventsAdminTextParams struct {
	PrefixQuery     string    `json:"prefix_query"`
	Status          *string   `json:"status"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	Lim             int32     `json:"lim"`
}

type SearchEventsAdminTextRow struct {
	ID           uuid.UUID  `json:"id"`
	Slug         *string    `json:"slug"`
	Title        string     `json:"title"`
	OccasionSlug string     `json:"occasion_slug"`
	Status       string     `json:"status"`
	CreatedAt    time.Time  `json:"created_at"`
	PublishedAt  *time.Time `json:"published_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
	OwnerID      *uuid.UUID `json:"owner_id"`
	OwnerEmail   *string    `json:"owner_email"`
}

// Prefix search over slug and title (events_search_idx); prefix_query built in Go as for users.
// status NULL = any.
func (q *Queries) SearchEventsAdminText(ctx context.Context, arg SearchEventsAdminTextParams) ([]SearchEventsAdminTextRow, error) {
	rows, err := q.db.Query(ctx, searchEventsAdminText,
		arg.PrefixQuery,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEventsAdminTextRow{}
	for rows.Next() {
		var i SearchEventsAdminTextRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.OccasionSlug,
			&i.Status,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.DeletedAt,
			&i.OwnerID,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEventFlags = `-- name: SetEventFlags :one
WITH prev AS (
    SELECT x.id, x.remove_branding, x.template_id, x.template_version, x.overrides FROM events x
    WHERE x.id = $5 AND x.deleted_at IS NULL
    FOR NO KEY UPDATE
)
UPDATE events e
SET remove_branding = coalesce($1, e.remove_branding),
    template_id = coalesce($2, e.template_id),
    template_version = coalesce($3, e.template_version),
    overrides = coalesce($4, e.overrides),
    version = CASE WHEN $2::uuid IS NULL THEN e.version ELSE e.version + 1 END,
    updated_at = now()
FROM prev
WHERE e.id = prev.id
RETURNING e.id,
          prev.remove_branding AS old_remove_branding, prev.template_id AS old_template_id,
          prev.template_version AS old_template_version, prev.overrides AS old_overrides,
          e.remove_branding, e.template_id, e.template_version, e.overrides, e.version
`

type SetEventFlagsParams struct {
	RemoveBranding  *bool      `json:"remove_branding"`
	TemplateID      *uuid.UUID `json:"template_id"`
	TemplateVersion *int32     `json:"template_version"`
	Overrides       []byte     `json:"overrides"`
	EventID         uuid.UUID  `json:"event_id"`
}

type SetEventFlagsRow struct {
	ID                 uuid.UUID `json:"id"`
	OldRemoveBranding  bool      `json:"old_remove_branding"`
	OldTemplateID      uuid.UUID `json:"old_template_id"`
	OldTemplateVersion int32     `json:"old_template_version"`
	OldOverrides       []byte    `json:"old_overrides"`
	RemoveBranding     bool      `json:"remove_branding"`
	TemplateID         uuid.UUID `json:"template_id"`
	TemplateVersion    int32     `json:"template_version"`
	Overrides          []byte    `json:"overrides"`
	Version            int32     `json:"version"`
}

// Super-admin flags. NULL leaves a field unchanged. A template change bumps version so an open
// editor reloads instead of saving over it.
func (q *Queries) SetEventFlags(ctx context.Context, arg SetEventFlagsParams) (SetEventFlagsRow, error) {
	row := q.db.QueryRow(ctx, setEventFlags,
		arg.RemoveBranding,
		arg.TemplateID,
		arg.TemplateVersion,
		arg.Overrides,
		arg.EventID,
	)
	var i SetEventFlagsRow
	err := row.Scan(
		&i.ID,
		&i.OldRemoveBranding,
		&i.OldTemplateID,
		&i.OldTemplateVersion,
		&i.OldOverrides,
		&i.RemoveBranding,
		&i.TemplateID,
		&i.TemplateVersion,
		&i.Overrides,
		&i.Version,
	)
	return i, err
}

const softDeleteAnonDraft = `-- name: SoftDeleteAnonDraft :one
UPDATE events e
SET deleted_at = now(), updated_at = now()
WHERE e.id = $1
  AND e.deleted_at IS NULL
  AND e.owner_id IS NULL
  AND EXISTS (SELECT 1 FROM anon_drafts a
              WHERE a.event_id = e.id AND a.cookie_hash = $2 AND a.expires_at > now())
RETURNING e.id
`

type SoftDeleteAnonDraftParams struct {
	EventID    uuid.UUID `json:"event_id"`
	CookieHash []byte    `json:"cookie_hash"`
}

func (q *Queries) SoftDeleteAnonDraft(ctx context.Context, arg SoftDeleteAnonDraftParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteAnonDraft, arg.EventID, arg.CookieHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const softDeleteEvent = `-- name: SoftDeleteEvent :one
UPDATE events
SET deleted_at = now(), updated_at = now(),
    slug = CASE WHEN published_at IS NULL AND status = 'draft' THEN NULL ELSE slug END
WHERE id = $1 AND owner_id = $2::uuid AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteEventParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

// The slug stays reserved until the purge, so a deleted page's URL can't be taken over at once.
// A never-published draft never showed its slug publicly, so its slug is released immediately
// instead of squatting on it until the purge job runs (events CHECK requires published/taken-down
// events to keep a non-null slug, so this only ever applies to drafts).
func (q *Queries) SoftDeleteEvent(ctx context.Context, arg SoftDeleteEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteEvent, arg.EventID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const softDeleteEventsByOwner = `-- name: SoftDeleteEventsByOwner :many
UPDATE events
SET deleted_at = now(), updated_at = now(),
    slug = CASE WHEN published_at IS NULL AND status = 'draft' THEN NULL ELSE slug END
WHERE owner_id = $1::uuid AND deleted_at IS NULL
RETURNING id
`

// Account deletion. Bounded by the per-user live-event cap. Never-published drafts release their
// slug immediately (see SoftDeleteEvent); published/taken-down events keep theirs reserved.
func (q *Queries) SoftDeleteEventsByOwner(ctx context.Context, ownerID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, softDeleteEventsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const takeDownEvent = `-- name: TakeDownEvent :one
WITH prev AS (
    SELECT x.id, x.status FROM events x
    WHERE x.id = $1 AND x.deleted_at IS NULL AND x.status <> 'taken_down' AND x.slug IS NOT NULL
    FOR NO KEY UPDATE
)
UPDATE events e
SET status = 'taken_down', updated_at = now()
FROM prev
WHERE e.id = prev.id
RETURNING e.id, e.owner_id, prev.status AS old_status, e.status AS new_status
`

type TakeDownEventRow struct {
	ID        uuid.UUID  `json:"id"`
	OwnerID   *uuid.UUID `json:"owner_id"`
	OldStatus string     `json:"old_status"`
	NewStatus string     `json:"new_status"`
}

// No row: missing, deleted, already taken down, or a slug-less draft (never public).
func (q *Queries) TakeDownEvent(ctx context.Context, eventID uuid.UUID) (TakeDownEventRow, error) {
	row := q.db.QueryRow(ctx, takeDownEvent, eventID)
	var i TakeDownEventRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.OldStatus,
		&i.NewStatus,
	)
	return i, err
}

const takeDownEventsByOwner = `-- name: TakeDownEventsByOwner :many
UPDATE events
SET status = 'taken_down', updated_at = now()
WHERE owner_id = $1::uuid
  AND deleted_at IS NULL
  AND status <> 'taken_down'
  AND slug IS NOT NULL
RETURNING id
`

// Ban. Drafts without a slug were never public and can't be taken down (events CHECK), so they are skipped.
func (q *Queries) TakeDownEventsByOwner(ctx context.Context, ownerID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, takeDownEventsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unpublishEvent = `-- name: UnpublishEvent :one
UPDATE events e
SET status = 'hidden', version = e.version + 1, updated_at = now()
WHERE e.id = $1
  AND e.owner_id = $2::uuid
  AND e.deleted_at IS NULL
  AND e.version = $3
  AND e.status = 'published'
RETURNING e.version, e.updated_at
`

type UnpublishEventParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
	Version int32     `json:"version"`
}

type UnpublishEventRow struct {
	Version   int32     `json:"version"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UnpublishEvent(ctx context.Context, arg UnpublishEventParams) (UnpublishEventRow, error) {
	row := q.db.QueryRow(ctx, unpublishEvent, arg.EventID, arg.UserID, arg.Version)
	var i UnpublishEventRow
	err := row.Scan(&i.Version, &i.UpdatedAt)
	return i, err
}

const updateAnonDraftContent = `-- name: UpdateAnonDraftContent :one
UPDATE events e
SET content = coalesce($1, e.content),
    title = CASE WHEN $1::jsonb IS NULL THEN e.title ELSE $2::text END,
    starts_at = CASE WHEN $1::jsonb IS NULL THEN e.starts_at ELSE $3::timestamptz END,
    overrides = coalesce($4, e.overrides),
    template_id = coalesce($5, e.template_id),
    template_version = coalesce($6, e.template_version),
    version = e.version + 1,
    updated_at = now()
WHERE e.id = $7
  AND e.deleted_at IS NULL
  AND e.version = $8
  AND e.owner_id IS NULL
  AND EXISTS (SELECT 1 FROM anon_drafts a
              WHERE a.event_id = e.id AND a.cookie_hash = $9 AND a.expires_at > now())
  AND (($5::uuid IS NULL AND $6::int IS NULL)
       OR EXISTS (SELECT 1 FROM templates t
                  JOIN template_versions tv ON tv.template_id = t.id
                  WHERE t.id = coalesce($5::uuid, e.template_id)
                    AND tv.version = coalesce($6::int, e.template_version)
                    AND tv.published_at IS NOT NULL
                    AND t.status = 'published'
                    AND NOT t.is_premium))
RETURNING e.version, e.updated_at
`

type UpdateAnonDraftContentParams struct {
	Content         []byte     `json:"content"`
	Title           string     `json:"title"`
	StartsAt        *time.Time `json:"starts_at"`
	Overrides       []byte     `json:"overrides"`
	TemplateID      *uuid.UUID `json:"template_id"`
	TemplateVersion *int32     `json:"template_version"`
	EventID         uuid.UUID  `json:"event_id"`
	Version         int32      `json:"version"`
	CookieHash      []byte     `json:"cookie_hash"`
}

type UpdateAnonDraftContentRow struct {
	Version   int32     `json:"version"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Same template-pin rule as UpdateEventContent.
func (q *Queries) UpdateAnonDraftContent(ctx context.Context, arg UpdateAnonDraftContentParams) (UpdateAnonDraftContentRow, error) {
	row := q.db.QueryRow(ctx, updateAnonDraftContent,
		arg.Content,
		arg.Title,
		arg.StartsAt,
		arg.Overrides,
		arg.TemplateID,
		arg.TemplateVersion,
		arg.EventID,
		arg.Version,
		arg.CookieHash,
	)
	var i UpdateAnonDraftContentRow
	err := row.Scan(&i.Version, &i.UpdatedAt)
	return i, err
}

const updateEventContent = `-- name: UpdateEventContent :one
UPDATE events e
SET content = coalesce($1, e.content),
    title = CASE WHEN $1::jsonb IS NULL THEN e.title ELSE $2::text END,
    starts_at = CASE WHEN $1::jsonb IS NULL THEN e.starts_at ELSE $3::timestamptz END,
    overrides = coalesce($4, e.overrides),
    template_id = coalesce($5, e.template_id),
    template_version = coalesce($6, e.template_version),
    version = e.version + 1,
    updated_at = now()
WHERE e.id = $7
  AND e.deleted_at IS NULL
  AND e.version = $8
  AND e.status <> 'taken_down'
  AND event_role($7, $9::uuid) IN ('owner', 'editor')
  AND (($5::uuid IS NULL AND $6::int IS NULL)
       OR EXISTS (SELECT 1 FROM templates t
                  JOIN template_versions tv ON tv.template_id = t.id
                  WHERE t.id = coalesce($5::uuid, e.template_id)
                    AND tv.version = coalesce($6::int, e.template_version)
                    AND tv.published_at IS NOT NULL
                    AND t.status = 'published'
                    AND NOT t.is_premium))
RETURNING e.version, e.updated_at
`

type UpdateEventContentParams struct {
	Content         []byte     `json:"content"`
	Title           string     `json:"title"`
	StartsAt        *time.Time `json:"starts_at"`
	Overrides       []byte     `json:"overrides"`
	TemplateID      *uuid.UUID `json:"template_id"`
	TemplateVersion *int32     `json:"template_version"`
	EventID         uuid.UUID  `json:"event_id"`
	Version         int32      `json:"version"`
	UserID          uuid.UUID  `json:"user_id"`
}

type UpdateEventContentRow struct {
	Version   int32     `json:"version"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Editor save for owners and editors. NULL content/overrides/template leave that part unchanged;
// title and starts_at are derived from content and only change with it. A template change must
// resolve (with the unchanged half) to a selectable pin; leaving both NULL keeps an existing pin even
// if that template has since become premium or retired. An unselectable pin updates no row.
func (q *Queries) UpdateEventContent(ctx context.Context, arg UpdateEventContentParams) (UpdateEventContentRow, error) {
	row := q.db.QueryRow(ctx, updateEventContent,
		arg.Content,
		arg.Title,
		arg.StartsAt,
		arg.Overrides,
		arg.TemplateID,
		arg.TemplateVersion,
		arg.EventID,
		arg.Version,
		arg.UserID,
	)
	var i UpdateEventContentRow
	err := row.Scan(&i.Version, &i.UpdatedAt)
	return i, err
}

const updateEventSettings = `-- name: UpdateEventSettings :one
UPDATE events e
SET slug = coalesce($1, e.slug),
    visibility = coalesce($2, e.visibility),
    password_hash = CASE
        WHEN coalesce($2::text, e.visibility) <> 'password' THEN NULL
        ELSE coalesce($3::text, e.password_hash)
    END,
    rsvp_mode = coalesce($4, e.rsvp_mode),
    notify_rsvps = coalesce($5, e.notify_rsvps),
    version = e.version + 1,
    updated_at = now()
WHERE e.id = $6
  AND e.owner_id = $7::uuid
  AND e.deleted_at IS NULL
  AND e.version = $8
  AND e.status <> 'taken_down'
RETURNING e.version, e.updated_at
`

type UpdateEventSettingsParams struct {
	Slug         *string   `json:"slug"`
	Visibility   *string   `json:"visibility"`
	PasswordHash *string   `json:"password_hash"`
	RsvpMode     *string   `json:"rsvp_mode"`
	NotifyRsvps  *bool     `json:"notify_rsvps"`
	EventID      uuid.UUID `json:"event_id"`
	UserID       uuid.UUID `json:"user_id"`
	Version      int32     `json:"version"`
}

type UpdateEventSettingsRow struct {
	Version   int32     `json:"version"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Owner only. NULL leaves a field unchanged. The password hash is kept only while visibility is
// 'password' (the CHECKs require that); a new hash replaces the old one. Changing the slug of a
// published event raises check_violation on constraint events_slug_immutable.
func (q *Queries) UpdateEventSettings(ctx context.Context, arg UpdateEventSettingsParams) (UpdateEventSettingsRow, error) {
	row := q.db.QueryRow(ctx, updateEventSettings,
		arg.Slug,
		arg.Visibility,
		arg.PasswordHash,
		arg.RsvpMode,
		arg.NotifyRsvps,
		arg.EventID,
		arg.UserID,
		arg.Version,
	)
	var i UpdateEventSettingsRow
	err := row.Scan(&i.Version, &i.UpdatedAt)
	return i, err
}
