// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guests.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countGuests = `-- name: CountGuests :one
SELECT count(*) FROM guests WHERE event_id = $1
`

func (q *Queries) CountGuests(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGuests, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuest = `-- name: CreateGuest :one
INSERT INTO guests (id, event_id, name, email, phone, household_size)
SELECT $1::uuid, $2::uuid, $3::text, $4::text, $5::text, $6::int
WHERE event_role($2::uuid, $7::uuid) IN ('owner', 'editor')
RETURNING id, name, email, phone, household_size, token_version, invited_at, created_at
`

type CreateGuestParams struct {
	ID            uuid.UUID `json:"id"`
	EventID       uuid.UUID `json:"event_id"`
	Name          string    `json:"name"`
	Email         *string   `json:"email"`
	Phone         *string   `json:"phone"`
	HouseholdSize int32     `json:"household_size"`
	UserID        uuid.UUID `json:"user_id"`
}

type CreateGuestRow struct {
	ID            uuid.UUID  `json:"id"`
	Name          string     `json:"name"`
	Email         *string    `json:"email"`
	Phone         *string    `json:"phone"`
	HouseholdSize int32      `json:"household_size"`
	TokenVersion  int32      `json:"token_version"`
	InvitedAt     *time.Time `json:"invited_at"`
	CreatedAt     time.Time  `json:"created_at"`
}

// Owner or editor. A duplicate email raises 23505 on guests_event_email_key (guest_exists).
func (q *Queries) CreateGuest(ctx context.Context, arg CreateGuestParams) (CreateGuestRow, error) {
	row := q.db.QueryRow(ctx, createGuest,
		arg.ID,
		arg.EventID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.HouseholdSize,
		arg.UserID,
	)
	var i CreateGuestRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.HouseholdSize,
		&i.TokenVersion,
		&i.InvitedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGuest = `-- name: DeleteGuest :execrows
DELETE FROM guests g
WHERE g.id = $1::uuid
  AND g.event_id = $2::uuid
  AND event_role($2::uuid, $3::uuid) IN ('owner', 'editor')
`

type DeleteGuestParams struct {
	GuestID uuid.UUID `json:"guest_id"`
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

// Their RSVP cascades; their photos keep the row with guest_id NULL.
func (q *Queries) DeleteGuest(ctx context.Context, arg DeleteGuestParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGuest, arg.GuestID, arg.EventID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGuestForInviteEmail = `-- name: GetGuestForInviteEmail :one
SELECT g.id, g.name, g.email, g.token_version,
       e.id AS event_id, e.slug AS event_slug, e.title AS event_title, e.status AS event_status,
       e.starts_at AS event_starts_at, u.name AS owner_name
FROM guests g
JOIN events e ON e.id = g.event_id
LEFT JOIN users u ON u.id = e.owner_id AND u.deleted_at IS NULL
WHERE g.id = $1 AND e.deleted_at IS NULL
`

type GetGuestForInviteEmailRow struct {
	ID            uuid.UUID  `json:"id"`
	Name          string     `json:"name"`
	Email         *string    `json:"email"`
	TokenVersion  int32      `json:"token_version"`
	EventID       uuid.UUID  `json:"event_id"`
	EventSlug     *string    `json:"event_slug"`
	EventTitle    string     `json:"event_title"`
	EventStatus   string     `json:"event_status"`
	EventStartsAt *time.Time `json:"event_starts_at"`
	OwnerName     *string    `json:"owner_name"`
}

// send_invite job. The job no-ops unless the event is published and the guest still has an email.
func (q *Queries) GetGuestForInviteEmail(ctx context.Context, guestID uuid.UUID) (GetGuestForInviteEmailRow, error) {
	row := q.db.QueryRow(ctx, getGuestForInviteEmail, guestID)
	var i GetGuestForInviteEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.TokenVersion,
		&i.EventID,
		&i.EventSlug,
		&i.EventTitle,
		&i.EventStatus,
		&i.EventStartsAt,
		&i.OwnerName,
	)
	return i, err
}

const getGuestForToken = `-- name: GetGuestForToken :one
SELECT g.id, g.event_id, g.name, g.household_size, g.token_version, e.slug AS event_slug, e.status AS event_status
FROM guests g
JOIN events e ON e.id = g.event_id
WHERE g.id = $1 AND e.deleted_at IS NULL
`

type GetGuestForTokenRow struct {
	ID            uuid.UUID `json:"id"`
	EventID       uuid.UUID `json:"event_id"`
	Name          string    `json:"name"`
	HouseholdSize int32     `json:"household_size"`
	TokenVersion  int32     `json:"token_version"`
	EventSlug     *string   `json:"event_slug"`
	EventStatus   string    `json:"event_status"`
}

// Public; the caller has already verified the token MAC against token_version.
func (q *Queries) GetGuestForToken(ctx context.Context, guestID uuid.UUID) (GetGuestForTokenRow, error) {
	row := q.db.QueryRow(ctx, getGuestForToken, guestID)
	var i GetGuestForTokenRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.HouseholdSize,
		&i.TokenVersion,
		&i.EventSlug,
		&i.EventStatus,
	)
	return i, err
}

const insertGuestsBatch = `-- name: InsertGuestsBatch :many
INSERT INTO guests (id, event_id, name, email, phone, household_size)
SELECT b.id, $1::uuid, b.name, nullif(b.email, ''), nullif(b.phone, ''), b.household_size
FROM (SELECT unnest($2::uuid[]) AS id, unnest($3::text[]) AS name, unnest($4::text[]) AS email,
             unnest($5::text[]) AS phone, unnest($6::int[]) AS household_size) b
WHERE event_role($1::uuid, $7::uuid) IN ('owner', 'editor')
ON CONFLICT (event_id, email) WHERE email IS NOT NULL DO NOTHING
RETURNING id
`

type InsertGuestsBatchParams struct {
	EventID        uuid.UUID   `json:"event_id"`
	Ids            []uuid.UUID `json:"ids"`
	Names          []string    `json:"names"`
	Emails         []string    `json:"emails"`
	Phones         []string    `json:"phones"`
	HouseholdSizes []int32     `json:"household_sizes"`
	UserID         uuid.UUID   `json:"user_id"`
}

// CSV import, after LockEventForEditor in the same tx. Arrays are parallel; an empty string in
// emails/phones means none. Rows whose email is already invited (or repeated in the batch) are
// skipped; the returned ids are the inserted rows.
func (q *Queries) InsertGuestsBatch(ctx context.Context, arg InsertGuestsBatchParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, insertGuestsBatch,
		arg.EventID,
		arg.Ids,
		arg.Names,
		arg.Emails,
		arg.Phones,
		arg.HouseholdSizes,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuests = `-- name: ListGuests :many
SELECT g.id, g.name, g.email, g.phone, g.household_size, g.token_version, g.invited_at, g.created_at,
       r.attending AS rsvp_attending, r.count AS rsvp_count, r.updated_at AS rsvp_updated_at
FROM (
    SELECT x.id, x.event_id, x.name, x.email, x.phone, x.household_size, x.token_version, x.invited_at, x.created_at
    FROM guests x
    WHERE x.event_id = $1::uuid
      AND event_role($1::uuid, $2::uuid) IS NOT NULL
      AND ($3::text IS NULL
           OR x.name ILIKE $3::text
           OR x.email ILIKE $3::text)
      AND (x.created_at, x.id) > ($4::timestamptz, $5::uuid)
    ORDER BY x.created_at, x.id
    LIMIT $6::int
) g
LEFT JOIN rsvps r ON r.event_id = g.event_id AND r.guest_id = g.id
ORDER BY g.created_at, g.id
`

type ListGuestsParams struct {
	EventID         uuid.UUID `json:"event_id"`
	UserID          uuid.UUID `json:"user_id"`
	Pattern         *string   `json:"pattern"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	Lim             int32     `json:"lim"`
}

type ListGuestsRow struct {
	ID            uuid.UUID  `json:"id"`
	Name          string     `json:"name"`
	Email         *string    `json:"email"`
	Phone         *string    `json:"phone"`
	HouseholdSize int32      `json:"household_size"`
	TokenVersion  int32      `json:"token_version"`
	InvitedAt     *time.Time `json:"invited_at"`
	CreatedAt     time.Time  `json:"created_at"`
	RsvpAttending *string    `json:"rsvp_attending"`
	RsvpCount     *int32     `json:"rsvp_count"`
	RsvpUpdatedAt *time.Time `json:"rsvp_updated_at"`
}

// Any member. Oldest first (the order hosts entered them). pattern is NULL or an ILIKE pattern
// built in Go with %, _ and \ escaped, e.g. '%ann%'. The RSVP join is at most one row per guest
// (rsvps_event_guest_key).
// The page is cut before the join so only its rows are joined.
func (q *Queries) ListGuests(ctx context.Context, arg ListGuestsParams) ([]ListGuestsRow, error) {
	rows, err := q.db.Query(ctx, listGuests,
		arg.EventID,
		arg.UserID,
		arg.Pattern,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuestsRow{}
	for rows.Next() {
		var i ListGuestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.HouseholdSize,
			&i.TokenVersion,
			&i.InvitedAt,
			&i.CreatedAt,
			&i.RsvpAttending,
			&i.RsvpCount,
			&i.RsvpUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGuestsInvited = `-- name: MarkGuestsInvited :many
UPDATE guests g
SET invited_at = now(), updated_at = now()
WHERE g.id IN (
        SELECT x.id FROM guests x
        WHERE x.event_id = $1::uuid
          AND x.email IS NOT NULL
          AND ((x.id = ANY($2::uuid[])
                AND (x.invited_at IS NULL OR x.invited_at < now() - interval '24 hours'))
               OR ($3::bool AND x.invited_at IS NULL))
        ORDER BY x.created_at, x.id
        LIMIT 500)
  AND event_role($1::uuid, $4::uuid) IN ('owner', 'editor')
RETURNING g.id
`

type MarkGuestsInvitedParams struct {
	EventID      uuid.UUID   `json:"event_id"`
	GuestIds     []uuid.UUID `json:"guest_ids"`
	AllUninvited bool        `json:"all_uninvited"`
	UserID       uuid.UUID   `json:"user_id"`
}

// Owner or editor. Stamps up to 500 guests with an email, either the given ids or every guest not
// yet invited; the caller enqueues one send_invite job per returned id in the same tx. Explicit ids
// are re-sent at most once per 24 hours, so repeated calls can't be used to spam an inbox.
func (q *Queries) MarkGuestsInvited(ctx context.Context, arg MarkGuestsInvitedParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, markGuestsInvited,
		arg.EventID,
		arg.GuestIds,
		arg.AllUninvited,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateGuestToken = `-- name: RotateGuestToken :one
UPDATE guests g
SET token_version = g.token_version + 1, updated_at = now()
WHERE g.id = $1::uuid
  AND g.event_id = $2::uuid
  AND event_role($2::uuid, $3::uuid) IN ('owner', 'editor')
RETURNING g.id, g.name, g.email, g.phone, g.household_size, g.token_version, g.invited_at, g.created_at
`

type RotateGuestTokenParams struct {
	GuestID uuid.UUID `json:"guest_id"`
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type RotateGuestTokenRow struct {
	ID            uuid.UUID  `json:"id"`
	Name          string     `json:"name"`
	Email         *string    `json:"email"`
	Phone         *string    `json:"phone"`
	HouseholdSize int32      `json:"household_size"`
	TokenVersion  int32      `json:"token_version"`
	InvitedAt     *time.Time `json:"invited_at"`
	CreatedAt     time.Time  `json:"created_at"`
}

// Invalidates the guest's current invite link.
func (q *Queries) RotateGuestToken(ctx context.Context, arg RotateGuestTokenParams) (RotateGuestTokenRow, error) {
	row := q.db.QueryRow(ctx, rotateGuestToken, arg.GuestID, arg.EventID, arg.UserID)
	var i RotateGuestTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.HouseholdSize,
		&i.TokenVersion,
		&i.InvitedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateGuest = `-- name: UpdateGuest :one
UPDATE guests g
SET name = coalesce($1::text, g.name),
    household_size = coalesce($2::int, g.household_size),
    email = CASE WHEN $3::bool THEN $4::text ELSE g.email END,
    phone = CASE WHEN $5::bool THEN $6::text ELSE g.phone END,
    updated_at = now()
WHERE g.id = $7::uuid
  AND g.event_id = $8::uuid
  AND event_role($8::uuid, $9::uuid) IN ('owner', 'editor')
RETURNING g.id, g.name, g.email, g.phone, g.household_size, g.token_version, g.invited_at, g.created_at
`

type UpdateGuestParams struct {
	Name          *string   `json:"name"`
	HouseholdSize *int32    `json:"household_size"`
	SetEmail      bool      `json:"set_email"`
	Email         *string   `json:"email"`
	SetPhone      bool      `json:"set_phone"`
	Phone         *string   `json:"phone"`
	GuestID       uuid.UUID `json:"guest_id"`
	EventID       uuid.UUID `json:"event_id"`
	UserID        uuid.UUID `json:"user_id"`
}

type UpdateGuestRow struct {
	ID            uuid.UUID  `json:"id"`
	Name          string     `json:"name"`
	Email         *string    `json:"email"`
	Phone         *string    `json:"phone"`
	HouseholdSize int32      `json:"household_size"`
	TokenVersion  int32      `json:"token_version"`
	InvitedAt     *time.Time `json:"invited_at"`
	CreatedAt     time.Time  `json:"created_at"`
}

// Owner or editor. NULL name/household_size leave them unchanged; email and phone change only when
// their set_ flag is true (so they can be cleared with NULL).
func (q *Queries) UpdateGuest(ctx context.Context, arg UpdateGuestParams) (UpdateGuestRow, error) {
	row := q.db.QueryRow(ctx, updateGuest,
		arg.Name,
		arg.HouseholdSize,
		arg.SetEmail,
		arg.Email,
		arg.SetPhone,
		arg.Phone,
		arg.GuestID,
		arg.EventID,
		arg.UserID,
	)
	var i UpdateGuestRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.HouseholdSize,
		&i.TokenVersion,
		&i.InvitedAt,
		&i.CreatedAt,
	)
	return i, err
}
