// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const approvedMediaByIDs = `-- name: ApprovedMediaByIDs :many
SELECT id, width, height
FROM media
WHERE event_id = $1 AND id = ANY($2::uuid[]) AND moderation_status = 'approved'
`

type ApprovedMediaByIDsParams struct {
	EventID  uuid.UUID   `json:"event_id"`
	MediaIds []uuid.UUID `json:"media_ids"`
}

type ApprovedMediaByIDsRow struct {
	ID     uuid.UUID `json:"id"`
	Width  int32     `json:"width"`
	Height int32     `json:"height"`
}

// Content save: which referenced media exist, belong to this event and are approved.
func (q *Queries) ApprovedMediaByIDs(ctx context.Context, arg ApprovedMediaByIDsParams) ([]ApprovedMediaByIDsRow, error) {
	rows, err := q.db.Query(ctx, approvedMediaByIDs, arg.EventID, arg.MediaIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovedMediaByIDsRow{}
	for rows.Next() {
		var i ApprovedMediaByIDsRow
		if err := rows.Scan(&i.ID, &i.Width, &i.Height); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAnonDraftMedia = `-- name: CreateAnonDraftMedia :one
INSERT INTO media (id, owner_id, event_id, storage_key, content_type, size_bytes, width, height, uploaded_by, moderation_status)
SELECT $1::uuid, NULL, e.id, $2::text, 'image/jpeg',
       $3::bigint, $4::int, $5::int, 'host', 'approved'
FROM events e
WHERE e.id = $6::uuid
  AND e.deleted_at IS NULL
  AND e.owner_id IS NULL
  AND EXISTS (SELECT 1 FROM anon_drafts a
              WHERE a.event_id = e.id AND a.cookie_hash = $7 AND a.expires_at > now())
RETURNING id, event_id, width, height, size_bytes, uploaded_by, moderation_status, created_at
`

type CreateAnonDraftMediaParams struct {
	ID         uuid.UUID `json:"id"`
	StorageKey string    `json:"storage_key"`
	SizeBytes  int64     `json:"size_bytes"`
	Width      int32     `json:"width"`
	Height     int32     `json:"height"`
	EventID    uuid.UUID `json:"event_id"`
	CookieHash []byte    `json:"cookie_hash"`
}

type CreateAnonDraftMediaRow struct {
	ID               uuid.UUID `json:"id"`
	EventID          uuid.UUID `json:"event_id"`
	Width            int32     `json:"width"`
	Height           int32     `json:"height"`
	SizeBytes        int64     `json:"size_bytes"`
	UploadedBy       string    `json:"uploaded_by"`
	ModerationStatus string    `json:"moderation_status"`
	CreatedAt        time.Time `json:"created_at"`
}

// Unclaimed draft owned by the draft cookie; owner_id is filled in when the draft is claimed.
func (q *Queries) CreateAnonDraftMedia(ctx context.Context, arg CreateAnonDraftMediaParams) (CreateAnonDraftMediaRow, error) {
	row := q.db.QueryRow(ctx, createAnonDraftMedia,
		arg.ID,
		arg.StorageKey,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.EventID,
		arg.CookieHash,
	)
	var i CreateAnonDraftMediaRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.ModerationStatus,
		&i.CreatedAt,
	)
	return i, err
}

const createGuestMedia = `-- name: CreateGuestMedia :one
INSERT INTO media (id, owner_id, event_id, storage_key, content_type, size_bytes, width, height, uploaded_by, guest_id, moderation_status)
SELECT $1::uuid, NULL, e.id, $2::text, 'image/jpeg',
       $3::bigint, $4::int, $5::int, 'guest', $6::uuid, 'pending'
FROM events e
WHERE e.id = $7::uuid AND e.status = 'published' AND e.deleted_at IS NULL
RETURNING id, moderation_status
`

type CreateGuestMediaParams struct {
	ID         uuid.UUID  `json:"id"`
	StorageKey string     `json:"storage_key"`
	SizeBytes  int64      `json:"size_bytes"`
	Width      int32      `json:"width"`
	Height     int32      `json:"height"`
	GuestID    *uuid.UUID `json:"guest_id"`
	EventID    uuid.UUID  `json:"event_id"`
}

type CreateGuestMediaRow struct {
	ID               uuid.UUID `json:"id"`
	ModerationStatus string    `json:"moderation_status"`
}

// After LockEventForRSVP and the photo-limit check in the same tx. Starts pending moderation.
func (q *Queries) CreateGuestMedia(ctx context.Context, arg CreateGuestMediaParams) (CreateGuestMediaRow, error) {
	row := q.db.QueryRow(ctx, createGuestMedia,
		arg.ID,
		arg.StorageKey,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.GuestID,
		arg.EventID,
	)
	var i CreateGuestMediaRow
	err := row.Scan(&i.ID, &i.ModerationStatus)
	return i, err
}

const createHostMedia = `-- name: CreateHostMedia :one

INSERT INTO media (id, owner_id, event_id, storage_key, content_type, size_bytes, width, height, uploaded_by, moderation_status)
SELECT $1::uuid, $2::uuid, $3::uuid, $4::text, 'image/jpeg',
       $5::bigint, $6::int, $7::int, 'host', 'approved'
WHERE event_role($3::uuid, $2::uuid) IN ('owner', 'editor')
RETURNING id, event_id, width, height, size_bytes, uploaded_by, moderation_status, created_at
`

type CreateHostMediaParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	EventID    uuid.UUID `json:"event_id"`
	StorageKey string    `json:"storage_key"`
	SizeBytes  int64     `json:"size_bytes"`
	Width      int32     `json:"width"`
	Height     int32     `json:"height"`
}

type CreateHostMediaRow struct {
	ID               uuid.UUID `json:"id"`
	EventID          uuid.UUID `json:"event_id"`
	Width            int32     `json:"width"`
	Height           int32     `json:"height"`
	SizeBytes        int64     `json:"size_bytes"`
	UploadedBy       string    `json:"uploaded_by"`
	ModerationStatus string    `json:"moderation_status"`
	CreatedAt        time.Time `json:"created_at"`
}

// Files are written before the row (see internal/media) and deleted before the row on every delete
// path except detached-media cleanup, which is row-first on purpose: DeleteDetachedMedia re-checks
// detached_at atomically, and files of a row that was re-attached meanwhile must not be removed.
// Orphaned files left by a failed step are swept by media reconcile.
// Owner or editor, after LockEventForEditor and the quota check in the same tx.
func (q *Queries) CreateHostMedia(ctx context.Context, arg CreateHostMediaParams) (CreateHostMediaRow, error) {
	row := q.db.QueryRow(ctx, createHostMedia,
		arg.ID,
		arg.UserID,
		arg.EventID,
		arg.StorageKey,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
	)
	var i CreateHostMediaRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.ModerationStatus,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDetachedMedia = `-- name: DeleteDetachedMedia :many
DELETE FROM media
WHERE id IN (
    SELECT x.id FROM media x
    WHERE x.detached_at < now() - interval '7 days'
    LIMIT 500)
  AND detached_at < now() - interval '7 days'
RETURNING event_id, id
`

type DeleteDetachedMediaRow struct {
	EventID uuid.UUID `json:"event_id"`
	ID      uuid.UUID `json:"id"`
}

// Cleanup: host media detached for 7+ days, in batches. The outer predicate is re-checked on
// locked rows, so media re-attached concurrently is kept.
func (q *Queries) DeleteDetachedMedia(ctx context.Context) ([]DeleteDetachedMediaRow, error) {
	rows, err := q.db.Query(ctx, deleteDetachedMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeleteDetachedMediaRow{}
	for rows.Next() {
		var i DeleteDetachedMediaRow
		if err := rows.Scan(&i.EventID, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEventMedia = `-- name: DeleteEventMedia :one
DELETE FROM media m
WHERE m.id = $1::uuid
  AND m.event_id = $2::uuid
  AND event_role($2::uuid, $3::uuid) IN ('owner', 'editor')
RETURNING m.id, m.uploaded_by, m.moderation_status
`

type DeleteEventMediaParams struct {
	MediaID uuid.UUID `json:"media_id"`
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type DeleteEventMediaRow struct {
	ID               uuid.UUID `json:"id"`
	UploadedBy       string    `json:"uploaded_by"`
	ModerationStatus string    `json:"moderation_status"`
}

// Owner or editor. The caller has already checked the media isn't referenced by content.
func (q *Queries) DeleteEventMedia(ctx context.Context, arg DeleteEventMediaParams) (DeleteEventMediaRow, error) {
	row := q.db.QueryRow(ctx, deleteEventMedia, arg.MediaID, arg.EventID, arg.UserID)
	var i DeleteEventMediaRow
	err := row.Scan(&i.ID, &i.UploadedBy, &i.ModerationStatus)
	return i, err
}

const deleteRejectedMedia = `-- name: DeleteRejectedMedia :execrows
DELETE FROM media
WHERE id IN (
    SELECT x.id FROM media x
    WHERE x.moderation_status = 'rejected' AND x.created_at < now() - interval '7 days'
    LIMIT 500)
`

// Cleanup: rejected rows (files already deleted) older than 7 days, in batches.
func (q *Queries) DeleteRejectedMedia(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRejectedMedia)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEventMedia = `-- name: GetEventMedia :one
SELECT m.id, m.event_id, m.width, m.height, m.size_bytes, m.uploaded_by, m.moderation_status, m.created_at,
       g.name AS guest_name
FROM media m
LEFT JOIN guests g ON g.id = m.guest_id
WHERE m.id = $1::uuid
  AND m.event_id = $2::uuid
  AND event_role($2::uuid, $3::uuid) IS NOT NULL
`

type GetEventMediaParams struct {
	MediaID uuid.UUID `json:"media_id"`
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type GetEventMediaRow struct {
	ID               uuid.UUID `json:"id"`
	EventID          uuid.UUID `json:"event_id"`
	Width            int32     `json:"width"`
	Height           int32     `json:"height"`
	SizeBytes        int64     `json:"size_bytes"`
	UploadedBy       string    `json:"uploaded_by"`
	ModerationStatus string    `json:"moderation_status"`
	CreatedAt        time.Time `json:"created_at"`
	GuestName        *string   `json:"guest_name"`
}

// Any member.
func (q *Queries) GetEventMedia(ctx context.Context, arg GetEventMediaParams) (GetEventMediaRow, error) {
	row := q.db.QueryRow(ctx, getEventMedia, arg.MediaID, arg.EventID, arg.UserID)
	var i GetEventMediaRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.ModerationStatus,
		&i.CreatedAt,
		&i.GuestName,
	)
	return i, err
}

const getMediaAdmin = `-- name: GetMediaAdmin :one
SELECT m.id, m.event_id, m.width, m.height, m.size_bytes, m.uploaded_by, m.moderation_status, m.created_at,
       e.status AS event_status, e.deleted_at AS event_deleted_at
FROM media m
JOIN events e ON e.id = m.event_id
WHERE m.id = $1
`

type GetMediaAdminRow struct {
	ID               uuid.UUID  `json:"id"`
	EventID          uuid.UUID  `json:"event_id"`
	Width            int32      `json:"width"`
	Height           int32      `json:"height"`
	SizeBytes        int64      `json:"size_bytes"`
	UploadedBy       string     `json:"uploaded_by"`
	ModerationStatus string     `json:"moderation_status"`
	CreatedAt        time.Time  `json:"created_at"`
	EventStatus      string     `json:"event_status"`
	EventDeletedAt   *time.Time `json:"event_deleted_at"`
}

func (q *Queries) GetMediaAdmin(ctx context.Context, mediaID uuid.UUID) (GetMediaAdminRow, error) {
	row := q.db.QueryRow(ctx, getMediaAdmin, mediaID)
	var i GetMediaAdminRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.ModerationStatus,
		&i.CreatedAt,
		&i.EventStatus,
		&i.EventDeletedAt,
	)
	return i, err
}

const getServableMedia = `-- name: GetServableMedia :one
SELECT m.id
FROM media m
JOIN events e ON e.id = m.event_id
WHERE m.id = $1
  AND m.event_id = $2
  AND m.moderation_status = 'approved'
  AND e.deleted_at IS NULL
  AND e.status <> 'taken_down'
`

type GetServableMediaParams struct {
	MediaID uuid.UUID `json:"media_id"`
	EventID uuid.UUID `json:"event_id"`
}

// Public /media serving gate: approved media of an event that is neither soft-deleted nor taken
// down. No row = not servable, whatever the reason (the caller answers every case with the same 404).
func (q *Queries) GetServableMedia(ctx context.Context, arg GetServableMediaParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getServableMedia, arg.MediaID, arg.EventID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listApprovedGuestPhotos = `-- name: ListApprovedGuestPhotos :many
SELECT id, width, height, created_at
FROM media
WHERE event_id = $1
  AND uploaded_by = 'guest'
  AND moderation_status = 'approved'
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type ListApprovedGuestPhotosParams struct {
	EventID         uuid.UUID `json:"event_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	Lim             int32     `json:"lim"`
}

type ListApprovedGuestPhotosRow struct {
	ID        uuid.UUID `json:"id"`
	Width     int32     `json:"width"`
	Height    int32     `json:"height"`
	CreatedAt time.Time `json:"created_at"`
}

// Public photo wall, newest first (media_event_approved_guest_idx).
func (q *Queries) ListApprovedGuestPhotos(ctx context.Context, arg ListApprovedGuestPhotosParams) ([]ListApprovedGuestPhotosRow, error) {
	rows, err := q.db.Query(ctx, listApprovedGuestPhotos,
		arg.EventID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovedGuestPhotosRow{}
	for rows.Next() {
		var i ListApprovedGuestPhotosRow
		if err := rows.Scan(
			&i.ID,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventMedia = `-- name: ListEventMedia :many
SELECT m.id, m.width, m.height, m.size_bytes, m.uploaded_by, m.moderation_status, m.created_at,
       g.name AS guest_name
FROM (
    SELECT x.id, x.guest_id, x.width, x.height, x.size_bytes, x.uploaded_by, x.moderation_status, x.created_at
    FROM media x
    WHERE x.event_id = $1::uuid
      AND event_role($1::uuid, $2::uuid) IS NOT NULL
      AND ($3::text IS NULL OR x.uploaded_by = $3::text)
      AND ($4::text IS NULL OR x.moderation_status = $4::text)
      AND (x.created_at, x.id) < ($5::timestamptz, $6::uuid)
    ORDER BY x.created_at DESC, x.id DESC
    LIMIT $7::int
) m
LEFT JOIN guests g ON g.id = m.guest_id
ORDER BY m.created_at DESC, m.id DESC
`

type ListEventMediaParams struct {
	EventID         uuid.UUID `json:"event_id"`
	UserID          uuid.UUID `json:"user_id"`
	UploadedBy      *string   `json:"uploaded_by"`
	Status          *string   `json:"status"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	Lim             int32     `json:"lim"`
}

type ListEventMediaRow struct {
	ID               uuid.UUID `json:"id"`
	Width            int32     `json:"width"`
	Height           int32     `json:"height"`
	SizeBytes        int64     `json:"size_bytes"`
	UploadedBy       string    `json:"uploaded_by"`
	ModerationStatus string    `json:"moderation_status"`
	CreatedAt        time.Time `json:"created_at"`
	GuestName        *string   `json:"guest_name"`
}

// Any member. Newest first; uploaded_by / status NULL = all. The page is cut before the guest join.
func (q *Queries) ListEventMedia(ctx context.Context, arg ListEventMediaParams) ([]ListEventMediaRow, error) {
	rows, err := q.db.Query(ctx, listEventMedia,
		arg.EventID,
		arg.UserID,
		arg.UploadedBy,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventMediaRow{}
	for rows.Next() {
		var i ListEventMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.UploadedBy,
			&i.ModerationStatus,
			&i.CreatedAt,
			&i.GuestName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuestMediaAdmin = `-- name: ListGuestMediaAdmin :many
SELECT m.id, m.event_id, m.width, m.height, m.size_bytes, m.moderation_status, m.created_at,
       e.slug AS event_slug, e.title AS event_title, g.name AS guest_name
FROM media m
JOIN events e ON e.id = m.event_id
LEFT JOIN guests g ON g.id = m.guest_id
WHERE m.uploaded_by = 'guest'
  AND m.moderation_status = $1::text
  AND ($2::uuid IS NULL OR m.event_id = $2::uuid)
  AND (m.created_at, m.id) < ($3::timestamptz, $4::uuid)
ORDER BY m.created_at DESC, m.id DESC
LIMIT $5::int
`

type ListGuestMediaAdminParams struct {
	Status          string     `json:"status"`
	EventID         *uuid.UUID `json:"event_id"`
	CursorCreatedAt time.Time  `json:"cursor_created_at"`
	CursorID        uuid.UUID  `json:"cursor_id"`
	Lim             int32      `json:"lim"`
}

type ListGuestMediaAdminRow struct {
	ID               uuid.UUID `json:"id"`
	EventID          uuid.UUID `json:"event_id"`
	Width            int32     `json:"width"`
	Height           int32     `json:"height"`
	SizeBytes        int64     `json:"size_bytes"`
	ModerationStatus string    `json:"moderation_status"`
	CreatedAt        time.Time `json:"created_at"`
	EventSlug        *string   `json:"event_slug"`
	EventTitle       string    `json:"event_title"`
	GuestName        *string   `json:"guest_name"`
}

// Moderation queue: guest uploads with one status, newest first (media_guest_status_created_idx).
// event_id NULL = all events.
func (q *Queries) ListGuestMediaAdmin(ctx context.Context, arg ListGuestMediaAdminParams) ([]ListGuestMediaAdminRow, error) {
	rows, err := q.db.Query(ctx, listGuestMediaAdmin,
		arg.Status,
		arg.EventID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuestMediaAdminRow{}
	for rows.Next() {
		var i ListGuestMediaAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.ModerationStatus,
			&i.CreatedAt,
			&i.EventSlug,
			&i.EventTitle,
			&i.GuestName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRejectedMediaIDsByEvent = `-- name: ListRejectedMediaIDsByEvent :many
SELECT id
FROM media
WHERE event_id = $1::uuid AND moderation_status = 'rejected'
`

// MediaVisibilityWorker: rejected media of one event, whose files must be gone. Unpaginated: an
// event has at most ~2,150 media rows (per-event caps) and media_event_created_idx covers the lookup.
func (q *Queries) ListRejectedMediaIDsByEvent(ctx context.Context, eventID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listRejectedMediaIDsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveMediaIDs = `-- name: LiveMediaIDs :many
SELECT id
FROM media
WHERE id = ANY($1::uuid[]) AND moderation_status <> 'rejected'
`

// Reconcile: which of these media ids still have a non-rejected row; files of any other id are
// orphans. Callers pass at most one listing page (1000 ids).
func (q *Queries) LiveMediaIDs(ctx context.Context, ids []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, liveMediaIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMediaStorageQuota = `-- name: LockMediaStorageQuota :exec
SELECT pg_advisory_xact_lock(hashtextextended('syt:media_storage_quota', 0))
`

// Serialises the quota check and insert across upload transactions. Take it last, after the event
// row lock, so lock order is always event -> quota and cannot deadlock.
func (q *Queries) LockMediaStorageQuota(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockMediaStorageQuota)
	return err
}

const mediaOwnerUsage = `-- name: MediaOwnerUsage :one
SELECT coalesce(sum(m.size_bytes), 0)::bigint AS owner_bytes
FROM media m JOIN events e ON e.id = m.event_id
WHERE e.owner_id = $1::uuid
  AND e.deleted_at IS NULL
  AND m.moderation_status <> 'rejected'
  AND NOT (m.uploaded_by = 'guest' AND m.moderation_status = 'pending')
`

// Approval check (run after LockMediaStorageQuota): same owner_bytes rule as MediaStorageUsage,
// without the global sum, so the global lock is not held across a bucket-wide scan.
func (q *Queries) MediaOwnerUsage(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, mediaOwnerUsage, ownerID)
	var owner_bytes int64
	err := row.Scan(&owner_bytes)
	return owner_bytes, err
}

const mediaStorageUsage = `-- name: MediaStorageUsage :one
SELECT (SELECT coalesce(sum(m.size_bytes), 0)
        FROM media m JOIN events e ON e.id = m.event_id
        WHERE e.owner_id = $1::uuid
          AND e.deleted_at IS NULL
          AND m.moderation_status <> 'rejected'
          AND NOT (m.uploaded_by = 'guest' AND m.moderation_status = 'pending'))::bigint AS owner_bytes,
       (SELECT coalesce(sum(size_bytes), 0)
        FROM media
        WHERE moderation_status <> 'rejected')::bigint AS total_bytes,
       (SELECT coalesce(sum(size_bytes), 0)
        FROM media
        WHERE event_id = $2::uuid
          AND uploaded_by = 'guest'
          AND moderation_status = 'pending')::bigint AS pending_guest_bytes,
       (SELECT coalesce(sum(m.size_bytes), 0)
        FROM media m JOIN events e ON e.id = m.event_id
        WHERE e.owner_id = $1::uuid
          AND e.deleted_at IS NULL
          AND m.uploaded_by = 'guest'
          AND m.moderation_status = 'pending')::bigint AS owner_pending_guest_bytes
`

type MediaStorageUsageParams struct {
	OwnerID *uuid.UUID `json:"owner_id"`
	EventID *uuid.UUID `json:"event_id"`
}

type MediaStorageUsageRow struct {
	OwnerBytes             int64 `json:"owner_bytes"`
	TotalBytes             int64 `json:"total_bytes"`
	PendingGuestBytes      int64 `json:"pending_guest_bytes"`
	OwnerPendingGuestBytes int64 `json:"owner_pending_guest_bytes"`
}

// Upload quota (run after LockMediaStorageQuota). owner_bytes: live events of one owner, rejected
// rows and pending guest photos excluded (soft-deleted events free the owner's quota at once; a
// guest photo is charged to the owner only once the host approves it). total_bytes: every event,
// soft-deleted ones included until purge, pending guest photos too, because their files still
// occupy the bucket. pending_guest_bytes: pending guest photos of one event, bounded separately.
// owner_pending_guest_bytes: pending guest photos across all live events of one owner, bounded
// by a per-owner allowance so many events cannot each park a full per-event allowance.
// NULL owner (anonymous draft): owner_bytes and owner_pending_guest_bytes are 0 and the caller
// skips the per-user checks. NULL event: pending_guest_bytes is 0.
func (q *Queries) MediaStorageUsage(ctx context.Context, arg MediaStorageUsageParams) (MediaStorageUsageRow, error) {
	row := q.db.QueryRow(ctx, mediaStorageUsage, arg.OwnerID, arg.EventID)
	var i MediaStorageUsageRow
	err := row.Scan(
		&i.OwnerBytes,
		&i.TotalBytes,
		&i.PendingGuestBytes,
		&i.OwnerPendingGuestBytes,
	)
	return i, err
}

const mediaUsage = `-- name: MediaUsage :one
SELECT count(*) AS files, coalesce(sum(size_bytes), 0)::bigint AS bytes
FROM media
WHERE event_id = $1 AND uploaded_by = $2 AND moderation_status <> 'rejected'
`

type MediaUsageParams struct {
	EventID    uuid.UUID `json:"event_id"`
	UploadedBy string    `json:"uploaded_by"`
}

type MediaUsageRow struct {
	Files int64 `json:"files"`
	Bytes int64 `json:"bytes"`
}

// Quota check (files and bytes) per event and uploader kind; rejected rows don't count.
func (q *Queries) MediaUsage(ctx context.Context, arg MediaUsageParams) (MediaUsageRow, error) {
	row := q.db.QueryRow(ctx, mediaUsage, arg.EventID, arg.UploadedBy)
	var i MediaUsageRow
	err := row.Scan(&i.Files, &i.Bytes)
	return i, err
}

const rejectMediaAdmin = `-- name: RejectMediaAdmin :one
WITH prev AS (
    SELECT x.id, x.moderation_status FROM media x
    WHERE x.id = $1 AND x.moderation_status <> 'rejected'
    FOR UPDATE
)
UPDATE media m
SET moderation_status = 'rejected'
FROM prev
WHERE m.id = prev.id
RETURNING m.id, m.event_id, m.uploaded_by, prev.moderation_status AS old_status, m.moderation_status AS new_status
`

type RejectMediaAdminRow struct {
	ID         uuid.UUID `json:"id"`
	EventID    uuid.UUID `json:"event_id"`
	UploadedBy string    `json:"uploaded_by"`
	OldStatus  string    `json:"old_status"`
	NewStatus  string    `json:"new_status"`
}

// Returns the previous status for the audit row. No row: missing or already rejected.
func (q *Queries) RejectMediaAdmin(ctx context.Context, mediaID uuid.UUID) (RejectMediaAdminRow, error) {
	row := q.db.QueryRow(ctx, rejectMediaAdmin, mediaID)
	var i RejectMediaAdminRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UploadedBy,
		&i.OldStatus,
		&i.NewStatus,
	)
	return i, err
}

const setGuestMediaModeration = `-- name: SetGuestMediaModeration :one
WITH prev AS (
    SELECT x.id, x.moderation_status FROM media x
    WHERE x.id = $2::uuid
      AND x.event_id = $3::uuid
      AND x.uploaded_by = 'guest'
      AND event_role($3::uuid, $4::uuid) IN ('owner', 'editor')
      AND (($1::text = 'approved' AND x.moderation_status = 'pending')
           OR ($1::text = 'rejected' AND x.moderation_status <> 'rejected'))
      AND EXISTS (SELECT 1 FROM events e WHERE e.id = $3::uuid AND e.status <> 'taken_down')
    FOR UPDATE
)
UPDATE media m
SET moderation_status = $1::text
FROM prev
WHERE m.id = prev.id
RETURNING m.id, m.event_id, m.width, m.height, m.size_bytes, m.uploaded_by, m.moderation_status, m.created_at,
          prev.moderation_status AS old_status
`

type SetGuestMediaModerationParams struct {
	Status  string    `json:"status"`
	MediaID uuid.UUID `json:"media_id"`
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type SetGuestMediaModerationRow struct {
	ID               uuid.UUID `json:"id"`
	EventID          uuid.UUID `json:"event_id"`
	Width            int32     `json:"width"`
	Height           int32     `json:"height"`
	SizeBytes        int64     `json:"size_bytes"`
	UploadedBy       string    `json:"uploaded_by"`
	ModerationStatus string    `json:"moderation_status"`
	CreatedAt        time.Time `json:"created_at"`
	OldStatus        string    `json:"old_status"`
}

// Owner or editor approves/rejects a guest photo; returns the previous status so the caller knows
// whether files need deleting. Approve only from pending; reject blocked only when already
// rejected (its files are already deleted, so re-rejecting would re-issue a delete for files that
// don't exist). Either transition is blocked once the event is taken down.
func (q *Queries) SetGuestMediaModeration(ctx context.Context, arg SetGuestMediaModerationParams) (SetGuestMediaModerationRow, error) {
	row := q.db.QueryRow(ctx, setGuestMediaModeration,
		arg.Status,
		arg.MediaID,
		arg.EventID,
		arg.UserID,
	)
	var i SetGuestMediaModerationRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.ModerationStatus,
		&i.CreatedAt,
		&i.OldStatus,
	)
	return i, err
}

const syncMediaDetached = `-- name: SyncMediaDetached :exec
UPDATE media
SET detached_at = CASE WHEN id = ANY($1::uuid[]) THEN NULL ELSE now() END
WHERE event_id = $2
  AND uploaded_by = 'host'
  AND (id = ANY($1::uuid[])) = (detached_at IS NOT NULL)
`

type SyncMediaDetachedParams struct {
	Referenced []uuid.UUID `json:"referenced"`
	EventID    uuid.UUID   `json:"event_id"`
}

// After a content save: referenced host media are attached, the rest get a detached_at (kept if
// already set). Only rows whose state actually changes are written.
func (q *Queries) SyncMediaDetached(ctx context.Context, arg SyncMediaDetachedParams) error {
	_, err := q.db.Exec(ctx, syncMediaDetached, arg.Referenced, arg.EventID)
	return err
}
