// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countEventMembers = `-- name: CountEventMembers :one
SELECT count(*) FROM event_members WHERE event_id = $1
`

func (q *Queries) CountEventMembers(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEventMembers, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEventMember = `-- name: DeleteEventMember :execrows
DELETE FROM event_members m
WHERE m.event_id = $1::uuid
  AND m.user_id = $2::uuid
  AND (m.user_id = $3::uuid
       OR EXISTS (SELECT 1 FROM events e
                  WHERE e.id = $1::uuid AND e.owner_id = $3::uuid AND e.deleted_at IS NULL))
`

type DeleteEventMemberParams struct {
	EventID  uuid.UUID `json:"event_id"`
	MemberID uuid.UUID `json:"member_id"`
	UserID   uuid.UUID `json:"user_id"`
}

// The owner removes anyone; a member may remove themself (leave).
func (q *Queries) DeleteEventMember(ctx context.Context, arg DeleteEventMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEventMember, arg.EventID, arg.MemberID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMembershipsByUser = `-- name: DeleteMembershipsByUser :exec
DELETE FROM event_members WHERE user_id = $1
`

func (q *Queries) DeleteMembershipsByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMembershipsByUser, userID)
	return err
}

const getCohostNotification = `-- name: GetCohostNotification :one
SELECT u.email, e.title AS event_title
FROM event_members m
JOIN users u ON u.id = m.user_id AND u.deleted_at IS NULL
JOIN events e ON e.id = m.event_id AND e.deleted_at IS NULL
WHERE m.event_id = $1::uuid AND m.user_id = $2::uuid
`

type GetCohostNotificationParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type GetCohostNotificationRow struct {
	Email      string `json:"email"`
	EventTitle string `json:"event_title"`
}

// notify_cohost_added job. A missing row (membership removed, user deleted,
// or the event gone before the job runs) is treated by the worker as done,
// not an error.
func (q *Queries) GetCohostNotification(ctx context.Context, arg GetCohostNotificationParams) (GetCohostNotificationRow, error) {
	row := q.db.QueryRow(ctx, getCohostNotification, arg.EventID, arg.UserID)
	var i GetCohostNotificationRow
	err := row.Scan(&i.Email, &i.EventTitle)
	return i, err
}

const listEventMembers = `-- name: ListEventMembers :many
SELECT x.user_id, x.email, x.name, x.role
FROM (
    SELECT u.id AS user_id, u.email, u.name, 'owner'::text AS role, 0 AS ord, e.created_at
    FROM events e
    JOIN users u ON u.id = e.owner_id
    WHERE e.id = $1::uuid AND e.deleted_at IS NULL
    UNION ALL
    SELECT u.id, u.email, u.name, m.role, 1, m.created_at
    FROM event_members m
    JOIN users u ON u.id = m.user_id
    WHERE m.event_id = $1::uuid
) x
WHERE event_role($1::uuid, $2::uuid) IS NOT NULL
ORDER BY x.ord, x.created_at
LIMIT 11
`

type ListEventMembersParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type ListEventMembersRow struct {
	UserID uuid.UUID `json:"user_id"`
	Email  string    `json:"email"`
	Name   string    `json:"name"`
	Role   string    `json:"role"`
}

// Visible to any member. Owner first, then co-hosts by join time; at most 1 owner + 10 members.
func (q *Queries) ListEventMembers(ctx context.Context, arg ListEventMembersParams) ([]ListEventMembersRow, error) {
	rows, err := q.db.Query(ctx, listEventMembers, arg.EventID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventMembersRow{}
	for rows.Next() {
		var i ListEventMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Name,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventMemberRole = `-- name: UpdateEventMemberRole :execrows
UPDATE event_members m
SET role = $1
WHERE m.event_id = $2::uuid
  AND m.user_id = $3::uuid
  AND EXISTS (SELECT 1 FROM events e
              WHERE e.id = $2::uuid AND e.owner_id = $4::uuid AND e.deleted_at IS NULL)
`

type UpdateEventMemberRoleParams struct {
	Role     string    `json:"role"`
	EventID  uuid.UUID `json:"event_id"`
	MemberID uuid.UUID `json:"member_id"`
	OwnerID  uuid.UUID `json:"owner_id"`
}

func (q *Queries) UpdateEventMemberRole(ctx context.Context, arg UpdateEventMemberRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventMemberRole,
		arg.Role,
		arg.EventID,
		arg.MemberID,
		arg.OwnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertEventMember = `-- name: UpsertEventMember :one
INSERT INTO event_members (event_id, user_id, role)
SELECT e.id, $1::uuid, $2::text
FROM events e
WHERE e.id = $3::uuid
  AND e.owner_id = $4::uuid
  AND e.deleted_at IS NULL
  AND e.owner_id <> $1::uuid
ON CONFLICT (event_id, user_id) DO UPDATE SET role = EXCLUDED.role
RETURNING (xmax = 0) AS inserted
`

type UpsertEventMemberParams struct {
	MemberID uuid.UUID `json:"member_id"`
	Role     string    `json:"role"`
	EventID  uuid.UUID `json:"event_id"`
	OwnerID  uuid.UUID `json:"owner_id"`
}

// Owner only; the owner can't be added as a member of their own event. No row: not the owner,
// event gone, or member_id is the owner (pgx.ErrNoRows at the call site). inserted is false for a
// re-add or role change of an existing member, so the caller only notifies on a fresh add.
func (q *Queries) UpsertEventMember(ctx context.Context, arg UpsertEventMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertEventMember,
		arg.MemberID,
		arg.Role,
		arg.EventID,
		arg.OwnerID,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}
