// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type AnonDraft struct {
	ID         uuid.UUID `json:"id"`
	CookieHash []byte    `json:"cookie_hash"`
	EventID    uuid.UUID `json:"event_id"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedAt  time.Time `json:"created_at"`
}

type AuditLog struct {
	ID         uuid.UUID   `json:"id"`
	ActorID    *uuid.UUID  `json:"actor_id"`
	Action     string      `json:"action"`
	TargetType string      `json:"target_type"`
	TargetID   string      `json:"target_id"`
	Before     []byte      `json:"before"`
	After      []byte      `json:"after"`
	Ip         *netip.Addr `json:"ip"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Event struct {
	ID              uuid.UUID  `json:"id"`
	OwnerID         *uuid.UUID `json:"owner_id"`
	OccasionSlug    string     `json:"occasion_slug"`
	Slug            *string    `json:"slug"`
	Title           string     `json:"title"`
	Content         []byte     `json:"content"`
	TemplateID      uuid.UUID  `json:"template_id"`
	TemplateVersion int32      `json:"template_version"`
	Overrides       []byte     `json:"overrides"`
	Visibility      string     `json:"visibility"`
	PasswordHash    *string    `json:"password_hash"`
	RsvpMode        string     `json:"rsvp_mode"`
	Status          string     `json:"status"`
	RemoveBranding  bool       `json:"remove_branding"`
	StartsAt        *time.Time `json:"starts_at"`
	PublishedAt     *time.Time `json:"published_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
	Version         int32      `json:"version"`
	NotifyRsvps     bool       `json:"notify_rsvps"`
	RsvpNotifiedAt  *time.Time `json:"rsvp_notified_at"`
	// Effective end: the datetime block end, else its start. NULL exactly when starts_at is NULL.
	EndsAt *time.Time `json:"ends_at"`
	// Retention anchor: greatest(ends_at, now()) when ends_at was set or last changed. NULL exactly when ends_at is NULL.
	RetentionFrom           *time.Time `json:"retention_from"`
	RetentionRemindedAt     *time.Time `json:"retention_reminded_at"`
	RetentionReminderSentAt *time.Time `json:"retention_reminder_sent_at"`
}

type EventMember struct {
	EventID   uuid.UUID `json:"event_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type Guest struct {
	ID            uuid.UUID  `json:"id"`
	EventID       uuid.UUID  `json:"event_id"`
	Name          string     `json:"name"`
	Email         *string    `json:"email"`
	Phone         *string    `json:"phone"`
	HouseholdSize int32      `json:"household_size"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	TokenVersion  int32      `json:"token_version"`
	InvitedAt     *time.Time `json:"invited_at"`
}

type Medium struct {
	ID               uuid.UUID  `json:"id"`
	OwnerID          *uuid.UUID `json:"owner_id"`
	EventID          uuid.UUID  `json:"event_id"`
	StorageKey       string     `json:"storage_key"`
	ContentType      string     `json:"content_type"`
	SizeBytes        int64      `json:"size_bytes"`
	Width            int32      `json:"width"`
	Height           int32      `json:"height"`
	UploadedBy       string     `json:"uploaded_by"`
	GuestID          *uuid.UUID `json:"guest_id"`
	ModerationStatus string     `json:"moderation_status"`
	CreatedAt        time.Time  `json:"created_at"`
	DetachedAt       *time.Time `json:"detached_at"`
}

type Occasion struct {
	Slug           string    `json:"slug"`
	Name           string    `json:"name"`
	DefaultBlocks  []byte    `json:"default_blocks"`
	OptionalBlocks []byte    `json:"optional_blocks"`
	RsvpFields     []byte    `json:"rsvp_fields"`
	Copy           []byte    `json:"copy"`
	SetupQuestions []byte    `json:"setup_questions"`
	SortOrder      int32     `json:"sort_order"`
	IsActive       bool      `json:"is_active"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Report struct {
	ID             uuid.UUID  `json:"id"`
	EventID        uuid.UUID  `json:"event_id"`
	ReporterIpHash []byte     `json:"reporter_ip_hash"`
	Reason         string     `json:"reason"`
	Details        string     `json:"details"`
	Status         string     `json:"status"`
	HandledBy      *uuid.UUID `json:"handled_by"`
	HandledAt      *time.Time `json:"handled_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

type Rsvp struct {
	ID               uuid.UUID  `json:"id"`
	EventID          uuid.UUID  `json:"event_id"`
	GuestID          *uuid.UUID `json:"guest_id"`
	Name             string     `json:"name"`
	Email            *string    `json:"email"`
	Attending        string     `json:"attending"`
	Count            int32      `json:"count"`
	Answers          []byte     `json:"answers"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	EditTokenVersion int32      `json:"edit_token_version"`
}

type Session struct {
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"user_id"`
	TokenHash     []byte      `json:"token_hash"`
	ExpiresAt     time.Time   `json:"expires_at"`
	Ip            *netip.Addr `json:"ip"`
	UserAgent     string      `json:"user_agent"`
	CreatedAt     time.Time   `json:"created_at"`
	LastSeenAt    time.Time   `json:"last_seen_at"`
	MfaVerifiedAt *time.Time  `json:"mfa_verified_at"`
}

type SlugBlocklist struct {
	Term      string    `json:"term"`
	Reason    string    `json:"reason"`
	CreatedAt time.Time `json:"created_at"`
}

type Template struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	Tags      []byte    `json:"tags"`
	Status    string    `json:"status"`
	IsPremium bool      `json:"is_premium"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	SortOrder int32     `json:"sort_order"`
}

type TemplateVersion struct {
	TemplateID  uuid.UUID  `json:"template_id"`
	Version     int32      `json:"version"`
	Manifest    []byte     `json:"manifest"`
	AssetsPath  string     `json:"assets_path"`
	CreatedBy   *uuid.UUID `json:"created_by"`
	CreatedAt   time.Time  `json:"created_at"`
	PublishedAt *time.Time `json:"published_at"`
}

type User struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	Name            string     `json:"name"`
	Status          string     `json:"status"`
	TotpSecret      *string    `json:"totp_secret"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
	TotpConfirmedAt *time.Time `json:"totp_confirmed_at"`
	TotpLastStep    int64      `json:"totp_last_step"`
}

type UserRole struct {
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}
