// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overview.sql

package store

import (
	"context"
)

const adminOverviewCounts = `-- name: AdminOverviewCounts :one
SELECT
    (SELECT count(*) FROM reports WHERE status IN ('open', 'reviewing')) AS open_reports,
    (SELECT count(*) FROM media WHERE uploaded_by = 'guest' AND moderation_status = 'pending') AS pending_guest_photos,
    (SELECT count(*) FROM users WHERE deleted_at IS NULL AND created_at >= now() - interval '7 days') AS new_users_7d,
    (SELECT count(*) FROM events WHERE published_at >= now() - interval '7 days') AS events_published_7d
`

type AdminOverviewCountsRow struct {
	OpenReports        int64 `json:"open_reports"`
	PendingGuestPhotos int64 `json:"pending_guest_photos"`
	NewUsers7d         int64 `json:"new_users_7d"`
	EventsPublished7d  int64 `json:"events_published_7d"`
}

// Each count is served by a partial or leading-column index.
func (q *Queries) AdminOverviewCounts(ctx context.Context) (AdminOverviewCountsRow, error) {
	row := q.db.QueryRow(ctx, adminOverviewCounts)
	var i AdminOverviewCountsRow
	err := row.Scan(
		&i.OpenReports,
		&i.PendingGuestPhotos,
		&i.NewUsers7d,
		&i.EventsPublished7d,
	)
	return i, err
}
