// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countOpenReports = `-- name: CountOpenReports :one
SELECT count(*) FROM reports WHERE status IN ('open', 'reviewing')
`

func (q *Queries) CountOpenReports(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenReports)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReport = `-- name: CreateReport :execrows
INSERT INTO reports (id, event_id, reporter_ip_hash, reason, details)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (event_id, reporter_ip_hash) WHERE status IN ('open', 'reviewing') DO NOTHING
`

type CreateReportParams struct {
	ID             uuid.UUID `json:"id"`
	EventID        uuid.UUID `json:"event_id"`
	ReporterIpHash []byte    `json:"reporter_ip_hash"`
	Reason         string    `json:"reason"`
	Details        string    `json:"details"`
}

// Zero rows: this reporter already has an open report for the event (silently ignored).
func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, createReport,
		arg.ID,
		arg.EventID,
		arg.ReporterIpHash,
		arg.Reason,
		arg.Details,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dismissReport = `-- name: DismissReport :one
WITH prev AS (
    SELECT x.id, x.status FROM reports x
    WHERE x.id = $2 AND x.status IN ('open', 'reviewing')
    FOR UPDATE
)
UPDATE reports p
SET status = 'dismissed', handled_by = $1::uuid, handled_at = now()
FROM prev
WHERE p.id = prev.id
RETURNING p.id, p.event_id, prev.status AS old_status, p.status AS new_status
`

type DismissReportParams struct {
	HandledBy uuid.UUID `json:"handled_by"`
	ReportID  uuid.UUID `json:"report_id"`
}

type DismissReportRow struct {
	ID        uuid.UUID `json:"id"`
	EventID   uuid.UUID `json:"event_id"`
	OldStatus string    `json:"old_status"`
	NewStatus string    `json:"new_status"`
}

func (q *Queries) DismissReport(ctx context.Context, arg DismissReportParams) (DismissReportRow, error) {
	row := q.db.QueryRow(ctx, dismissReport, arg.HandledBy, arg.ReportID)
	var i DismissReportRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.OldStatus,
		&i.NewStatus,
	)
	return i, err
}

const listReportsAdmin = `-- name: ListReportsAdmin :many
WITH page AS (
    SELECT p.id, p.event_id, p.reason, p.details, p.status, p.handled_by, p.handled_at, p.created_at
    FROM reports p
    WHERE p.status = $1::text
      AND (p.created_at, p.id) < ($2::timestamptz, $3::uuid)
    ORDER BY p.created_at DESC, p.id DESC
    LIMIT $4::int
)
SELECT page.id, page.event_id, page.reason, page.details, page.status, page.handled_by, page.handled_at, page.created_at,
       e.slug AS event_slug, e.title AS event_title, e.status AS event_status, u.email AS owner_email,
       oc.open_reports_for_event
FROM page
JOIN events e ON e.id = page.event_id
LEFT JOIN users u ON u.id = e.owner_id
CROSS JOIN LATERAL (
    SELECT count(*) AS open_reports_for_event FROM reports o
    WHERE o.event_id = page.event_id AND o.status IN ('open', 'reviewing')
) oc
ORDER BY page.created_at DESC, page.id DESC
`

type ListReportsAdminParams struct {
	Status          string    `json:"status"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	Lim             int32     `json:"lim"`
}

type ListReportsAdminRow struct {
	ID                  uuid.UUID  `json:"id"`
	EventID             uuid.UUID  `json:"event_id"`
	Reason              string     `json:"reason"`
	Details             string     `json:"details"`
	Status              string     `json:"status"`
	HandledBy           *uuid.UUID `json:"handled_by"`
	HandledAt           *time.Time `json:"handled_at"`
	CreatedAt           time.Time  `json:"created_at"`
	EventSlug           *string    `json:"event_slug"`
	EventTitle          string     `json:"event_title"`
	EventStatus         string     `json:"event_status"`
	OwnerEmail          *string    `json:"owner_email"`
	OpenReportsForEvent int64      `json:"open_reports_for_event"`
}

// Moderation queue for one status, newest first, with the event, its owner and the number of
// open reports against that event (counted only for the rows on this page).
func (q *Queries) ListReportsAdmin(ctx context.Context, arg ListReportsAdminParams) ([]ListReportsAdminRow, error) {
	rows, err := q.db.Query(ctx, listReportsAdmin,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportsAdminRow{}
	for rows.Next() {
		var i ListReportsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Reason,
			&i.Details,
			&i.Status,
			&i.HandledBy,
			&i.HandledAt,
			&i.CreatedAt,
			&i.EventSlug,
			&i.EventTitle,
			&i.EventStatus,
			&i.OwnerEmail,
			&i.OpenReportsForEvent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsForEvent = `-- name: ListReportsForEvent :many
SELECT id, event_id, reason, details, status, handled_by, handled_at, created_at
FROM reports
WHERE event_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type ListReportsForEventParams struct {
	EventID         uuid.UUID `json:"event_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	Lim             int32     `json:"lim"`
}

type ListReportsForEventRow struct {
	ID        uuid.UUID  `json:"id"`
	EventID   uuid.UUID  `json:"event_id"`
	Reason    string     `json:"reason"`
	Details   string     `json:"details"`
	Status    string     `json:"status"`
	HandledBy *uuid.UUID `json:"handled_by"`
	HandledAt *time.Time `json:"handled_at"`
	CreatedAt time.Time  `json:"created_at"`
}

// All reports against one event, newest first, for the admin event detail page.
// Caller already has the event/owner in hand, so no join is needed here.
func (q *Queries) ListReportsForEvent(ctx context.Context, arg ListReportsForEventParams) ([]ListReportsForEventRow, error) {
	rows, err := q.db.Query(ctx, listReportsForEvent,
		arg.EventID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportsForEventRow{}
	for rows.Next() {
		var i ListReportsForEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Reason,
			&i.Details,
			&i.Status,
			&i.HandledBy,
			&i.HandledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveOpenReportsForEvent = `-- name: ResolveOpenReportsForEvent :execrows
UPDATE reports
SET status = 'taken_down', handled_by = $1::uuid, handled_at = now()
WHERE event_id = $2 AND status IN ('open', 'reviewing')
`

type ResolveOpenReportsForEventParams struct {
	HandledBy uuid.UUID `json:"handled_by"`
	EventID   uuid.UUID `json:"event_id"`
}

// On takedown: every open report against the event is resolved as taken_down.
func (q *Queries) ResolveOpenReportsForEvent(ctx context.Context, arg ResolveOpenReportsForEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveOpenReportsForEvent, arg.HandledBy, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreReportsForEvent = `-- name: RestoreReportsForEvent :execrows
UPDATE reports
SET status = 'restored', handled_by = $1::uuid, handled_at = now()
WHERE event_id = $2 AND status = 'taken_down'
`

type RestoreReportsForEventParams struct {
	HandledBy uuid.UUID `json:"handled_by"`
	EventID   uuid.UUID `json:"event_id"`
}

// On restore: reports that led to the takedown are marked restored.
func (q *Queries) RestoreReportsForEvent(ctx context.Context, arg RestoreReportsForEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreReportsForEvent, arg.HandledBy, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
