// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rsvps.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRSVPs = `-- name: CountRSVPs :one
SELECT count(*) FROM rsvps WHERE event_id = $1
`

func (q *Queries) CountRSVPs(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRSVPs, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOpenRSVP = `-- name: CreateOpenRSVP :one
INSERT INTO rsvps (id, event_id, name, email, attending, count, answers)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, event_id, guest_id, name, email, attending, count, answers, edit_token_version, created_at, updated_at
`

type CreateOpenRSVPParams struct {
	ID        uuid.UUID `json:"id"`
	EventID   uuid.UUID `json:"event_id"`
	Name      string    `json:"name"`
	Email     *string   `json:"email"`
	Attending string    `json:"attending"`
	Count     int32     `json:"count"`
	Answers   []byte    `json:"answers"`
}

type CreateOpenRSVPRow struct {
	ID               uuid.UUID  `json:"id"`
	EventID          uuid.UUID  `json:"event_id"`
	GuestID          *uuid.UUID `json:"guest_id"`
	Name             string     `json:"name"`
	Email            *string    `json:"email"`
	Attending        string     `json:"attending"`
	Count            int32      `json:"count"`
	Answers          []byte     `json:"answers"`
	EditTokenVersion int32      `json:"edit_token_version"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

func (q *Queries) CreateOpenRSVP(ctx context.Context, arg CreateOpenRSVPParams) (CreateOpenRSVPRow, error) {
	row := q.db.QueryRow(ctx, createOpenRSVP,
		arg.ID,
		arg.EventID,
		arg.Name,
		arg.Email,
		arg.Attending,
		arg.Count,
		arg.Answers,
	)
	var i CreateOpenRSVPRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.GuestID,
		&i.Name,
		&i.Email,
		&i.Attending,
		&i.Count,
		&i.Answers,
		&i.EditTokenVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRSVP = `-- name: DeleteRSVP :execrows
DELETE FROM rsvps r
WHERE r.id = $1::uuid
  AND r.event_id = $2::uuid
  AND event_role($2::uuid, $3::uuid) IN ('owner', 'editor')
`

type DeleteRSVPParams struct {
	ID      uuid.UUID `json:"id"`
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteRSVP(ctx context.Context, arg DeleteRSVPParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRSVP, arg.ID, arg.EventID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const exportRSVPsBatch = `-- name: ExportRSVPsBatch :many
SELECT r.id, r.guest_id, r.name, r.email, r.attending, r.count, r.answers, r.created_at, r.updated_at
FROM rsvps r
WHERE r.event_id = $1::uuid
  AND event_role($1::uuid, $2::uuid) IS NOT NULL
  AND (r.created_at, r.id) > ($3::timestamptz, $4::uuid)
ORDER BY r.created_at, r.id
LIMIT $5::int
`

type ExportRSVPsBatchParams struct {
	EventID         uuid.UUID `json:"event_id"`
	UserID          uuid.UUID `json:"user_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	Lim             int32     `json:"lim"`
}

type ExportRSVPsBatchRow struct {
	ID        uuid.UUID  `json:"id"`
	GuestID   *uuid.UUID `json:"guest_id"`
	Name      string     `json:"name"`
	Email     *string    `json:"email"`
	Attending string     `json:"attending"`
	Count     int32      `json:"count"`
	Answers   []byte     `json:"answers"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// CSV export, oldest first, called in a loop with the last row as the cursor (lim ≤ 500).
func (q *Queries) ExportRSVPsBatch(ctx context.Context, arg ExportRSVPsBatchParams) ([]ExportRSVPsBatchRow, error) {
	rows, err := q.db.Query(ctx, exportRSVPsBatch,
		arg.EventID,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportRSVPsBatchRow{}
	for rows.Next() {
		var i ExportRSVPsBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.GuestID,
			&i.Name,
			&i.Email,
			&i.Attending,
			&i.Count,
			&i.Answers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGuestRSVP = `-- name: GetGuestRSVP :one
SELECT id, event_id, guest_id, name, email, attending, count, answers, created_at, updated_at
FROM rsvps
WHERE event_id = $1 AND guest_id = $2::uuid
`

type GetGuestRSVPParams struct {
	EventID uuid.UUID `json:"event_id"`
	GuestID uuid.UUID `json:"guest_id"`
}

type GetGuestRSVPRow struct {
	ID        uuid.UUID  `json:"id"`
	EventID   uuid.UUID  `json:"event_id"`
	GuestID   *uuid.UUID `json:"guest_id"`
	Name      string     `json:"name"`
	Email     *string    `json:"email"`
	Attending string     `json:"attending"`
	Count     int32      `json:"count"`
	Answers   []byte     `json:"answers"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

func (q *Queries) GetGuestRSVP(ctx context.Context, arg GetGuestRSVPParams) (GetGuestRSVPRow, error) {
	row := q.db.QueryRow(ctx, getGuestRSVP, arg.EventID, arg.GuestID)
	var i GetGuestRSVPRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.GuestID,
		&i.Name,
		&i.Email,
		&i.Attending,
		&i.Count,
		&i.Answers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRSVPForConfirmation = `-- name: GetRSVPForConfirmation :one
SELECT r.id, r.name, r.email, r.attending, r.count, r.guest_id, r.edit_token_version,
       g.token_version AS guest_token_version,
       e.id AS event_id, e.slug AS event_slug, e.title AS event_title, e.status AS event_status,
       e.starts_at AS event_starts_at, e.content AS event_content
FROM rsvps r
JOIN events e ON e.id = r.event_id
LEFT JOIN guests g ON g.id = r.guest_id
WHERE r.id = $1 AND e.deleted_at IS NULL
`

type GetRSVPForConfirmationRow struct {
	ID                uuid.UUID  `json:"id"`
	Name              string     `json:"name"`
	Email             *string    `json:"email"`
	Attending         string     `json:"attending"`
	Count             int32      `json:"count"`
	GuestID           *uuid.UUID `json:"guest_id"`
	EditTokenVersion  int32      `json:"edit_token_version"`
	GuestTokenVersion *int32     `json:"guest_token_version"`
	EventID           uuid.UUID  `json:"event_id"`
	EventSlug         *string    `json:"event_slug"`
	EventTitle        string     `json:"event_title"`
	EventStatus       string     `json:"event_status"`
	EventStartsAt     *time.Time `json:"event_starts_at"`
	EventContent      []byte     `json:"event_content"`
}

// send_rsvp_confirmation job. guest_token_version is set for guest RSVPs (the link is the invite link).
func (q *Queries) GetRSVPForConfirmation(ctx context.Context, id uuid.UUID) (GetRSVPForConfirmationRow, error) {
	row := q.db.QueryRow(ctx, getRSVPForConfirmation, id)
	var i GetRSVPForConfirmationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Attending,
		&i.Count,
		&i.GuestID,
		&i.EditTokenVersion,
		&i.GuestTokenVersion,
		&i.EventID,
		&i.EventSlug,
		&i.EventTitle,
		&i.EventStatus,
		&i.EventStartsAt,
		&i.EventContent,
	)
	return i, err
}

const getRSVPForEvent = `-- name: GetRSVPForEvent :one
SELECT id, event_id, guest_id, name, email, attending, count, answers, edit_token_version, created_at, updated_at
FROM rsvps
WHERE id = $1 AND event_id = $2
`

type GetRSVPForEventParams struct {
	ID      uuid.UUID `json:"id"`
	EventID uuid.UUID `json:"event_id"`
}

type GetRSVPForEventRow struct {
	ID               uuid.UUID  `json:"id"`
	EventID          uuid.UUID  `json:"event_id"`
	GuestID          *uuid.UUID `json:"guest_id"`
	Name             string     `json:"name"`
	Email            *string    `json:"email"`
	Attending        string     `json:"attending"`
	Count            int32      `json:"count"`
	Answers          []byte     `json:"answers"`
	EditTokenVersion int32      `json:"edit_token_version"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

func (q *Queries) GetRSVPForEvent(ctx context.Context, arg GetRSVPForEventParams) (GetRSVPForEventRow, error) {
	row := q.db.QueryRow(ctx, getRSVPForEvent, arg.ID, arg.EventID)
	var i GetRSVPForEventRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.GuestID,
		&i.Name,
		&i.Email,
		&i.Attending,
		&i.Count,
		&i.Answers,
		&i.EditTokenVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRSVPForToken = `-- name: GetRSVPForToken :one
SELECT r.id, r.event_id, r.guest_id, r.edit_token_version, e.slug AS event_slug, e.status AS event_status
FROM rsvps r
JOIN events e ON e.id = r.event_id
WHERE r.id = $1 AND e.deleted_at IS NULL
`

type GetRSVPForTokenRow struct {
	ID               uuid.UUID  `json:"id"`
	EventID          uuid.UUID  `json:"event_id"`
	GuestID          *uuid.UUID `json:"guest_id"`
	EditTokenVersion int32      `json:"edit_token_version"`
	EventSlug        *string    `json:"event_slug"`
	EventStatus      string     `json:"event_status"`
}

// Public. Load by the token's RSVP id, then verify the MAC against (id, edit_token_version).
func (q *Queries) GetRSVPForToken(ctx context.Context, id uuid.UUID) (GetRSVPForTokenRow, error) {
	row := q.db.QueryRow(ctx, getRSVPForToken, id)
	var i GetRSVPForTokenRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.GuestID,
		&i.EditTokenVersion,
		&i.EventSlug,
		&i.EventStatus,
	)
	return i, err
}

const listRSVPs = `-- name: ListRSVPs :many
SELECT r.id, r.guest_id, r.name, r.email, r.attending, r.count, r.answers, r.created_at, r.updated_at
FROM rsvps r
WHERE r.event_id = $1::uuid
  AND event_role($1::uuid, $2::uuid) IS NOT NULL
  AND ($3::text IS NULL OR r.attending = $3::text)
  AND (r.created_at, r.id) < ($4::timestamptz, $5::uuid)
ORDER BY r.created_at DESC, r.id DESC
LIMIT $6::int
`

type ListRSVPsParams struct {
	EventID         uuid.UUID `json:"event_id"`
	UserID          uuid.UUID `json:"user_id"`
	Attending       *string   `json:"attending"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	Lim             int32     `json:"lim"`
}

type ListRSVPsRow struct {
	ID        uuid.UUID  `json:"id"`
	GuestID   *uuid.UUID `json:"guest_id"`
	Name      string     `json:"name"`
	Email     *string    `json:"email"`
	Attending string     `json:"attending"`
	Count     int32      `json:"count"`
	Answers   []byte     `json:"answers"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// Any member. Newest first; attending NULL = all.
func (q *Queries) ListRSVPs(ctx context.Context, arg ListRSVPsParams) ([]ListRSVPsRow, error) {
	rows, err := q.db.Query(ctx, listRSVPs,
		arg.EventID,
		arg.UserID,
		arg.Attending,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRSVPsRow{}
	for rows.Next() {
		var i ListRSVPsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuestID,
			&i.Name,
			&i.Email,
			&i.Attending,
			&i.Count,
			&i.Answers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRSVPsUpdatedSince = `-- name: ListRSVPsUpdatedSince :many
SELECT r.id, r.name, r.attending, r.count, r.created_at, r.updated_at, count(*) OVER () AS total
FROM rsvps r
WHERE r.event_id = $1
  AND r.updated_at > coalesce($2::timestamptz, '-infinity')
  AND r.updated_at <= $3::timestamptz
ORDER BY r.updated_at DESC, r.id DESC
LIMIT 50
`

type ListRSVPsUpdatedSinceParams struct {
	EventID uuid.UUID  `json:"event_id"`
	Since   *time.Time `json:"since"`
	Until   time.Time  `json:"until"`
}

type ListRSVPsUpdatedSinceRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Attending string    `json:"attending"`
	Count     int32     `json:"count"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Total     int64     `json:"total"`
}

// Digest job: RSVPs changed in (since, until], newest first, at most 50, plus the total in range.
// since NULL = from the beginning.
func (q *Queries) ListRSVPsUpdatedSince(ctx context.Context, arg ListRSVPsUpdatedSinceParams) ([]ListRSVPsUpdatedSinceRow, error) {
	rows, err := q.db.Query(ctx, listRSVPsUpdatedSince, arg.EventID, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRSVPsUpdatedSinceRow{}
	for rows.Next() {
		var i ListRSVPsUpdatedSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Attending,
			&i.Count,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rSVPSummary = `-- name: RSVPSummary :one
WITH ev AS (
    SELECT x.id FROM events x
    WHERE x.id = $1::uuid AND event_role(x.id, $2::uuid) IS NOT NULL
)
SELECT count(r.id) FILTER (WHERE r.attending = 'yes') AS yes,
       count(r.id) FILTER (WHERE r.attending = 'no') AS no,
       count(r.id) FILTER (WHERE r.attending = 'maybe') AS maybe,
       coalesce(sum(r.count) FILTER (WHERE r.attending = 'yes'), 0)::bigint AS yes_heads,
       coalesce(sum(r.count) FILTER (WHERE r.attending = 'maybe'), 0)::bigint AS maybe_heads,
       count(r.id) AS total,
       count(r.guest_id) AS guests_responded,
       (SELECT count(*) FROM guests g WHERE g.event_id = ev.id) AS guests_total
FROM ev
LEFT JOIN rsvps r ON r.event_id = ev.id
GROUP BY ev.id
`

type RSVPSummaryParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type RSVPSummaryRow struct {
	Yes             int64 `json:"yes"`
	No              int64 `json:"no"`
	Maybe           int64 `json:"maybe"`
	YesHeads        int64 `json:"yes_heads"`
	MaybeHeads      int64 `json:"maybe_heads"`
	Total           int64 `json:"total"`
	GuestsResponded int64 `json:"guests_responded"`
	GuestsTotal     int64 `json:"guests_total"`
}

// Any member. No row when the caller has no access (the GROUP BY on the access CTE guarantees it).
func (q *Queries) RSVPSummary(ctx context.Context, arg RSVPSummaryParams) (RSVPSummaryRow, error) {
	row := q.db.QueryRow(ctx, rSVPSummary, arg.EventID, arg.UserID)
	var i RSVPSummaryRow
	err := row.Scan(
		&i.Yes,
		&i.No,
		&i.Maybe,
		&i.YesHeads,
		&i.MaybeHeads,
		&i.Total,
		&i.GuestsResponded,
		&i.GuestsTotal,
	)
	return i, err
}

const rotateRSVPEditToken = `-- name: RotateRSVPEditToken :one
UPDATE rsvps r
SET edit_token_version = r.edit_token_version + 1 -- updated_at untouched: not an answer change for the digest
WHERE r.id = $1::uuid
  AND r.event_id = $2::uuid
  AND event_role($2::uuid, $3::uuid) IN ('owner', 'editor')
RETURNING r.id, r.edit_token_version
`

type RotateRSVPEditTokenParams struct {
	ID      uuid.UUID `json:"id"`
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type RotateRSVPEditTokenRow struct {
	ID               uuid.UUID `json:"id"`
	EditTokenVersion int32     `json:"edit_token_version"`
}

// Owner or editor. Invalidates every edit link issued for the RSVP; the caller mints a new one from
// the returned version.
func (q *Queries) RotateRSVPEditToken(ctx context.Context, arg RotateRSVPEditTokenParams) (RotateRSVPEditTokenRow, error) {
	row := q.db.QueryRow(ctx, rotateRSVPEditToken, arg.ID, arg.EventID, arg.UserID)
	var i RotateRSVPEditTokenRow
	err := row.Scan(&i.ID, &i.EditTokenVersion)
	return i, err
}

const sumYesHeads = `-- name: SumYesHeads :one
SELECT coalesce(sum(count), 0)::int AS heads
FROM rsvps
WHERE event_id = $1 AND attending = 'yes' AND id IS DISTINCT FROM $2::uuid
`

type SumYesHeadsParams struct {
	EventID   uuid.UUID  `json:"event_id"`
	ExcludeID *uuid.UUID `json:"exclude_id"`
}

// Capacity check under the event lock. exclude_id leaves out the RSVP being edited.
func (q *Queries) SumYesHeads(ctx context.Context, arg SumYesHeadsParams) (int32, error) {
	row := q.db.QueryRow(ctx, sumYesHeads, arg.EventID, arg.ExcludeID)
	var heads int32
	err := row.Scan(&heads)
	return heads, err
}

const updateOpenRSVP = `-- name: UpdateOpenRSVP :one
UPDATE rsvps
SET name = $1, email = $2, attending = $3, count = $4, answers = $5,
    updated_at = now()
WHERE id = $6 AND event_id = $7 AND guest_id IS NULL AND edit_token_version = $8
RETURNING id, event_id, guest_id, name, email, attending, count, answers, edit_token_version, created_at, updated_at
`

type UpdateOpenRSVPParams struct {
	Name             string    `json:"name"`
	Email            *string   `json:"email"`
	Attending        string    `json:"attending"`
	Count            int32     `json:"count"`
	Answers          []byte    `json:"answers"`
	ID               uuid.UUID `json:"id"`
	EventID          uuid.UUID `json:"event_id"`
	EditTokenVersion int32     `json:"edit_token_version"`
}

type UpdateOpenRSVPRow struct {
	ID               uuid.UUID  `json:"id"`
	EventID          uuid.UUID  `json:"event_id"`
	GuestID          *uuid.UUID `json:"guest_id"`
	Name             string     `json:"name"`
	Email            *string    `json:"email"`
	Attending        string     `json:"attending"`
	Count            int32      `json:"count"`
	Answers          []byte     `json:"answers"`
	EditTokenVersion int32      `json:"edit_token_version"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

// edit_token_version is the one the caller verified the token against; a concurrent rotation
// makes this update no row.
func (q *Queries) UpdateOpenRSVP(ctx context.Context, arg UpdateOpenRSVPParams) (UpdateOpenRSVPRow, error) {
	row := q.db.QueryRow(ctx, updateOpenRSVP,
		arg.Name,
		arg.Email,
		arg.Attending,
		arg.Count,
		arg.Answers,
		arg.ID,
		arg.EventID,
		arg.EditTokenVersion,
	)
	var i UpdateOpenRSVPRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.GuestID,
		&i.Name,
		&i.Email,
		&i.Attending,
		&i.Count,
		&i.Answers,
		&i.EditTokenVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGuestRSVP = `-- name: UpsertGuestRSVP :one

INSERT INTO rsvps (id, event_id, guest_id, name, email, attending, count, answers)
VALUES ($1, $2, $3::uuid, $4, $5, $6, $7, $8)
ON CONFLICT (event_id, guest_id) WHERE guest_id IS NOT NULL DO UPDATE
SET name = EXCLUDED.name,
    email = EXCLUDED.email,
    attending = EXCLUDED.attending,
    count = EXCLUDED.count,
    answers = EXCLUDED.answers,
    updated_at = now()
RETURNING id, event_id, guest_id, name, email, attending, count, answers, created_at, updated_at,
          edit_token_version, (xmax = 0)::bool AS inserted
`

type UpsertGuestRSVPParams struct {
	ID        uuid.UUID `json:"id"`
	EventID   uuid.UUID `json:"event_id"`
	GuestID   uuid.UUID `json:"guest_id"`
	Name      string    `json:"name"`
	Email     *string   `json:"email"`
	Attending string    `json:"attending"`
	Count     int32     `json:"count"`
	Answers   []byte    `json:"answers"`
}

type UpsertGuestRSVPRow struct {
	ID               uuid.UUID  `json:"id"`
	EventID          uuid.UUID  `json:"event_id"`
	GuestID          *uuid.UUID `json:"guest_id"`
	Name             string     `json:"name"`
	Email            *string    `json:"email"`
	Attending        string     `json:"attending"`
	Count            int32      `json:"count"`
	Answers          []byte     `json:"answers"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	EditTokenVersion int32      `json:"edit_token_version"`
	Inserted         bool       `json:"inserted"`
}

// Public RSVP writes run after LockEventForRSVP in the same tx; the caller has already resolved
// the guest or RSVP identity from a verified token.
// One RSVP per invited guest. inserted is true for a new row.
func (q *Queries) UpsertGuestRSVP(ctx context.Context, arg UpsertGuestRSVPParams) (UpsertGuestRSVPRow, error) {
	row := q.db.QueryRow(ctx, upsertGuestRSVP,
		arg.ID,
		arg.EventID,
		arg.GuestID,
		arg.Name,
		arg.Email,
		arg.Attending,
		arg.Count,
		arg.Answers,
	)
	var i UpsertGuestRSVPRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.GuestID,
		&i.Name,
		&i.Email,
		&i.Attending,
		&i.Count,
		&i.Answers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditTokenVersion,
		&i.Inserted,
	)
	return i, err
}
