// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const clearUserMFAVerified = `-- name: ClearUserMFAVerified :exec
UPDATE sessions
SET mfa_verified_at = NULL
WHERE user_id = $1 AND mfa_verified_at IS NOT NULL
`

func (q *Queries) ClearUserMFAVerified(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserMFAVerified, userID)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, token_hash, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, token_hash, expires_at, ip, user_agent, created_at, last_seen_at, mfa_verified_at
`

type CreateSessionParams struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	TokenHash []byte      `json:"token_hash"`
	ExpiresAt time.Time   `json:"expires_at"`
	Ip        *netip.Addr `json:"ip"`
	UserAgent string      `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.MfaVerifiedAt,
	)
	return i, err
}

const deleteAllUserSessions = `-- name: DeleteAllUserSessions :many
DELETE FROM sessions
WHERE user_id = $1
RETURNING token_hash
`

func (q *Queries) DeleteAllUserSessions(ctx context.Context, userID uuid.UUID) ([][]byte, error) {
	rows, err := q.db.Query(ctx, deleteAllUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var token_hash []byte
		if err := rows.Scan(&token_hash); err != nil {
			return nil, err
		}
		items = append(items, token_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE id IN (SELECT id FROM sessions WHERE expires_at <= now() LIMIT 5000)
`

// Batched so one run never holds many row locks or bloats WAL; the job loops while rows > 0.
func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOtherUserSessions = `-- name: DeleteOtherUserSessions :many
DELETE FROM sessions
WHERE user_id = $1 AND id <> $2
RETURNING token_hash
`

type DeleteOtherUserSessionsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CurrentID uuid.UUID `json:"current_id"`
}

func (q *Queries) DeleteOtherUserSessions(ctx context.Context, arg DeleteOtherUserSessionsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, deleteOtherUserSessions, arg.UserID, arg.CurrentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var token_hash []byte
		if err := rows.Scan(&token_hash); err != nil {
			return nil, err
		}
		items = append(items, token_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const deleteUserSession = `-- name: DeleteUserSession :one
DELETE FROM sessions
WHERE id = $1 AND user_id = $2
RETURNING token_hash
`

type DeleteUserSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Returns the hash so the caller can drop the Valkey mirror entry.
func (q *Queries) DeleteUserSession(ctx context.Context, arg DeleteUserSessionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, deleteUserSession, arg.ID, arg.UserID)
	var token_hash []byte
	err := row.Scan(&token_hash)
	return token_hash, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT s.id, s.user_id, s.expires_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.expires_at > now()
  AND u.status = 'active'
  AND u.deleted_at IS NULL
`

type GetActiveSessionRow struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Only sessions that are unexpired and belong to an active, undeleted user.
func (q *Queries) GetActiveSession(ctx context.Context, tokenHash []byte) (GetActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSession, tokenHash)
	var i GetActiveSessionRow
	err := row.Scan(&i.ID, &i.UserID, &i.ExpiresAt)
	return i, err
}

const getAdminContext = `-- name: GetAdminContext :one
SELECT u.id AS user_id, u.email, u.totp_confirmed_at, s.mfa_verified_at,
       coalesce((SELECT array_agg(r.role ORDER BY r.role) FROM user_roles r WHERE r.user_id = u.id), '{}')::text[] AS roles
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1
  AND s.user_id = $2
  AND s.expires_at > now()
  AND u.status = 'active'
  AND u.deleted_at IS NULL
`

type GetAdminContextParams struct {
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type GetAdminContextRow struct {
	UserID          uuid.UUID  `json:"user_id"`
	Email           string     `json:"email"`
	TotpConfirmedAt *time.Time `json:"totp_confirmed_at"`
	MfaVerifiedAt   *time.Time `json:"mfa_verified_at"`
	Roles           []string   `json:"roles"`
}

// Read on every admin request. No row: session gone/expired or the user is not active.
func (q *Queries) GetAdminContext(ctx context.Context, arg GetAdminContextParams) (GetAdminContextRow, error) {
	row := q.db.QueryRow(ctx, getAdminContext, arg.SessionID, arg.UserID)
	var i GetAdminContextRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.TotpConfirmedAt,
		&i.MfaVerifiedAt,
		&i.Roles,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, created_at, last_seen_at, user_agent, ip
FROM sessions
WHERE user_id = $1 AND expires_at > now()
ORDER BY last_seen_at DESC, id DESC
LIMIT 50
`

type ListUserSessionsRow struct {
	ID         uuid.UUID   `json:"id"`
	CreatedAt  time.Time   `json:"created_at"`
	LastSeenAt time.Time   `json:"last_seen_at"`
	UserAgent  string      `json:"user_agent"`
	Ip         *netip.Addr `json:"ip"`
}

func (q *Queries) ListUserSessions(ctx context.Context, userID uuid.UUID) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSessionsRow{}
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.UserAgent,
			&i.Ip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionMFAVerified = `-- name: SetSessionMFAVerified :exec
UPDATE sessions
SET mfa_verified_at = now()
WHERE id = $1 AND user_id = $2
`

type SetSessionMFAVerifiedParams struct {
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) SetSessionMFAVerified(ctx context.Context, arg SetSessionMFAVerifiedParams) error {
	_, err := q.db.Exec(ctx, setSessionMFAVerified, arg.SessionID, arg.UserID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = now()
WHERE id = $1 AND last_seen_at < now() - interval '5 minutes'
`

// Writes at most once per 5 minutes per session.
func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
