// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: slugs.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const addBlockTerm = `-- name: AddBlockTerm :execrows
INSERT INTO slug_blocklist (term, reason)
VALUES ($1, $2)
ON CONFLICT (term) DO NOTHING
`

type AddBlockTermParams struct {
	Term   string `json:"term"`
	Reason string `json:"reason"`
}

// Zero rows: the term already exists.
func (q *Queries) AddBlockTerm(ctx context.Context, arg AddBlockTermParams) (int64, error) {
	result, err := q.db.Exec(ctx, addBlockTerm, arg.Term, arg.Reason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBlockTerm = `-- name: DeleteBlockTerm :one
DELETE FROM slug_blocklist
WHERE term = $1
RETURNING term, reason
`

type DeleteBlockTermRow struct {
	Term   string `json:"term"`
	Reason string `json:"reason"`
}

func (q *Queries) DeleteBlockTerm(ctx context.Context, term string) (DeleteBlockTermRow, error) {
	row := q.db.QueryRow(ctx, deleteBlockTerm, term)
	var i DeleteBlockTermRow
	err := row.Scan(&i.Term, &i.Reason)
	return i, err
}

const listBlocklist = `-- name: ListBlocklist :many
SELECT term, reason, created_at
FROM slug_blocklist
WHERE term > $1::text
ORDER BY term
LIMIT $2::int
`

type ListBlocklistParams struct {
	AfterTerm string `json:"after_term"`
	Lim       int32  `json:"lim"`
}

// Keyset on term; first page passes after_term = ”.
func (q *Queries) ListBlocklist(ctx context.Context, arg ListBlocklistParams) ([]SlugBlocklist, error) {
	rows, err := q.db.Query(ctx, listBlocklist, arg.AfterTerm, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlugBlocklist{}
	for rows.Next() {
		var i SlugBlocklist
		if err := rows.Scan(&i.Term, &i.Reason, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slugBlocked = `-- name: SlugBlocked :one
SELECT EXISTS (
    SELECT 1 FROM slug_blocklist b
    WHERE b.term = $1::text
       OR b.term = ANY(string_to_array($1::text, '-'))
       OR (length(b.term) >= 5 AND b.reason <> 'reserved'
           AND (strpos(replace($1::text, '-', ''), b.term) > 0
                OR strpos(translate(replace($1::text, '-', ''), '0134578', 'oleastb'), b.term) > 0))
) AS blocked
`

// Blocked when a term equals the slug or one of its '-' tokens, or (for abuse/brand terms of 5+
// chars) appears anywhere in the slug with hyphens removed, either as-is or with common leetspeak
// digit substitutions undone (0/1/3/4/5/7/8 -> o/l/e/a/s/t/b), so "s33youthere"/"paym3nt"/"veri7y"
// are still caught. The blocklist is small, so this is a single scan of it.
func (q *Queries) SlugBlocked(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, slugBlocked, slug)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const slugTaken = `-- name: SlugTaken :one
SELECT EXISTS (
    SELECT 1 FROM events e
    WHERE e.slug = $1::text AND e.id IS DISTINCT FROM $2::uuid
) AS taken
`

type SlugTakenParams struct {
	Slug           string     `json:"slug"`
	ExcludeEventID *uuid.UUID `json:"exclude_event_id"`
}

// exclude_event_id lets an event keep its own slug. Deleted events keep their slug reserved.
func (q *Queries) SlugTaken(ctx context.Context, arg SlugTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, slugTaken, arg.Slug, arg.ExcludeEventID)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}
