// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates_admin.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPublishedVersions = `-- name: CountPublishedVersions :one
SELECT count(*) FROM template_versions
WHERE template_id = $1 AND published_at IS NOT NULL
`

func (q *Queries) CountPublishedVersions(ctx context.Context, templateID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedVersions, templateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (id, slug, name, tags, is_premium)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, slug, name, tags, status, is_premium, created_at, updated_at
`

type CreateTemplateParams struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	Tags      []byte    `json:"tags"`
	IsPremium bool      `json:"is_premium"`
}

// A duplicate slug raises 23505 on templates_slug_key.
func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Tags,
		arg.IsPremium,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tags,
		&i.Status,
		&i.IsPremium,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemplateVersion = `-- name: CreateTemplateVersion :one
INSERT INTO template_versions (template_id, version, manifest, created_by)
SELECT $1::uuid, coalesce(max(tv.version), 0) + 1, $2::jsonb, $3::uuid
FROM template_versions tv
WHERE tv.template_id = $1::uuid
RETURNING template_id, version, assets_path, created_by, created_at, published_at
`

type CreateTemplateVersionParams struct {
	TemplateID uuid.UUID  `json:"template_id"`
	Manifest   []byte     `json:"manifest"`
	CreatedBy  *uuid.UUID `json:"created_by"`
}

type CreateTemplateVersionRow struct {
	TemplateID  uuid.UUID  `json:"template_id"`
	Version     int32      `json:"version"`
	AssetsPath  string     `json:"assets_path"`
	CreatedBy   *uuid.UUID `json:"created_by"`
	CreatedAt   time.Time  `json:"created_at"`
	PublishedAt *time.Time `json:"published_at"`
}

// New draft version n+1. Two concurrent creates collide on the primary key (23505) → 409 retry.
func (q *Queries) CreateTemplateVersion(ctx context.Context, arg CreateTemplateVersionParams) (CreateTemplateVersionRow, error) {
	row := q.db.QueryRow(ctx, createTemplateVersion, arg.TemplateID, arg.Manifest, arg.CreatedBy)
	var i CreateTemplateVersionRow
	err := row.Scan(
		&i.TemplateID,
		&i.Version,
		&i.AssetsPath,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getTemplateAdmin = `-- name: GetTemplateAdmin :one
SELECT id, slug, name, tags, status, is_premium, created_at, updated_at FROM templates WHERE id = $1
`

func (q *Queries) GetTemplateAdmin(ctx context.Context, templateID uuid.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateAdmin, templateID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tags,
		&i.Status,
		&i.IsPremium,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplateVersions = `-- name: ListTemplateVersions :many
SELECT template_id, version, assets_path, created_by, created_at, published_at
FROM template_versions
WHERE template_id = $1
ORDER BY version DESC
LIMIT 100
`

type ListTemplateVersionsRow struct {
	TemplateID  uuid.UUID  `json:"template_id"`
	Version     int32      `json:"version"`
	AssetsPath  string     `json:"assets_path"`
	CreatedBy   *uuid.UUID `json:"created_by"`
	CreatedAt   time.Time  `json:"created_at"`
	PublishedAt *time.Time `json:"published_at"`
}

// Without manifests (wide); fetch one with GetTemplateVersion.
func (q *Queries) ListTemplateVersions(ctx context.Context, templateID uuid.UUID) ([]ListTemplateVersionsRow, error) {
	rows, err := q.db.Query(ctx, listTemplateVersions, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplateVersionsRow{}
	for rows.Next() {
		var i ListTemplateVersionsRow
		if err := rows.Scan(
			&i.TemplateID,
			&i.Version,
			&i.AssetsPath,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesAdmin = `-- name: ListTemplatesAdmin :many
SELECT t.id, t.slug, t.name, t.tags, t.status, t.is_premium, t.created_at, t.updated_at,
       v.latest_version, v.latest_published_version
FROM templates t
CROSS JOIN LATERAL (
    SELECT coalesce(max(tv.version), 0)::int AS latest_version,
           coalesce(max(tv.version) FILTER (WHERE tv.published_at IS NOT NULL), 0)::int AS latest_published_version
    FROM template_versions tv
    WHERE tv.template_id = t.id
) v
ORDER BY t.name, t.id
LIMIT 200
`

type ListTemplatesAdminRow struct {
	ID                     uuid.UUID `json:"id"`
	Slug                   string    `json:"slug"`
	Name                   string    `json:"name"`
	Tags                   []byte    `json:"tags"`
	Status                 string    `json:"status"`
	IsPremium              bool      `json:"is_premium"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
	LatestVersion          int32     `json:"latest_version"`
	LatestPublishedVersion int32     `json:"latest_published_version"`
}

// Every template with its newest version and newest published version (0 = none).
func (q *Queries) ListTemplatesAdmin(ctx context.Context) ([]ListTemplatesAdminRow, error) {
	rows, err := q.db.Query(ctx, listTemplatesAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplatesAdminRow{}
	for rows.Next() {
		var i ListTemplatesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Tags,
			&i.Status,
			&i.IsPremium,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LatestVersion,
			&i.LatestPublishedVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishTemplateVersion = `-- name: PublishTemplateVersion :one
UPDATE template_versions
SET published_at = now()
WHERE template_id = $1 AND version = $2 AND published_at IS NULL
RETURNING published_at::timestamptz AS published_at
`

type PublishTemplateVersionParams struct {
	TemplateID uuid.UUID `json:"template_id"`
	Version    int32     `json:"version"`
}

func (q *Queries) PublishTemplateVersion(ctx context.Context, arg PublishTemplateVersionParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, publishTemplateVersion, arg.TemplateID, arg.Version)
	var published_at time.Time
	err := row.Scan(&published_at)
	return published_at, err
}

const setTemplateVersionAssets = `-- name: SetTemplateVersionAssets :execrows
UPDATE template_versions
SET assets_path = $1
WHERE template_id = $2 AND version = $3 AND published_at IS NULL
`

type SetTemplateVersionAssetsParams struct {
	AssetsPath string    `json:"assets_path"`
	TemplateID uuid.UUID `json:"template_id"`
	Version    int32     `json:"version"`
}

func (q *Queries) SetTemplateVersionAssets(ctx context.Context, arg SetTemplateVersionAssetsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTemplateVersionAssets, arg.AssetsPath, arg.TemplateID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTemplate = `-- name: UpdateTemplate :one
WITH prev AS (
    SELECT x.id, x.name, x.tags, x.status, x.is_premium FROM templates x
    WHERE x.id = $5
    FOR NO KEY UPDATE
)
UPDATE templates t
SET name = coalesce($1, t.name),
    tags = coalesce($2, t.tags),
    is_premium = coalesce($3, t.is_premium),
    status = coalesce($4, t.status),
    updated_at = now()
FROM prev
WHERE t.id = prev.id
  AND (coalesce($4::text, t.status) <> 'published'
       OR EXISTS (SELECT 1 FROM template_versions tv
                  WHERE tv.template_id = t.id AND tv.published_at IS NOT NULL))
RETURNING prev.name AS old_name, prev.tags AS old_tags, prev.status AS old_status, prev.is_premium AS old_is_premium,
          t.id, t.slug, t.name, t.tags, t.status, t.is_premium, t.created_at, t.updated_at
`

type UpdateTemplateParams struct {
	Name       *string   `json:"name"`
	Tags       []byte    `json:"tags"`
	IsPremium  *bool     `json:"is_premium"`
	Status     *string   `json:"status"`
	TemplateID uuid.UUID `json:"template_id"`
}

type UpdateTemplateRow struct {
	OldName      string    `json:"old_name"`
	OldTags      []byte    `json:"old_tags"`
	OldStatus    string    `json:"old_status"`
	OldIsPremium bool      `json:"old_is_premium"`
	ID           uuid.UUID `json:"id"`
	Slug         string    `json:"slug"`
	Name         string    `json:"name"`
	Tags         []byte    `json:"tags"`
	Status       string    `json:"status"`
	IsPremium    bool      `json:"is_premium"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// NULL leaves a field unchanged. Setting status 'published' requires a published version; no row
// then (or when the template is missing), which the caller maps with CountPublishedVersions.
func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (UpdateTemplateRow, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.Name,
		arg.Tags,
		arg.IsPremium,
		arg.Status,
		arg.TemplateID,
	)
	var i UpdateTemplateRow
	err := row.Scan(
		&i.OldName,
		&i.OldTags,
		&i.OldStatus,
		&i.OldIsPremium,
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tags,
		&i.Status,
		&i.IsPremium,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTemplateVersionManifest = `-- name: UpdateTemplateVersionManifest :execrows
UPDATE template_versions
SET manifest = $1
WHERE template_id = $2 AND version = $3 AND published_at IS NULL
`

type UpdateTemplateVersionManifestParams struct {
	Manifest   []byte    `json:"manifest"`
	TemplateID uuid.UUID `json:"template_id"`
	Version    int32     `json:"version"`
}

// Zero rows: missing or already published (version_published).
func (q *Queries) UpdateTemplateVersionManifest(ctx context.Context, arg UpdateTemplateVersionManifestParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTemplateVersionManifest, arg.Manifest, arg.TemplateID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
