// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const confirmUserTOTPStep = `-- name: ConfirmUserTOTPStep :execrows
UPDATE users
SET totp_last_step = $1,
    totp_confirmed_at = coalesce(totp_confirmed_at, now()),
    updated_at = now()
WHERE id = $2
  AND deleted_at IS NULL
  AND totp_secret IS NOT NULL
  AND totp_secret = $3::text
  AND totp_last_step < $1
`

type ConfirmUserTOTPStepParams struct {
	Step           int64     `json:"step"`
	UserID         uuid.UUID `json:"user_id"`
	ExpectedSecret string    `json:"expected_secret"`
}

// Records an accepted code. The step must be newer than the last one, so a code can't be replayed,
// even by two concurrent requests (the row lock serialises them and the second sees the new step).
// expected_secret must equal the secret that was actually verified: if a new enrolment
// (SetUserTOTPSecret) replaced totp_secret between verify and confirm, this no-ops instead of
// confirming a different, unverified secret.
func (q *Queries) ConfirmUserTOTPStep(ctx context.Context, arg ConfirmUserTOTPStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmUserTOTPStep, arg.Step, arg.UserID, arg.ExpectedSecret)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countSuperAdmins = `-- name: CountSuperAdmins :one
SELECT count(*)
FROM user_roles r
JOIN users u ON u.id = r.user_id
WHERE r.role = 'super_admin' AND u.deleted_at IS NULL AND u.status = 'active'
`

func (q *Queries) CountSuperAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSuperAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserAdmin = `-- name: GetUserAdmin :one
SELECT u.id, u.email, u.name, u.status, u.totp_confirmed_at, u.created_at, u.updated_at, u.deleted_at,
       coalesce((SELECT array_agg(r.role ORDER BY r.role) FROM user_roles r WHERE r.user_id = u.id), '{}')::text[] AS roles,
       (SELECT count(*) FROM events e WHERE e.owner_id = u.id AND e.deleted_at IS NULL) AS live_events,
       (SELECT count(*) FROM sessions s WHERE s.user_id = u.id AND s.expires_at > now()) AS active_sessions
FROM users u
WHERE u.id = $1
`

type GetUserAdminRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	Name            string     `json:"name"`
	Status          string     `json:"status"`
	TotpConfirmedAt *time.Time `json:"totp_confirmed_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
	Roles           []string   `json:"roles"`
	LiveEvents      int64      `json:"live_events"`
	ActiveSessions  int64      `json:"active_sessions"`
}

// Includes deleted (scrubbed) users so audit trails stay navigable.
func (q *Queries) GetUserAdmin(ctx context.Context, userID uuid.UUID) (GetUserAdminRow, error) {
	row := q.db.QueryRow(ctx, getUserAdmin, userID)
	var i GetUserAdminRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.TotpConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Roles,
		&i.LiveEvents,
		&i.ActiveSessions,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, status, totp_secret, created_at, updated_at, deleted_at, totp_confirmed_at, totp_last_step FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TotpConfirmedAt,
		&i.TotpLastStep,
	)
	return i, err
}

const getUserTOTP = `-- name: GetUserTOTP :one
SELECT id, email, totp_secret, totp_confirmed_at, totp_last_step
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserTOTPRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	TotpSecret      *string    `json:"totp_secret"`
	TotpConfirmedAt *time.Time `json:"totp_confirmed_at"`
	TotpLastStep    int64      `json:"totp_last_step"`
}

func (q *Queries) GetUserTOTP(ctx context.Context, userID uuid.UUID) (GetUserTOTPRow, error) {
	row := q.db.QueryRow(ctx, getUserTOTP, userID)
	var i GetUserTOTPRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TotpSecret,
		&i.TotpConfirmedAt,
		&i.TotpLastStep,
	)
	return i, err
}

const grantRole = `-- name: GrantRole :execrows
INSERT INTO user_roles (user_id, role)
SELECT u.id, $1::text
FROM users u
WHERE u.id = $2 AND u.deleted_at IS NULL
ON CONFLICT (user_id, role) DO NOTHING
`

type GrantRoleParams struct {
	Role   string    `json:"role"`
	UserID uuid.UUID `json:"user_id"`
}

// Zero rows: the role was already held or the user is missing/deleted.
func (q *Queries) GrantRole(ctx context.Context, arg GrantRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, grantRole, arg.Role, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT role FROM user_roles
WHERE user_id = $1
ORDER BY role
`

func (q *Queries) ListUserRoles(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRoles = `-- name: LockRoles :exec
SELECT pg_advisory_xact_lock(hashtextextended('syt:user_roles', 0))
`

// Serialises role changes so the "last super_admin" check can't race. Transaction-scoped.
func (q *Queries) LockRoles(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockRoles)
	return err
}

const resetUserTOTP = `-- name: ResetUserTOTP :execrows
WITH cleared AS (
    UPDATE sessions SET mfa_verified_at = NULL
    WHERE user_id = $1::uuid AND mfa_verified_at IS NOT NULL
)
UPDATE users u
SET totp_secret = NULL, totp_confirmed_at = NULL, updated_at = now()
WHERE u.id = $1::uuid AND u.deleted_at IS NULL
`

// Also drops the MFA step-up on the user's sessions. Rows affected counts users only.
func (q *Queries) ResetUserTOTP(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, resetUserTOTP, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRole = `-- name: RevokeRole :execrows
DELETE FROM user_roles WHERE user_id = $1 AND role = $2
`

type RevokeRoleParams struct {
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) RevokeRole(ctx context.Context, arg RevokeRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRole, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchUsersAdmin = `-- name: SearchUsersAdmin :many
WITH page AS (
    SELECT u.id, u.email, u.name, u.status, u.created_at
    FROM users u
    WHERE u.deleted_at IS NULL
      AND (u.created_at, u.id) < ($1::timestamptz, $2::uuid)
    ORDER BY u.created_at DESC, u.id DESC
    LIMIT $3::int
)
SELECT p.id, p.email, p.name, p.status, p.created_at,
       coalesce((SELECT array_agg(r.role ORDER BY r.role) FROM user_roles r WHERE r.user_id = p.id), '{}')::text[] AS roles
FROM page p
ORDER BY p.created_at DESC, p.id DESC
`

type SearchUsersAdminParams struct {
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	Lim             int32     `json:"lim"`
}

type SearchUsersAdminRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	Roles     []string  `json:"roles"`
}

// Admin browse, newest first (users_created_idx). First page: cursor = (far future, max uuid).
// Roles are aggregated only for the rows on the page.
func (q *Queries) SearchUsersAdmin(ctx context.Context, arg SearchUsersAdminParams) ([]SearchUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, searchUsersAdmin, arg.CursorCreatedAt, arg.CursorID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersAdminRow{}
	for rows.Next() {
		var i SearchUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersAdminByEmail = `-- name: SearchUsersAdminByEmail :many
SELECT u.id, u.email, u.name, u.status, u.created_at,
       coalesce((SELECT array_agg(r.role ORDER BY r.role) FROM user_roles r WHERE r.user_id = u.id), '{}')::text[] AS roles
FROM users u
WHERE u.email = $1 AND u.deleted_at IS NULL
  AND ($2::text IS NULL OR u.status = $2::text)
`

type SearchUsersAdminByEmailParams struct {
	Email  string  `json:"email"`
	Status *string `json:"status"`
}

type SearchUsersAdminByEmailRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	Roles     []string  `json:"roles"`
}

// Exact-address fast path (users_email_key). Returns at most one row.
func (q *Queries) SearchUsersAdminByEmail(ctx context.Context, arg SearchUsersAdminByEmailParams) ([]SearchUsersAdminByEmailRow, error) {
	rows, err := q.db.Query(ctx, searchUsersAdminByEmail, arg.Email, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersAdminByEmailRow{}
	for rows.Next() {
		var i SearchUsersAdminByEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersAdminByStatus = `-- name: SearchUsersAdminByStatus :many
WITH page AS (
    SELECT u.id, u.email, u.name, u.status, u.created_at
    FROM users u
    WHERE u.status = $1::text
      AND u.deleted_at IS NULL
      AND (u.created_at, u.id) < ($2::timestamptz, $3::uuid)
    ORDER BY u.created_at DESC, u.id DESC
    LIMIT $4::int
)
SELECT p.id, p.email, p.name, p.status, p.created_at,
       coalesce((SELECT array_agg(r.role ORDER BY r.role) FROM user_roles r WHERE r.user_id = p.id), '{}')::text[] AS roles
FROM page p
ORDER BY p.created_at DESC, p.id DESC
`

type SearchUsersAdminByStatusParams struct {
	Status          string    `json:"status"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	Lim             int32     `json:"lim"`
}

type SearchUsersAdminByStatusRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	Roles     []string  `json:"roles"`
}

// As SearchUsersAdmin, one status only (users_status_created_idx).
func (q *Queries) SearchUsersAdminByStatus(ctx context.Context, arg SearchUsersAdminByStatusParams) ([]SearchUsersAdminByStatusRow, error) {
	rows, err := q.db.Query(ctx, searchUsersAdminByStatus,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersAdminByStatusRow{}
	for rows.Next() {
		var i SearchUsersAdminByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersAdminText = `-- name: SearchUsersAdminText :many
WITH page AS (
    SELECT u.id, u.email, u.name, u.status, u.created_at
    FROM users u
    WHERE to_tsvector('simple', u.email || ' ' || u.name) @@ to_tsquery('simple', $1)
      AND u.deleted_at IS NULL
      AND ($2::text IS NULL OR u.status = $2::text)
      AND (u.created_at, u.id) < ($3::timestamptz, $4::uuid)
    ORDER BY u.created_at DESC, u.id DESC
    LIMIT $5::int
)
SELECT p.id, p.email, p.name, p.status, p.created_at,
       coalesce((SELECT array_agg(r.role ORDER BY r.role) FROM user_roles r WHERE r.user_id = p.id), '{}')::text[] AS roles
FROM page p
ORDER BY p.created_at DESC, p.id DESC
`

type SearchUsersAdminTextParams struct {
	PrefixQuery     string    `json:"prefix_query"`
	Status          *string   `json:"status"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	Lim             int32     `json:"lim"`
}

type SearchUsersAdminTextRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	Roles     []string  `json:"roles"`
}

// Prefix search over email and name (users_search_idx). prefix_query is built in Go from sanitised
// tokens, e.g. 'ali:* & example:*'. Keyset as SearchUsersAdmin; status NULL = any (a filter on
// the bitmap result, which the tsquery already narrows).
func (q *Queries) SearchUsersAdminText(ctx context.Context, arg SearchUsersAdminTextParams) ([]SearchUsersAdminTextRow, error) {
	rows, err := q.db.Query(ctx, searchUsersAdminText,
		arg.PrefixQuery,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersAdminTextRow{}
	for rows.Next() {
		var i SearchUsersAdminTextRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserStatus = `-- name: SetUserStatus :one
WITH prev AS (
    SELECT x.id, x.status FROM users x
    WHERE x.id = $2 AND x.deleted_at IS NULL
    FOR NO KEY UPDATE
)
UPDATE users u
SET status = $1, updated_at = now()
FROM prev
WHERE u.id = prev.id
RETURNING prev.status AS old_status, u.status AS new_status
`

type SetUserStatusParams struct {
	Status   string    `json:"status"`
	TargetID uuid.UUID `json:"target_id"`
}

type SetUserStatusRow struct {
	OldStatus string `json:"old_status"`
	NewStatus string `json:"new_status"`
}

// Returns the status before and after for the audit row. No row: user missing or deleted.
func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (SetUserStatusRow, error) {
	row := q.db.QueryRow(ctx, setUserStatus, arg.Status, arg.TargetID)
	var i SetUserStatusRow
	err := row.Scan(&i.OldStatus, &i.NewStatus)
	return i, err
}

const setUserTOTPSecret = `-- name: SetUserTOTPSecret :execrows
UPDATE users u
SET totp_secret = $1, updated_at = now()
WHERE u.id = $2
  AND u.deleted_at IS NULL
  AND u.totp_confirmed_at IS NULL
  AND EXISTS (SELECT 1 FROM user_roles r WHERE r.user_id = u.id)
`

type SetUserTOTPSecretParams struct {
	TotpSecret *string   `json:"totp_secret"`
	UserID     uuid.UUID `json:"user_id"`
}

// Starts (or restarts) enrolment. Only role holders may enrol, and a confirmed secret is never
// replaced here (an admin reset clears it first).
func (q *Queries) SetUserTOTPSecret(ctx context.Context, arg SetUserTOTPSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserTOTPSecret, arg.TotpSecret, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET email = 'deleted+' || id::text || '@deleted.invalid',
    name = '',
    totp_secret = NULL,
    totp_confirmed_at = NULL,
    deleted_at = now(),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// Scrubs PII immediately. The placeholder address keeps the lower-case check and frees the real
// address for a future sign-up (users_email_key only covers live rows anyway).
func (q *Queries) SoftDeleteUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, userID)
	return err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users
SET name = $1, updated_at = now()
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, email, name, status, totp_secret, created_at, updated_at, deleted_at, totp_confirmed_at, totp_last_step
`

type UpdateUserNameParams struct {
	Name   string    `json:"name"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.Name, arg.UserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TotpConfirmedAt,
		&i.TotpLastStep,
	)
	return i, err
}

const upsertUserByEmail = `-- name: UpsertUserByEmail :one
INSERT INTO users (id, email)
VALUES ($1, $2)
ON CONFLICT (email) WHERE deleted_at IS NULL
DO UPDATE SET updated_at = users.updated_at
RETURNING id, email, name, status, totp_secret, created_at, updated_at, deleted_at, totp_confirmed_at, totp_last_step
`

type UpsertUserByEmailParams struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

// Creates the user on first login; returns the existing row otherwise.
func (q *Queries) UpsertUserByEmail(ctx context.Context, arg UpsertUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByEmail, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TotpConfirmedAt,
		&i.TotpLastStep,
	)
	return i, err
}
